# Builds tablet.html from index.html's styles and helpers plus tablet_part.js.
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
src=open('index.html').read()
cut=src.index("Promise.all(['GSF','Rob','CMR','CMI']")
head=src[:cut].replace('body{margin:0;background:#dcd8cf;font-family:GSF,Rob;display:flex;gap:44px;padding:44px;align-items:flex-start}',
 'body{margin:0;background:#dcd8cf;font-family:GSF,Rob;padding:44px}\n#sheet{display:grid;grid-template-columns:1280px 1280px;gap:44px 64px}\n.tablet{width:1280px;height:800px;border-radius:32px;overflow:hidden;display:flex;flex-direction:column;background:var(--bg);color:var(--on);box-shadow:0 0 0 14px #1a1a1a,0 30px 60px rgba(0,0,0,.35)}')
head=head.replace('</style></head><body></body>','</style></head><body><div id="sheet"></div></body>')
open('tablet.html','w').write('<!-- Generated by build_tablet.py from index.html + tablet_part.js -->\n'+head+open('tablet_part.js').read()+'</script></html>')
