# Builds round9.html (the symbol builder, 3D solids and letters, STL export and the contour legend)
# from index.html's styles and helpers plus round9_part.js.
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
src=open('index.html').read()
cut=src.index("Promise.all(['GSF','Rob','CMR','CMI']")
head=src[:cut].replace('body{margin:0;background:#dcd8cf;font-family:GSF,Rob;display:flex;gap:44px;padding:44px;align-items:flex-start}',
 'body{margin:0;background:#dcd8cf;font-family:GSF,Rob;padding:44px}\n#sheet{display:flex;flex-wrap:wrap;gap:48px 40px;width:2720px;align-items:flex-start}\n#sheet>div[style*="grid-column"]{width:100%}\n'
 '.tablet{width:1280px;height:800px;border-radius:32px;overflow:hidden;display:flex;flex-direction:column;background:var(--bg);color:var(--on);box-shadow:0 0 0 14px #1a1a1a,0 30px 60px rgba(0,0,0,.35)}\n'
 '.dark{--tert:#A2D0C3;--ontert:#06372E}.light{--tert:#3B665C;--ontert:#FFFFFF}')
head=head.replace('</style></head><body></body>','</style></head><body><div id="sheet"></div></body>')
open('round9.html','w').write('<!-- Generated by build_round9.py from index.html + round9_part.js -->\n'+head+open('round9_part.js').read()+'</script></html>')
