// Generated by coordshots.kt
EX.sphGrad={e:"fn:grad{frac{'1;|'r;}}",x:"mat:3x1{'−;frac{'1;|'r;pow{'2;}}|'0;|'0;}",a:""};
EX.sphDiv={e:"fn:div{mat:3x1{'r;pow{'2;}|'0;|'0;}}",x:"'4;'r;",a:""};
EX.sphLap={e:"fn:laplacian{frac{'1;|'r;}}",x:"'0;",a:""};
EX.sphCurl={e:"fn:curl{mat:3x1{'0;|'0;|'r;fn:sin{'θ;}}}",x:"mat:3x1{'2;fn:cos{'θ;}|'−;'2;fn:sin{'θ;}|'0;}",a:""};
EX.zeta2={e:"fn:zeta{'2;}",x:"frac{'π;pow{'2;}|'6;}",a:"'1;'.;'6;'4;'4;' ;'9;'3;'4;' ;'0;'6;'7;"};
EX.ansTimes6={e:"'ans;'×;frac{'6;|'π;pow{'2;}}",x:"'1;",a:""};
