"""Regenerates app/src/main/java/com/example/cas/ui/theme/FontCoverage.kt from the bundled fonts."""
from fontTools.ttLib import TTFont
import os
here = os.path.dirname(os.path.abspath(__file__))
res = os.path.join(here, '..', 'app', 'src', 'main', 'res', 'font')
out = os.path.join(here, '..', 'app', 'src', 'main', 'java', 'com', 'example', 'cas', 'ui', 'theme', 'FontCoverage.kt')
fonts = {
    'GOOGLE_SANS_FLEX': 'google_sans_flex.ttf', 'ROBOTO': 'roboto.ttf', 'CM_ROMAN': 'cm_main.otf', 'CM_ITALIC': 'cm_italic.otf',
    'NCM_ROMAN': 'ncm_roman.otf', 'NCM_LATIN_ITALIC': 'ncm_latin_italic.otf',
}

def ranges(cps):
    cps = sorted(cps); rs = []
    for c in cps:
        if rs and c == rs[-1][1] + 1: rs[-1][1] = c
        else: rs.append([c, c])
    return rs

lines = ['package com.example.cas.ui.theme', '', '/*',
         ' * Which characters each bundled font really contains, taken from the fonts\'',
         ' * own character tables (generated by preview-render/font_coverage.py).',
         ' * Paint.hasGlyph can\'t be used for this: it also counts Android\'s system',
         ' * fallback fonts, so it reports Computer Modern as having τ or μ and the text',
         ' * then silently comes out in Roboto.', ' */', 'internal object FontCoverage {']
for name, f in fonts.items():
    cmap = TTFont(os.path.join(res, f)).getBestCmap()
    rs = ranges(cmap.keys())
    lines.append(f'    /** {f}: {len(cmap)} characters, as [first, last] ranges. */')
    lines.append(f'    val {name} = intArrayOf(' + ', '.join(f'{a}, {b}' for a, b in rs) + ')')
lines += ['', '    fun covers(ranges: IntArray, codePoint: Int): Boolean {', '        var lo = 0', '        var hi = ranges.size / 2 - 1',
          '        while (lo <= hi) {', '            val mid = (lo + hi) ushr 1', '            when {',
          '                codePoint < ranges[2 * mid] -> hi = mid - 1', '                codePoint > ranges[2 * mid + 1] -> lo = mid + 1',
          '                else -> return true', '            }', '        }', '        return false', '    }', '}', '']
open(out, 'w').write('\n'.join(lines))
print('wrote', out)
