import com.example.cas.cas.CD
import com.example.cas.editor.*
import com.example.cas.engine.Evaluator
import com.example.cas.graph.*
import java.awt.image.BufferedImage
import javax.imageio.ImageIO

fun r(text: String): MathRow { val out = MathRow(); for (c in text) when (c) { '²' -> out.add(Pow(row("2"))); else -> out.add(Sym(c.toString())) }; return out }
fun js(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

fun png(name: String, row: MathRow, params: List<String>, values: DoubleArray, view: Viewport, w: Int, h: Int, o: ColoringOptions): ComplexFunction {
    val f = ComplexCompiler.compile(Evaluator().evaluate(row), listOf("z") + params)
    val px = DomainColoring.render(f, values, view, w, h, o)!!
    val img = BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB)
    img.setRGB(0, 0, w, h, px, 0, w)
    ImageIO.write(img, "png", java.io.File("/home/claude/casshot/$name.png"))
    return f
}

fun cx(z: CD): String {
    fun s(v: Double) = (Math.round(v * 10000) / 10000.0).let { if (it == Math.rint(it)) it.toLong().toString() else it.toString() }.replace("-", "−")
    if (Math.abs(z.im) < 1e-9) return s(z.re)
    val im = s(Math.abs(z.im)).let { if (it == "1") "" else it } + "i"
    if (Math.abs(z.re) < 1e-9) return (if (z.im < 0) "−" else "") + im
    return s(z.re) + (if (z.im < 0) " − " else " + ") + im
}

fun main() {
    val out = StringBuilder("// Generated by complexshots.kt from DomainColoring.kt\n")
    val W = 412
    // 1: the classic example
    val classic = row(Frac(row(Sym("("), Sym("z"), Pow(row("2")), Sym("−"), Sym("1"), Sym(")"), Sym("("), Sym("z"), Sym("−"), Sym("2"), Sym("−"), Sym("i"), Sym(")"), Pow(row("2"))), r("z²+2+2i")))
    val v1 = Viewport.standard(630.0 / W, 3.0)
    val f1 = png("cp_classic", classic, emptyList(), DoubleArray(0), v1, W, 630, ColoringOptions())
    val probe = CD(1.0, 1.0)
    val w1 = f1(probe, DoubleArray(0))
    out.append("const CP1={row:${js(MathCodec.encode(classic))},view:[${v1.xMin},${v1.xMax},${v1.yMin},${v1.yMax}],h:630,probe:[${probe.re},${probe.im}],z:${js(cx(probe))},w:${js(cx(w1))},wv:[${w1.re},${w1.im}]};\n")
    // 2: Riemann zeta with phase lines, around the critical strip
    val zeta = row(Func("zeta", listOf(r("z"))))
    val v2 = Viewport(-7.0, 8.0, -3.0, -3.0 + 15.0 * 630 / W)
    png("cp_zeta", zeta, emptyList(), DoubleArray(0), v2, W, 630, ColoringOptions(phaseLines = true))
    out.append("const CP2={row:${js(MathCodec.encode(zeta))},view:[${v2.xMin},${v2.xMax},${v2.yMin},${v2.yMax}],h:630};\n")
    // 3: a loop around the pole at i of 1/(z² + 1)
    val g = row(Frac(row("1"), r("z²+1")))
    val v3 = Viewport.standard(600.0 / W, 2.5)
    val f3 = png("cp_loop", g, emptyList(), DoubleArray(0), v3, W, 600, ColoringOptions())
    val loop = List(80) { k -> val a = 2 * Math.PI * k / 80; val rr = 0.7 + 0.08 * Math.sin(3 * a); CD(rr * Math.cos(a), 1.0 + rr * Math.sin(a)) }
    val I = DomainColoring.contourIntegral(f3, DoubleArray(0), loop)
    out.append("const CP3={row:${js(MathCodec.encode(g))},view:[${v3.xMin},${v3.xMax},${v3.yMin},${v3.yMax}],h:600,loop:[${loop.joinToString(",") { "[${it.re},${it.im}]" }}],integral:${js(cx(I))},residues:${js(cx(DomainColoring.residueSum(I)))}};\n")
    // 4: z² − t with a slider, grid lines on (while editing)
    val zt = r("z²−t")
    val v4 = Viewport.standard(250.0 / W, 2.5)
    png("cp_zt", zt, listOf("t"), doubleArrayOf(1.5), v4, W, 250, ColoringOptions(grid = true))
    out.append("const CP4={row:${js(MathCodec.encode(zt))},view:[${v4.xMin},${v4.xMax},${v4.yMin},${v4.yMax}],h:250};\n")
    // 5: typing ζ(z) with the ℂ tab open: the view around the first zeros on Re z = ½
    val v5 = Viewport(-6.0, 7.0, 10.0, 10.0 + 13.0 * 200 / W)
    png("cp_zeta_edit", zeta, emptyList(), DoubleArray(0), v5, W, 200, ColoringOptions())
    out.append("const CP5={row:${js(MathCodec.encode(zeta))},view:[${v5.xMin},${v5.xMax},${v5.yMin},${v5.yMax}],h:200};\n")
    java.io.File("/home/claude/casshot/complex.js").writeText(out.toString())
    println("integral " + cx(I) + "  residues " + cx(DomainColoring.residueSum(I)))
}
