import com.example.cas.editor.*
import com.example.cas.engine.Evaluator
import com.example.cas.graph.*
fun js(d: Double) = String.format(java.util.Locale.US, "%.1f", d)
fun q(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
fun r(t: String): MathRow { val o = MathRow(); for (c in t) when (c) { '²' -> o.add(Pow(row("2"))); else -> o.add(Sym(c.toString())) }; return o }
fun main() {
    val sphereRow = r("x²+y²+z²=4")
    val saddleRow = row(Sym("z"), Sym("="), Frac(r("x²−y²"), r("4")))
    val b = Bounds(-2.5, 2.5, -2.5, 2.5, -2.5, 2.5)
    val cam = Camera()
    val w = 412f; val h = 520f
    val sphere = PlotSpec3D.classify(Evaluator().evaluate(sphereRow)) as PlotSpec3D.Implicit
    val saddle = PlotSpec3D.classify(Evaluator().evaluate(saddleRow)) as PlotSpec3D.Explicit
    val fs = Compiler.compile(sphere.f, listOf("x", "y", "z"))
    val fe = Compiler.compile(saddle.f, listOf("x", "y"))
    val polys = Surface3D.implicit({ x, y, z -> fs(doubleArrayOf(x, y, z)) }, b, 22, 0) + Surface3D.explicit({ x, y -> fe(doubleArrayOf(x, y)) }, b, 36, 1)
    val faces = Surface3D.faces(polys, b, cam, w, h)
    // Pick the point under the upper middle of the sphere.
    val (px, py) = Surface3D.project(0.8, -1.2, 1.4, b, cam, w, h)
    val hit = Surface3D.pick(faces, px, py)!!
    val c = hit.center
    val (mx, my) = Surface3D.project(c[0], c[1], c[2], b, cam, w, h)
    fun sn(v: Double) = (Math.round(v * 10000) / 10000.0).toString().replace("-", "−")
    val sb = StringBuilder("// Generated by gen3d.kt (Surface3D, PlotSpec3D)\nconst G9={w:$w,h:$h,")
    sb.append("faces:[" + faces.joinToString(",") { f -> "[[" + f.xs.indices.joinToString(",") { "${js(f.xs[it].toDouble())},${js(f.ys[it].toDouble())}" } + "],${js(f.shade.toDouble())},${js(f.height.toDouble())},${f.surface}]" } + "],")
    sb.append("box:[" + Surface3D.box(cam, w, h).joinToString(",") { "[${js(it.x1.toDouble())},${js(it.y1.toDouble())},${js(it.x2.toDouble())},${js(it.y2.toDouble())}]" } + "],")
    sb.append("labels:[" + Surface3D.axisLabels(cam, w, h).joinToString(",") { (n, p) -> "[\"$n\",${js(p.first.toDouble())},${js(p.second.toDouble())}]" } + "],")
    sb.append("pick:{x:${js(mx.toDouble())},y:${js(my.toDouble())},text:${q("(" + sn(c[0]) + ", " + sn(c[1]) + ", " + sn(c[2]) + ")")},r:${sn(Math.sqrt(c[0] * c[0] + c[1] * c[1] + c[2] * c[2]))}},")
    sb.append("rows:[${q(MathCodec.encode(sphereRow))},${q(MathCodec.encode(saddleRow))}]};\n")
    java.io.File("/home/claude/casshot/gen3d.js").writeText(sb.toString())
    println("faces ${faces.size}, picked ${c.joinToString { sn(it) }}, |p| = ${Math.sqrt(c[0] * c[0] + c[1] * c[1] + c[2] * c[2])}")
}
