import com.example.cas.cas.Coordinates
import com.example.cas.cas.CoordinateKind
import com.example.cas.cas.Expr
import com.example.cas.editor.Frac
import com.example.cas.editor.Func
import com.example.cas.editor.MathCodec
import com.example.cas.editor.MathRow
import com.example.cas.editor.Matrix
import com.example.cas.editor.Pow
import com.example.cas.editor.row
import com.example.cas.editor.Sym as ESym
import com.example.cas.engine.AngleUnit
import com.example.cas.engine.Evaluator
import com.example.cas.engine.Formatter
import com.example.cas.engine.UnitSystem
fun r(text: String): MathRow { val out = MathRow(); for (c in text) when (c) { '²' -> out.add(Pow(row("2"))); else -> out.add(ESym(c.toString())) }; return out }
fun js(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
fun main() {
    val sph = Coordinates(CoordinateKind.Spherical)
    val sb = StringBuilder("// Generated by coordshots.kt\n")
    fun ex(name: String, row: MathRow, c: Coordinates, ans: Expr? = null) {
        val v = Evaluator(AngleUnit.Radians, ans, emptyMap(), UnitSystem.SI, c).evaluate(row)
        val a = Formatter.answer(v)
        sb.append("EX.$name={e:${js(MathCodec.encode(row))},x:${js(MathCodec.encode(a.exact))},a:${js(a.approx?.let { MathCodec.encode(it) } ?: "")}};\n")
    }
    ex("sphGrad", row(Func("grad", listOf(row(Frac(r("1"), r("r")))))), sph)
    ex("sphDiv", row(Func("div", listOf(row(Matrix(3, 1, listOf(r("r²"), r("0"), r("0"))))))), sph)
    ex("sphLap", row(Func("laplacian", listOf(row(Frac(r("1"), r("r")))))), sph)
    val rotation = Matrix(3, 1, listOf(r("0"), r("0"), row(ESym("r"), Func("sin", listOf(r("θ"))))))
    ex("sphCurl", row(Func("curl", listOf(row(rotation)))), sph)
    val ans = Evaluator().evaluate(row(Func("zeta", listOf(r("2")))))
    ex("zeta2", row(Func("zeta", listOf(r("2")))), Coordinates())
    ex("ansTimes6", row(ESym("ans"), ESym("×"), Frac(row("6"), MathRow(mutableListOf(ESym("π"), Pow(row("2")))))), Coordinates(), ans)
    java.io.File("/home/claude/casshot/coords.js").writeText(sb.toString())
    println(sb)
}
