import com.example.cas.editor.MathCodec
import com.example.cas.engine.LatexParser
import com.example.cas.ui.KeyHelps
fun js(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
fun main() {
    val keys = listOf("integral", "normal density", "gradient", "contour integral", "inverse", "Riemann zeta function", "Neutron mass", "Newtonian constant of gravitation", "Taylor series", "e", "transpose")
    val sb = StringBuilder("// Generated by helpshots.kt: key help parsed by LatexParser\nconst HELP={\n")
    for (k in keys) {
        val h = KeyHelps.of(k)
        fun pieces(t: String) = "[" + LatexParser.inline(t).joinToString(",") { (m, p) -> if (m) "{m:${js(MathCodec.encode(LatexParser.parse(p)))}}" else "{t:${js(p)}}" } + "]"
        sb.append("  ${js(k)}:{title:${js(h.title)},formula:[${LatexParser.lines(h.formula).joinToString(",") { js(MathCodec.encode(it)) }}],about:${pieces(h.about)},usage:${pieces(h.usage)},link:${h.link?.let { js(it) } ?: "null"}},\n")
    }
    sb.append("};\n")
    java.io.File("/home/claude/casshot/help.js").writeText(sb.toString())
    println(sb.toString().lines().take(3).joinToString("\n").take(400))
}
