"""
The app icon: a curve in a hexagon over three axes, from the designer's 1080 × 1080 artboards
(green for the icon, black for the themed one). Writes the launcher icon (adaptive layers and
themed monochrome), the Play Store icon (512 × 512) and the feature graphic (1024 × 500).

  python3 icon_artboard.py      writes the vector drawables and store/*.svg (rendered by
                                render_store.py to PNG)
"""
import os, re

BG, AXES, INK = '#3E4F3C', '#7F886B', '#F3ECDA'
HEXAGON = 'M809.6,684.27v-268.05c0-13.77-7.34-26.49-19.27-33.37l-232.14-134.03c-11.92-6.88-26.61-6.88-38.53,0l-232.14,134.03c-11.92,6.88-19.27,19.6-19.27,33.37v268.05c0,13.77,7.34,26.49,19.27,33.37l232.14,134.03c11.92,6.88,26.61,6.88,38.53,0l232.14-134.03c11.92-6.88,19.27-19.6,19.27-33.37Z'
CURVE = 'M363.24,545.48c3.62-15.66,9.46-30.7,17.31-44.8,9.48-18.06,21.36-34.57,36.04-48.77,24.91-25.67,57.69-46.18,94.01-48.86,31.68-2.14,58.82,17.31,71.71,45.59,10.58,23.27,10.96,49.82,8.42,74.86-4.5,35.08-17.67,69.32-38.97,97.65-12.04,16.1-27.75,32.11-47.92,36.54-10.86,2.33-21.88-1.89-27.19-11.53-7.14-13.15-5.19-29.39-2.25-43.6,6.01-25.9,20.46-48.74,36.26-69.79,10.1-13.54,22.12-25.4,35.73-35.4,17.11-12.9,36.03-24.34,57.18-28.71,27.58-5.75,57.69,0.2,75.79,23.19,15.81,19.43,22.08,45.19,22.65,69.83,0.2,16.68-2.41,33.26-6,49.47-3.4,14.93-9.25,28.92-16.06,42.6-4.3,8.53-8.81,17.12-14.16,25.08-10.27,14.72-23.11,28.84-38.72,37.64-15.22,8.68-35.43,7.83-42.74-10.08-4.46-10.56-3.21-22.61-2.31-33.85'
AXIS_LINES = [(169.6, 766.19, 538.54, 559.05), (910.4, 761.28, 538.54, 559.05), (538.54, 127.17, 538.54, 559.05)]
MONO_SHIFT = 8.84   # the black artboard has the drawing this much lower

def axes(dy=0.0): return ''.join(f'M{a},{b + dy:.2f}L{c},{d + dy:.2f}' for a, b, c, d in AXIS_LINES)
def moved(path, dy):
    m = re.match(r'M([\d.]+),([\d.]+)', path)
    return f'M{m[1]},{float(m[2]) + dy:.2f}' + path[m.end():]

# A launcher shows the middle 72dp of the 108dp canvas: the artboard goes there, so every mask
# shape shows it whole, as drawn.
GROUP = '<group android:translateX="18" android:translateY="18" android:scaleX="0.0666667" android:scaleY="0.0666667">'

def vector(note, body):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- {note} Generated by preview-render/icon_artboard.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    {GROUP}
{body}
    </group>
</vector>
'''

def launcher(res):
    d = os.path.join(res, 'drawable')
    open(os.path.join(d, 'ic_launcher_foreground.xml'), 'w').write(vector('The app icon: a curve in a hexagon, over three axes.', f'''        <path android:strokeColor="#FF{AXES[1:]}" android:strokeWidth="45" android:strokeLineCap="round" android:pathData="{axes()}"/>
        <path android:strokeColor="#FF{INK[1:]}" android:strokeWidth="55" android:strokeMiterLimit="10" android:pathData="{HEXAGON}"/>
        <path android:strokeColor="#FF{INK[1:]}" android:strokeWidth="38" android:strokeLineCap="round" android:pathData="{CURVE}"/>'''))
    # Themed icons are tinted by alpha: the axes at 40%, as on the black artboard.
    open(os.path.join(d, 'ic_launcher_monochrome.xml'), 'w').write(vector('Themed icon (Android 13+): the icon in one color, the axes faint.', f'''        <path android:strokeColor="#FF000000" android:strokeAlpha="0.4" android:strokeWidth="45" android:strokeLineCap="round" android:pathData="{axes(MONO_SHIFT)}"/>
        <path android:strokeColor="#FF000000" android:strokeWidth="55" android:strokeMiterLimit="10" android:pathData="{moved(HEXAGON, MONO_SHIFT)}"/>
        <path android:strokeColor="#FF000000" android:strokeWidth="38" android:strokeLineCap="round" android:pathData="{moved(CURVE, MONO_SHIFT)}"/>'''))
    open(os.path.join(d, 'ic_launcher_background.xml'), 'w').write(f'''<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="#FF{BG[1:]}" />
</shape>
''')

def art(transform=''):
    return f'''<g{f' transform="{transform}"' if transform else ''}>
<path d="{axes()}" fill="none" stroke="{AXES}" stroke-width="45" stroke-linecap="round"/>
<path d="{HEXAGON}" fill="none" stroke="{INK}" stroke-width="55" stroke-miterlimit="10"/>
<path d="{CURVE}" fill="none" stroke="{INK}" stroke-width="38" stroke-linecap="round"/>
</g>'''

def play_icon(out):
    open(out, 'w').write(f'''<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 1080 1080">
<rect width="1080" height="1080" fill="{BG}"/>
{art()}
</svg>
''')

def feature(out, text=True):
    W, H = 1024, 500
    cx, s = (778, 0.5) if text else (512, 0.58)
    # The drawing's middle is near (540, 500) on the artboard.
    t = f'translate({cx - 540 * s:.1f},{H / 2 - 500 * s:.1f}) scale({s})'
    words = ''
    if text:
        style = "font-family:GSF;font-variation-settings:'ROND' 100"
        words = f'''<text x="80" y="176" font-size="66" fill="{INK}" style="{style};font-weight:650">CAS Scientific</text>
<text x="80" y="250" font-size="66" fill="{INK}" style="{style};font-weight:650">Calculator</text>
<text x="84" y="316" font-size="28" fill="#C9D3A8" style="{style};font-weight:500">Algebra, calculus and graphing</text>
<text x="84" y="356" font-size="28" fill="#A9B39A" style="{style};font-weight:450">in 2D, 3D and the complex plane</text>'''
    open(out, 'w').write(f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
<defs><radialGradient id="bg" cx="{cx}" cy="230" r="520" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#4A5D47"/><stop offset="1" stop-color="{BG}"/></radialGradient></defs><rect width="{W}" height="{H}" fill="url(#bg)"/>
{art(t)}
{words}
</svg>
''')

if __name__ == '__main__':
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    launcher(os.path.join(root, 'app/src/main/res'))
    store = os.path.join(root, 'store')
    play_icon(os.path.join(store, 'icon-512.svg'))
    feature(os.path.join(store, 'feature-graphic.svg'), text=True)
    feature(os.path.join(store, 'feature-graphic-plain.svg'), text=False)
