"""
The app icon: a saddle z = x² − y² with the curve that bends up (mint) and the one that bends
down (gold) through its middle. Draws it for the launcher icon (adaptive layers, themed
monochrome), the Play Store icon (512 × 512) and the feature graphic (1024 × 500).

  python3 icon_saddle.py        writes the vector drawables and store/*.svg (rendered by
                                render_store.py to PNG)
"""
import math, os

AZ, ZK, EL = 0.6, 0.8, 0.55            # the view chosen from the contact sheet of angles
CA, SA, CE = math.cos(AZ), math.sin(AZ), math.sqrt(1 - EL * EL)
BG, SURF_TOP, SURF_UNDER = '#0E2A3A', '#2F6F7E', '#1E4D5C'
MINT, GOLD = '#8BE9C9', '#FFD27A'

def p0(x, y):
    z = (x * x - y * y) * ZK
    return (x * CA - y * SA, (x * SA + y * CA) * EL - z * CE)

def depth(x, y): return x * SA + y * CA

def outline(n=24):
    pts = [(-1 + 2 * i / n, -1) for i in range(n + 1)] + [(1, -1 + 2 * i / n) for i in range(1, n + 1)] \
        + [(1 - 2 * i / n, 1) for i in range(1, n + 1)] + [(-1, 1 - 2 * i / n) for i in range(1, n)]
    return pts

class Frame:
    """Maps the saddle into a box: centred on (cx, cy), fitted so no point is further than
    [radius] from the centre (for masks) or so it spans [width] across."""
    def __init__(self, cx, cy, radius=None, width=None):
        raw = [p0(-1 + i / 20, -1 + j / 20) for i in range(41) for j in range(41)]
        xs, ys = [p[0] for p in raw], [p[1] for p in raw]
        self.ox, self.oy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
        if radius: self.s = radius / max(math.hypot(x - self.ox, y - self.oy) for x, y in raw)
        else: self.s = width / (max(xs) - min(xs))
        self.cx, self.cy = cx, cy
    def P(self, x, y):
        a, b = p0(x, y)
        return (self.cx + (a - self.ox) * self.s, self.cy + (b - self.oy) * self.s)

def f(v): return f"{v:.2f}".rstrip('0').rstrip('.')
def path(pts, close=False): return 'M' + 'L'.join(f"{f(x)},{f(y)}" for x, y in pts) + ('Z' if close else '')

def faces(F, n=14):
    """Cells back to front, each (path, facing up)."""
    cells = []
    for i in range(n):
        for j in range(n):
            x0, x1, y0, y1 = -1 + 2 * i / n, -1 + 2 * (i + 1) / n, -1 + 2 * j / n, -1 + 2 * (j + 1) / n
            a, b, c, d = F.P(x0, y0), F.P(x1, y0), F.P(x1, y1), F.P(x0, y1)
            cross = (b[0] - a[0]) * (d[1] - a[1]) - (b[1] - a[1]) * (d[0] - a[0])
            cells.append((depth((x0 + x1) / 2, (y0 + y1) / 2), path([a, b, c, d], True), cross > 0))
    cells.sort(key=lambda c: c[0])
    return [(p, up) for _, p, up in cells]

def curve_x(F, n=40): return path([F.P(-1 + 2 * i / n, 0) for i in range(n + 1)])
def curve_y(F, n=40): return path([F.P(0, -1 + 2 * i / n) for i in range(n + 1)])

def svg_saddle(F, stroke):
    """The saddle as SVG elements; [stroke] is the curves' width."""
    out = []
    for p, up in faces(F):
        c = SURF_TOP if up else SURF_UNDER
        out.append(f'<path d="{p}" fill="{c}" stroke="{c}" stroke-width="{f(stroke * .15)}"/>')
    out.append(f'<path d="{path([F.P(*q) for q in outline()], True)}" fill="none" stroke="{MINT}" stroke-width="{f(stroke * .45)}" stroke-linejoin="round" opacity=".6"/>')
    out.append(f'<path d="{curve_x(F)}" fill="none" stroke="{MINT}" stroke-width="{f(stroke)}" stroke-linecap="round"/>')
    out.append(f'<path d="{curve_y(F)}" fill="none" stroke="{GOLD}" stroke-width="{f(stroke)}" stroke-linecap="round"/>')
    return '\n'.join(out)

# ---- Android vector drawables (108 × 108 dp, content inside the 66 dp safe circle) -------------

def vector(body, comment):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- {comment} Generated by preview-render/icon_saddle.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
{body}
</vector>
'''

def launcher(res):
    F = Frame(54, 54, radius=32)   # inside the 33 dp safe circle, with room for the stroke caps
    body = []
    for p, up in faces(F):
        c = 'FF' + (SURF_TOP if up else SURF_UNDER)[1:]
        body.append(f'    <path android:fillColor="#{c}" android:strokeColor="#{c}" android:strokeWidth="0.5" android:pathData="{p}"/>')
    body.append(f'    <path android:strokeColor="#99{MINT[1:]}" android:strokeWidth="1.6" android:strokeLineJoin="round" android:pathData="{path([F.P(*q) for q in outline()], True)}"/>')
    body.append(f'    <path android:strokeColor="#FF{MINT[1:]}" android:strokeWidth="4.2" android:strokeLineCap="round" android:pathData="{curve_x(F)}"/>')
    body.append(f'    <path android:strokeColor="#FF{GOLD[1:]}" android:strokeWidth="4.2" android:strokeLineCap="round" android:pathData="{curve_y(F)}"/>')
    open(os.path.join(res, 'drawable/ic_launcher_foreground.xml'), 'w').write(vector('\n'.join(body), 'The saddle z = x² − y² with its two curves: mint bends up, gold bends down.'))
    mono = [
        f'    <path android:strokeColor="#FF000000" android:strokeWidth="2.4" android:strokeLineJoin="round" android:pathData="{path([F.P(*q) for q in outline()], True)}"/>',
        f'    <path android:strokeColor="#FF000000" android:strokeWidth="3.4" android:strokeLineCap="round" android:pathData="{curve_x(F)}"/>',
        f'    <path android:strokeColor="#FF000000" android:strokeWidth="3.4" android:strokeLineCap="round" android:pathData="{curve_y(F)}"/>',
    ]
    open(os.path.join(res, 'drawable/ic_launcher_monochrome.xml'), 'w').write(vector('\n'.join(mono), 'Themed icon (Android 13+): the saddle as line art.'))
    open(os.path.join(res, 'drawable/ic_launcher_background.xml'), 'w').write(f'''<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="#FF{BG[1:]}" />
</shape>
''')

# ---- Store graphics ---------------------------------------------------------------------------

def glow(cx, cy, r, id_):
    return (f'<defs><radialGradient id="{id_}" cx="{f(cx)}" cy="{f(cy)}" r="{f(r)}" gradientUnits="userSpaceOnUse">'
            f'<stop offset="0" stop-color="#1B4A60"/><stop offset="1" stop-color="{BG}"/></radialGradient></defs>')

def play_icon(out):
    # Full-bleed 512 square; Play rounds the corners itself, so the saddle stays inside ~80 %.
    F = Frame(256, 262, width=400)
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
{glow(256, 230, 360, 'bg')}<rect width="512" height="512" fill="url(#bg)"/>
{svg_saddle(F, 20)}
</svg>'''
    open(out, 'w').write(svg)

def feature(out, text=True):
    W, H = 1024, 500
    F = Frame(778 if text else 512, 252, width=400 if text else 520)
    words = ''
    if text:
        words = f'''<text x="84" y="226" font-size="92" fill="#F2FBF8" style="font-family:GSF;font-weight:650;font-variation-settings:'ROND' 100">CasCalc</text>
<text x="88" y="292" font-size="30" fill="{MINT}" style="font-family:GSF;font-weight:500;font-variation-settings:'ROND' 100">Algebra, calculus and graphing</text>
<text x="88" y="334" font-size="30" fill="#BFD6DE" style="font-family:GSF;font-weight:450;font-variation-settings:'ROND' 100">in 2D, 3D and the complex plane</text>'''
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
{glow(F.cx, 230, 520, 'bg')}<rect width="{W}" height="{H}" fill="url(#bg)"/>
{svg_saddle(F, 22)}
{words}
</svg>'''
    open(out, 'w').write(svg)

if __name__ == '__main__':
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    launcher(os.path.join(root, 'app/src/main/res'))
    store = os.path.join(root, 'store'); os.makedirs(store, exist_ok=True)
    play_icon(os.path.join(store, 'icon-512.svg'))
    feature(os.path.join(store, 'feature-graphic.svg'), text=True)
    feature(os.path.join(store, 'feature-graphic-plain.svg'), text=False)
