package com.example.cas.ui

/**
 * What the documentation's examples give, worked out by the calculator itself: the exact
 * answer and the decimal (if there is one) in LaTeX, by the example's saved form (with |deg
 * for degrees). Made by a test from [Docs.allExamples]; DocsTest checks it still holds.
 */
object DocsResults {
    val answers: Map<String, Pair<String, String?>> = mapOf(
        """frac{'1;|'3;}'+;frac{'1;|'6;}""" to ("""\frac{1}{2}""" to """0.5"""),
        """'2;pow{'1;'0;}""" to ("""1024""" to null),
        """sqrt{'7;'2;}""" to ("""6\sqrt{2}""" to """8.485\,281\,374"""),
        """sqrt{'2;}sqrt{'8;}""" to ("""4""" to null),
        """'2;'π;'+;frac{'π;|'2;}""" to ("""\frac{5\pi}{2}""" to """7.853\,981\,634"""),
        """'a;':=;'3;""" to ("""a=3""" to null),
        """'f;'(;'x;');'=;'x;pow{'2;}'+;'1;""" to ("""\operatorname{f}\left(x\right)=x^{2}+1""" to null),
        """frac{'2;|'3;}'×;frac{'9;|'4;}""" to ("""\frac{3}{2}""" to """1.5"""),
        """frac{frac{'1;|'2;}|frac{'3;|'4;}}""" to ("""\frac{2}{3}""" to """0.666\,666\,666\,7"""),
        """'2;pow{'−;'3;}""" to ("""\frac{1}{8}""" to """0.125"""),
        """'8;pow{frac{'2;|'3;}}""" to ("""4""" to null),
        """'(;'−;'2;');pow{'5;}""" to ("""-32""" to null),
        """'0;'.;'1;'2;'5;'+;frac{'3;|'8;}""" to ("""\frac{1}{2}""" to """0.5"""),
        """sqrt{'7;'2;}""" to ("""6\sqrt{2}""" to """8.485\,281\,374"""),
        """root{'3;|'−;'2;'7;}""" to ("""-3""" to null),
        """root{'4;|'1;'6;}""" to ("""2""" to null),
        """frac{'1;|sqrt{'2;}}""" to ("""\frac{\sqrt{2}}{2}""" to """0.707\,106\,781\,2"""),
        """sqrt{'1;'2;}'+;sqrt{'2;'7;}""" to ("""5\sqrt{3}""" to """8.660\,254\,038"""),
        """sqrt{'−;'1;'6;}""" to ("""4i""" to null),
        """'2;'0;'!;""" to ("""2.432\,902\times 10^{18}""" to null),
        """binom{'1;'0;|'3;}""" to ("""120""" to null),
        """fn:perm{'1;'0;|'3;}""" to ("""720""" to null),
        """'1;'7;'mod;'5;""" to ("""2""" to null),
        """fn:gcd{'8;'4;|'3;'6;}""" to ("""12""" to null),
        """fn:lcm{'4;|'6;}""" to ("""12""" to null),
        """fn:abs{'−;'7;}""" to ("""7""" to null),
        """fn:floor{'3;'.;'7;}""" to ("""3""" to null),
        """fn:ceil{'3;'.;'2;}""" to ("""4""" to null),
        """fn:round{'2;'.;'5;}""" to ("""3""" to null),
        """fn:frac{'3;'.;'7;'5;}""" to ("""\frac{3}{4}""" to """0.75"""),
        """fn:min{'3;|'1;}""" to ("""1""" to null),
        """fn:max{'3;|'1;}""" to ("""3""" to null),
        """'2;'5;'%;""" to ("""\frac{1}{4}""" to """0.25"""),
        """'6;'.;'0;'2;'×;'1;'0;pow{'2;'3;}'×;'2;""" to ("""1.204\times 10^{24}""" to null),
        """'1;'.;'6;'×;'1;'0;pow{'−;'1;'9;}'×;'6;'.;'2;'4;'×;'1;'0;pow{'1;'8;}""" to ("""\frac{624}{625}""" to """0.9984"""),
        """'e;pow{'0;}""" to ("""1""" to null),
        """'e;pow{fn:ln{'3;}}""" to ("""3""" to null),
        """'e;pow{'i;'π;}""" to ("""-1""" to null),
        """'x;pow{'2;}'x;pow{'3;}""" to ("""x^{5}""" to null),
        """fn:ln{'e;pow{'3;}}""" to ("""3""" to null),
        """fn:log{'2;|'1;'0;'2;'4;}""" to ("""10""" to null),
        """fn:log{'1;'0;|'0;'.;'0;'0;'1;}""" to ("""-3""" to null),
        """fn:ln{'−;'1;}""" to ("""\pi i""" to """3.141\,592\,654i"""),
        """fn:log{'3;|'8;'1;}""" to ("""4""" to null),
        """fn:sin{frac{'π;|'4;}}""" to ("""\frac{\sqrt{2}}{2}""" to """0.707\,106\,781\,2"""),
        """fn:cos{frac{'2;'π;|'3;}}""" to ("""-\frac{1}{2}""" to """-0.5"""),
        """fn:tan{frac{'π;|'3;}}""" to ("""\sqrt{3}""" to """1.732\,050\,808"""),
        """fn:sin{'3;'0;}|deg""" to ("""\frac{1}{2}""" to """0.5"""),
        """fn:cos{'1;'3;'5;}|deg""" to ("""-\frac{\sqrt{2}}{2}""" to """-0.707\,106\,781\,2"""),
        """fn:asin{frac{'1;|'2;}}""" to ("""\frac{\pi}{6}""" to """0.523\,598\,775\,6"""),
        """fn:acos{'0;}""" to ("""\frac{\pi}{2}""" to """1.570\,796\,327"""),
        """fn:atan{'1;}""" to ("""\frac{\pi}{4}""" to """0.785\,398\,163\,4"""),
        """fn:atan{sqrt{'3;}}|deg""" to ("""60""" to null),
        """fn:sinh{'0;}""" to ("""0""" to null),
        """fn:cosh{fn:ln{'2;}}""" to ("""\cosh\left(\ln\left(2\right)\right)""" to """1.25"""),
        """fn:tanh{fn:ln{'3;}}""" to ("""\tanh\left(\ln\left(3\right)\right)""" to """0.8"""),
        """fn:sin{'x;}pow{'2;}'+;fn:cos{'x;}pow{'2;}""" to ("""1""" to null),
        """'(;'2;'+;'3;'i;');'(;'1;'−;'i;');""" to ("""5+i""" to null),
        """frac{'1;|'1;'+;'i;}""" to ("""\frac{1}{2}-\frac{i}{2}""" to """0.5-0.5i"""),
        """'(;'1;'+;'i;');pow{'8;}""" to ("""16""" to null),
        """sqrt{'−;'1;'6;}""" to ("""4i""" to null),
        """'i;pow{'i;}""" to ("""e^{-\frac{\pi}{2}}""" to """0.207\,879\,576\,4"""),
        """fn:abs{'3;'+;'4;'i;}""" to ("""5""" to null),
        """fn:Re{'3;'+;'4;'i;}""" to ("""3""" to null),
        """fn:Im{'3;'+;'4;'i;}""" to ("""4""" to null),
        """fn:conj{'3;'+;'4;'i;}""" to ("""3-4i""" to null),
        """fn:arg{'1;'+;'i;}""" to ("""\frac{\pi}{4}""" to """0.785\,398\,163\,4"""),
        """'2;'e;pow{'i;frac{'π;|'3;}}""" to ("""1+i\sqrt{3}""" to """1+1.732\,050\,808i"""),
        """fn:solve{'2;'x;'+;'1;'=;'7;|'x;}""" to ("""x=3""" to null),
        """fn:solve{'x;pow{'2;}'−;'5;'x;'+;'6;'=;'0;|'x;}""" to ("""x=2,\,\,x=3""" to null),
        """fn:solve{'x;pow{'2;}'=;'2;|'x;}""" to ("""x=-\sqrt{2},\,\,x=\sqrt{2}""" to """x=-1.414\,213\,562,\,\,x=1.414\,213\,562"""),
        """fn:solve{'x;pow{'2;}'+;'1;'=;'0;|'x;}""" to ("""x=-i,\,\,x=i""" to null),
        """fn:solve{'x;pow{'3;}'=;'8;|'x;}""" to ("""x=2,\,\,x=-1-i\sqrt{3},\,\,x=-1+i\sqrt{3}""" to """x=2,\,\,x=-1-1.732\,050\,808i,\,\,x=-1+1.732\,050\,808i"""),
        """fn:solve{'2;pow{'x;'+;'1;}'=;'8;|'x;}""" to ("""x=2""" to null),
        """fn:solve{'a;'x;'+;'b;'=;'0;|'x;}""" to ("""x=-\frac{b}{a}""" to null),
        """fn:expand{'(;'x;'+;'1;');pow{'3;}}""" to ("""x^{3}+3x^{2}+3x+1""" to null),
        """fn:expand{'(;'a;'−;'b;');pow{'3;}}""" to ("""a^{3}-3a^{2}b+3ab^{2}-b^{3}""" to null),
        """fn:factor{'x;pow{'2;}'−;'1;}""" to ("""(x-1)(x+1)""" to null),
        """fn:factor{'x;pow{'3;}'−;'8;}""" to ("""(x-2)(x^{2}+2x+4)""" to null),
        """fn:simplify{frac{'x;pow{'2;}'−;'1;|'x;'−;'1;}}""" to ("""x+1""" to null),
        """fn:apart{frac{'1;|'x;pow{'2;}'−;'1;}}""" to ("""\frac{1}{2(x-1)}-\frac{1}{2(x+1)}""" to null),
        """fn:together{frac{'1;|'x;}'+;frac{'1;|'y;}}""" to ("""\frac{x+y}{xy}""" to null),
        """diff{'x;|fn:sin{'x;pow{'2;}}||}""" to ("""2x\cos\left(x^{2}\right)""" to null),
        """diff{'x;|'x;pow{'x;}||}""" to ("""x^{x}(\ln\left(x\right)+1)""" to null),
        """diff{'x;|fn:ln{'x;pow{'2;}'+;'1;}||}""" to ("""\frac{2x}{x^{2}+1}""" to null),
        """diff{'x;|'x;pow{'2;}fn:sin{'x;}||}""" to ("""x(x\cos\left(x\right)+2\sin\left(x\right))""" to null),
        """diff{'x;|'x;pow{'5;}||'3;}""" to ("""60x^{2}""" to null),
        """diff{'x;|'x;pow{'3;}|'2;|}""" to ("""12""" to null),
        """pdiff{'y;|'x;pow{'2;}'y;'+;'y;pow{'3;}||}""" to ("""x^{2}+3y^{2}""" to null),
        """int{||'x;pow{'2;}|'x;}""" to ("""\frac{x^{3}}{3}""" to null),
        """int{||'x;'e;pow{'x;}|'x;}""" to ("""xe^{x}-e^{x}""" to null),
        """int{||frac{'1;|'1;'+;'x;pow{'2;}}|'x;}""" to ("""\tan^{-1}\left(x\right)""" to null),
        """int{||fn:sin{'x;}pow{'2;}|'x;}""" to ("""\frac{-\cos\left(x\right)\sin\left(x\right)+x}{2}""" to null),
        """int{'0;|'1;|'x;pow{'2;}|'x;}""" to ("""\frac{1}{3}""" to """0.333\,333\,333\,3"""),
        """int{'0;|'∞;|'e;pow{'−;'x;}|'x;}""" to ("""1""" to null),
        """int{'−;'∞;|'∞;|'e;pow{'−;'x;pow{'2;}}|'x;}""" to ("""\sqrt{\pi}""" to """1.772\,453\,851"""),
        """int{'0;|'∞;|frac{fn:sin{'x;}|'x;}|'x;}""" to ("""\frac{\pi}{2}""" to """1.570\,796\,327"""),
        """int{||frac{fn:sin{'x;}|'x;}|'x;}""" to ("""\operatorname{Si}\left(x\right)""" to null),
        """fn:lim{frac{fn:sin{'x;}|'x;}|'x;'→;'0;}""" to ("""1""" to null),
        """fn:lim{'(;'1;'+;frac{'1;|'x;}');pow{'x;}|'x;'→;'∞;}""" to ("""e""" to """2.718\,281\,828"""),
        """fn:lim{frac{'x;'−;fn:sin{'x;}|'x;pow{'3;}}|'x;'→;'0;}""" to ("""\frac{1}{6}""" to """0.166\,666\,666\,7"""),
        """fn:lim{frac{'1;|'x;}|'x;'→;'0;pow{'+;}}""" to ("""\infty""" to null),
        """sum{'k;|'1;|'n;|'k;}""" to ("""\frac{n(n+1)}{2}""" to null),
        """sum{'k;|'1;|'n;|'k;pow{'2;}}""" to ("""\frac{n(n+1)(2n+1)}{6}""" to null),
        """sum{'n;|'1;|'∞;|frac{'1;|'n;pow{'2;}}}""" to ("""\frac{\pi ^{2}}{6}""" to """1.644\,934\,067"""),
        """sum{'n;|'0;|'∞;|frac{'1;|'n;'!;}}""" to ("""e""" to """2.718\,281\,828"""),
        """sum{'n;|'1;|'∞;|frac{'(;'−;'1;');pow{'n;'+;'1;}|'n;}}""" to ("""\ln\left(2\right)""" to """0.693\,147\,180\,6"""),
        """prod{'k;|'1;|'5;|'k;}""" to ("""120""" to null),
        """fn:taylor{fn:sin{'x;}|'x;'→;'0;|'7;}""" to ("""-\frac{x^{7}}{5040}+\frac{x^{5}}{120}-\frac{x^{3}}{6}+x""" to null),
        """fn:taylor{'e;pow{'x;}|'x;'→;'0;|'4;}""" to ("""\frac{x^{4}}{24}+\frac{x^{3}}{6}+\frac{x^{2}}{2}+x+1""" to null),
        """fn:dsolve{'y;'′;'=;'y;}""" to ("""y=C_{1}e^{x}""" to null),
        """fn:dsolve{'y;'′;'′;'+;'y;'=;'0;}""" to ("""y=C_{1}\cos\left(x\right)+C_{2}\sin\left(x\right)""" to null),
        """fn:dot{mat:3x1{'1;|'2;|'3;}|mat:3x1{'4;|'5;|'6;}}""" to ("""32""" to null),
        """fn:cross{mat:3x1{'1;|'0;|'0;}|mat:3x1{'0;|'1;|'0;}}""" to ("""\begin{bmatrix}0 \\ 0 \\ 1\end{bmatrix}""" to null),
        """fn:grad{'x;pow{'2;}'y;|}""" to ("""\begin{bmatrix}2xy \\ x^{2}\end{bmatrix}""" to null),
        """fn:div{mat:3x1{'x;pow{'2;}|'x;'y;|'z;}}""" to ("""3x+1""" to null),
        """fn:curl{mat:3x1{'−;'y;|'x;|'0;}}""" to ("""\begin{bmatrix}0 \\ 0 \\ 2\end{bmatrix}""" to null),
        """fn:laplacian{'x;pow{'2;}'+;'y;pow{'2;}}""" to ("""4""" to null),
        """fn:jacobian{mat:2x1{'x;'y;|'x;'+;'y;}}""" to ("""\begin{bmatrix}y & x \\ 1 & 1\end{bmatrix}""" to null),
        """fn:hessian{'x;pow{'3;}'+;'x;'y;}""" to ("""\begin{bmatrix}6x & 1 \\ 1 & 0\end{bmatrix}""" to null),
        """mat:2x2{'1;|'2;|'3;|'4;}mat:2x1{'5;|'6;}""" to ("""\begin{bmatrix}17 \\ 39\end{bmatrix}""" to null),
        """mat:2x2{'1;|'2;|'3;|'4;}pow{'−;'1;}""" to ("""\begin{bmatrix}-2 & 1 \\ \frac{3}{2} & -\frac{1}{2}\end{bmatrix}""" to """\begin{bmatrix}-2 & 1 \\ 1.5 & -0.5\end{bmatrix}"""),
        """mat:2x3{'1;|'2;|'3;|'4;|'5;|'6;}pow{'T;}""" to ("""\begin{bmatrix}1 & 4 \\ 2 & 5 \\ 3 & 6\end{bmatrix}""" to null),
        """fn:det{mat:2x2{'1;|'2;|'3;|'4;}}""" to ("""-2""" to null),
        """fn:det{mat:3x3{'2;|'0;|'1;|'1;|'3;|'2;|'1;|'1;|'1;}}""" to ("""0""" to null),
        """fn:trace{mat:2x2{'1;|'2;|'3;|'4;}}""" to ("""5""" to null),
        """fn:eigvals{mat:2x2{'2;|'1;|'1;|'2;}}""" to ("""\lambda =1,\,\,\lambda =3""" to null),
        """fn:eigvecs{mat:2x2{'2;|'1;|'1;|'2;}}""" to ("""\lambda =1,\,\,v=\begin{bmatrix}-1 \\ 1\end{bmatrix},\,\,\lambda =3,\,\,v=\begin{bmatrix}1 \\ 1\end{bmatrix}""" to null),
        """fn:charpoly{mat:2x2{'1;|'2;|'3;|'4;}}""" to ("""\lambda ^{2}-5\lambda -2""" to null),
        """fn:rref{mat:2x3{'1;|'2;|'3;|'4;|'5;|'6;}}""" to ("""\begin{bmatrix}1 & 0 & -1 \\ 0 & 1 & 2\end{bmatrix}""" to null),
        """fn:rank{mat:2x2{'1;|'2;|'2;|'4;}}""" to ("""1""" to null),
        """fn:hadamard{mat:2x2{'1;|'2;|'3;|'4;}|mat:2x2{'5;|'6;|'7;|'8;}}""" to ("""\begin{bmatrix}5 & 12 \\ 21 & 32\end{bmatrix}""" to null),
        """fn:kron{mat:2x1{'1;|'2;}|mat:1x2{'3;|'4;}}""" to ("""\begin{bmatrix}3 & 4 \\ 6 & 8\end{bmatrix}""" to null),
        """fn:mean{'1;',;'2;',;'3;',;'4;}""" to ("""\frac{5}{2}""" to """2.5"""),
        """fn:median{'3;',;'1;',;'4;',;'1;',;'5;}""" to ("""3""" to null),
        """fn:sd{'2;',;'4;',;'4;',;'4;',;'5;',;'5;',;'7;',;'9;}""" to ("""\frac{4\sqrt{14}}{7}""" to """2.138\,089\,935"""),
        """fn:psd{'2;',;'4;',;'4;',;'4;',;'5;',;'5;',;'7;',;'9;}""" to ("""2""" to null),
        """fn:var{'1;',;'2;',;'3;',;'4;}""" to ("""\frac{5}{3}""" to """1.666\,666\,667"""),
        """fn:total{'1;',;'2;',;'3;',;'4;}""" to ("""10""" to null),
        """fn:binompdf{'1;'0;|'0;'.;'5;|'3;}""" to ("""\frac{15}{128}""" to """0.117\,187\,5"""),
        """fn:binomcdf{'1;'0;|'0;'.;'5;|'3;}""" to ("""\frac{11}{64}""" to """0.171\,875"""),
        """fn:poissonpdf{'2;|'3;}""" to ("""\frac{4}{3e^{2}}""" to """0.180\,447\,044\,3"""),
        """fn:normcdf{'1;'.;'9;'6;|'0;|'1;}""" to ("""\frac{1+\operatorname{erf}\left(\frac{49\sqrt{2}}{50}\right)}{2}""" to """0.975\,002\,104\,9"""),
        """fn:normpdf{'0;|'0;|'1;}""" to ("""\frac{\sqrt{2}}{2\sqrt{\pi}}""" to """0.398\,942\,280\,4"""),
        """fn:invnorm{'0;'.;'9;'7;'5;}""" to ("""1.959\,963\,985""" to null),
        """fn:gamma{'5;}""" to ("""24""" to null),
        """fn:gamma{frac{'1;|'2;}}""" to ("""\sqrt{\pi}""" to """1.772\,453\,851"""),
        """fn:zeta{'2;}""" to ("""\frac{\pi ^{2}}{6}""" to """1.644\,934\,067"""),
        """fn:zeta{'4;}""" to ("""\frac{\pi ^{4}}{90}""" to """1.082\,323\,234"""),
        """fn:besselj{'0;|'0;}""" to ("""1""" to null),
        """fn:lambertw{'0;}""" to ("""0""" to null),
        """fn:lambertw{'e;}""" to ("""1""" to null),
        """int{||frac{'e;pow{'x;}|'x;}|'x;}""" to ("""\operatorname{Ei}\left(x\right)""" to null),
        """int{||'e;pow{'−;'x;pow{'2;}}|'x;}""" to ("""\frac{\operatorname{erf}\left(x\right)\sqrt{\pi}}{2}""" to null),
        """int{||frac{'1;|fn:ln{'x;}}|'x;}""" to ("""\operatorname{li}\left(x\right)""" to null),
        """int{||fn:sin{'x;pow{'2;}}|'x;}""" to ("""\frac{\sqrt{2}S\left(\frac{\sqrt{2}x}{\sqrt{\pi}}\right)\sqrt{\pi}}{2}""" to null),
        """fn:residue{frac{'1;|'z;}|'z;'=;'0;}""" to ("""1""" to null),
        """fn:residue{frac{'e;pow{'z;}|'z;pow{'2;}}|'z;'=;'0;}""" to ("""1""" to null),
        """fn:contour{frac{'1;|'z;}|fn:abs{'z;}'=;'1;}""" to ("""2\pi i""" to """6.283\,185\,307i"""),
        """fn:contour{frac{'1;|'z;pow{'2;}'+;'1;}|fn:abs{'z;}'=;'2;}""" to ("""0""" to null),
    )

    fun of(e: Docs.Example): Pair<String, String?>? = answers[com.example.cas.editor.MathCodec.encode(e.row) + if (e.degrees) "|deg" else ""]
}
