package com.example.cas.ui

import com.example.cas.editor.BigOp
import com.example.cas.editor.BigOpKind
import com.example.cas.editor.Binom
import com.example.cas.editor.Derivative
import com.example.cas.editor.Frac
import com.example.cas.editor.Func
import com.example.cas.editor.Integral
import com.example.cas.editor.MathRow
import com.example.cas.editor.MathCodec
import com.example.cas.editor.Matrix
import com.example.cas.editor.Node
import com.example.cas.editor.Pow
import com.example.cas.editor.Root
import com.example.cas.editor.Sqrt
import com.example.cas.editor.Sym

/**
 * What each key's long-press card says, beyond its title and formula: what it is, how to use it
 * step by step, and worked examples. An example is the row exactly as the keys would type it; the
 * card works out its answer with the calculator itself (so it's always what you'd get), and Try it
 * types it in. Math in the text is LaTeX between \( and \).
 */
object KeyGuides {
    class Example(val row: MathRow, val note: String = "", val degrees: Boolean = false)
    class Guide(val about: String, val steps: List<String>, val examples: List<Example>)

    // ---------- building rows as the keys type them (as in [Docs]) ----------

    private fun m(vararg parts: Any): MathRow = MathRow(
        parts.flatMap { p ->
            when (p) {
                is String -> p.map { Sym(it.toString()) }
                is Node -> listOf(p)
                is MathRow -> p.items
                else -> error("not math: $p")
            }
        }.toMutableList(),
    )
    private fun f(name: String, vararg args: Any) = Func(name, args.map { if (it is MathRow) it else m(it) })
    private fun fr(num: Any, den: Any) = Frac(m(num), m(den))
    private fun p(vararg e: Any) = Pow(m(*e))
    private fun sq(x: Any) = Sqrt(m(x))
    private fun rt(n: Any, x: Any) = Root(m(n), m(x))
    private fun int(body: Any, v: String = "x", lo: Any? = null, hi: Any? = null) = Integral(lo?.let { m(it) } ?: MathRow(), hi?.let { m(it) } ?: MathRow(), m(body), m(v))
    private fun d(body: Any, v: String = "x", partial: Boolean = false) = Derivative(m(v), m(body), MathRow(), MathRow(), partial)
    private fun sum(v: String, lo: Any, hi: Any, body: Any) = BigOp(BigOpKind.Sum, m(v), m(lo), m(hi), m(body))
    private fun prod(v: String, lo: Any, hi: Any, body: Any) = BigOp(BigOpKind.Product, m(v), m(lo), m(hi), m(body))
    private fun lim(body: Any, to: Any) = Func("lim", listOf(m(body), m(to)))
    private fun mat(rows: Int, cols: Int, vararg cells: Any) = Matrix(rows, cols, cells.map { m(it) })
    private fun bin(n: Any, k: Any) = Binom(m(n), m(k))
    private fun w(word: String) = Sym(word)

    private fun ex(vararg parts: Any, note: String = "", degrees: Boolean = false) = Example(m(*parts), note, degrees)
    private fun g(about: String, steps: List<String>, vararg examples: Example) = Guide(about, steps, examples.toList())
    private fun s(vararg t: String) = t.toList()

    /** The trigonometry tab's second page, and the statistics tab's, as the first step for their keys. */
    private const val RECIPROCAL = "On the trigonometry tab, tap the 1/△ switch beside Rad/Deg."
    private const val DISTRIBUTIONS = "On the statistics tab, tap the pdf/cdf switch beside Rad/Deg."
    private const val SIGNALS = "In a graph, tap the signals button left of the letters above the keypad."

    val all: Map<String, Guide> = mapOf(
        // ---- Basic
        "pi" to g("""The ratio of a circle's circumference to its diameter, \(\pi \approx 3.14159\). It stays exact in answers: \(\sin\frac{\pi}{6} = \frac{1}{2}\).""",
            s("Tap it wherever the number goes.", """Tap \(\approx\) on an answer for its decimal."""),
            ex(f("sin", fr("π", "6")), note = """Exact at multiples of \(\frac{\pi}{6}\) and \(\frac{\pi}{4}\)."""), ex("2π", "×", "3"), ex(int(f("sin", "x"), lo = "0", hi = "π"))),
        "e" to g("""Euler's number, \(e \approx 2.71828\): the base of natural logarithms, with \(\frac{d}{dx} e^x = e^x\).""",
            s("""Tap e, then the power key for \(e^x\).""", """It stays exact: \(\ln e^3 = 3\)."""),
            ex(f("ln", m("e", p("3")))), ex(d(m("e", p("2x")))), ex(lim(m("(1+", fr("1", "n"), ")", p("n")), "n→∞"), note = """The limit that defines \(e\).""")),
        "power" to g("""Raises what's before the cursor to a power: \(x^n\). The exponent can be any expression, fractions included.""",
            s("Type the base.", "Tap the power key and type the exponent.", """Tap \(\rightarrow\) to come back down."""),
            ex("2", p("10")), ex("8", p(fr("2", "3")), note = """\(8^{2/3} = (\sqrt[3]{8})^2\)."""), ex("(x+1)", p("2"), "−x", p("2"))),
        "nth root" to g("""The \(n\)-th root, \(\sqrt[n]{x} = x^{1/n}\). Odd roots of negative numbers are real: \(\sqrt[3]{-8} = -2\).""",
            s("""Type \(n\) in the small box.""", """Tap \(\rightarrow\), then type the number under the root."""),
            ex(rt("3", "27")), ex(rt("3", "−8")), ex(rt("4", "48"), note = "Simplified, kept exact.")),
        "factorial" to g("""\(n! = 1 \cdot 2 \cdots n\), the number of orders of \(n\) things; \(0! = 1\). Other numbers use \(\Gamma\): \(x! = \Gamma(x + 1)\).""",
            s("Type the number (or a bracket).", "Tap n! after it."),
            ex("5!"), ex("20!", note = "Exact, however long."), ex(fr("10!", "8!"))),
        "natural log" to g("""The logarithm to base \(e\): \(\ln x = y\) when \(e^y = x\). Of a negative number it's complex: \(\ln(-1) = \pi i\).""",
            s("Tap ln, then type what's inside the brackets."),
            ex(f("ln", m("e", p("2")))), ex(f("ln", "8"), note = """Simplified to \(3 \ln 2\)."""), ex(d(f("ln", "x")))),
        "log base a" to g("""The logarithm to base \(a\): \(\log_a x = \frac{\ln x}{\ln a}\), the power of \(a\) that gives \(x\).""",
            s("Type the base in the small box.", """Tap \(\rightarrow\) and type the number."""),
            ex(f("log", "2", "8")), ex(f("log", "10", "1000")), ex(f("log", "3", "5"), note = "Kept exact; tap ≈ for the decimal.")),
        "absolute value" to g("""The size of a number without its sign: \(|-7| = 7\). For a complex number it's the distance from 0: \(|3 + 4i| = 5\).""",
            s("Tap it, then type inside the bars."),
            ex(f("abs", "−7")), ex(f("abs", "3+4i")), ex(int(f("abs", "x"), lo = "−1", hi = "1"))),
        "mod" to g("""The remainder after dividing: \(a \bmod b = a - b\lfloor a/b \rfloor\). It takes the sign of \(b\): \(-7 \bmod 3 = 2\).""",
            s("Type the first number.", "Tap mod, then type the second."),
            ex("17", w("mod"), "5"), ex("−7", w("mod"), "3"), ex("2", p("100"), w("mod"), "7")),
        "i, the imaginary unit" to g("""The number with \(i^2 = -1\). Answers with \(i\) are written \(a + bi\) (or \(r e^{i\theta}\), in Settings).""",
            s("""Tap it like any number; next to a number it multiplies: \(2i\)."""),
            ex("i", p("2")), ex("(2+i)(3−i)"), ex(fr("1", "1+i"))),
        "equals sign" to g("""Makes an equation; \(\operatorname{solve}(x^2 = 9, x)\) solves it for \(x\). In the graphs, \(y = \ldots\) or an equation in \(x\) and \(y\) is drawn.""",
            s("Type the left side.", "Tap =, then type the right side.", """To solve it, put it in \(\operatorname{solve}(\square, x)\): tap Try it on an example."""),
            ex(f("solve", m("x", p("2"), "=9"), "x")), ex(f("solve", "2x+3=11", "x")), ex(f("solve", m("x", p("3"), "=x"), "x"))),
        "less than" to g("""Makes an inequality; \(\operatorname{solve}\) solves it for its letter. In the graphs, an inequality shades its region.""",
            s("Type the left side, tap <, type the right side.", """Tap > then = for \(\ge\) (or < then = for \(\le\))."""),
            ex(f("solve", "2x+1<7", "x")), ex(f("solve", m("x", p("2"), "<4"), "x"))),
        "greater than" to g("""Makes an inequality; \(\operatorname{solve}\) solves it for its letter: \(x^2 > 4\) holds for \(x < -2\) or \(x > 2\).""",
            s("Type the left side, tap >, type the right side."),
            ex(f("solve", m("x", p("2"), ">4"), "x")), ex(f("solve", "3x−5>1", "x"))),
        "comma" to g("""Separates the values of a list and the inputs of a function with several, such as \(\gcd(12, 18)\).""",
            s("Tap it between values."),
            ex(f("mean", "2,4,9")), ex(f("max", "3", "8"))),
        "previous answer" to g("""The last answer, so a result can be used in the next step. An operator pressed right after = starts from it too.""",
            s("Tap Ans where the last answer should go.", """Or tap \(+\), \(\times\)… right after = to carry on from it."""),
        ),
        // ---- Trigonometry
        "sin" to g("""In a right triangle, the opposite side over the hypotenuse; on the unit circle, the height of the point at angle \(\theta\). Exact at multiples of \(30°\) and \(45°\).""",
            s("Rad/Deg above the keys sets the angle unit.", "Tap sin, then type the angle."),
            ex(f("sin", fr("π", "6"))), ex(f("sin", "30"), note = "In degrees.", degrees = true), ex(d(f("sin", "x")))),
        "inverse sin" to g("""The angle whose sine is \(x\), between \(-\frac{\pi}{2}\) and \(\frac{\pi}{2}\). Real for \(-1 \le x \le 1\), complex outside.""",
            s("Tap it, then type the sine."),
            ex(f("asin", fr("1", "2"))), ex(f("asin", "1"), note = "In degrees.", degrees = true), ex(d(f("asin", "x")))),
        "hyperbolic sin" to g("""\(\sinh x = \frac{e^x - e^{-x}}{2}\): with \(\cosh\), the coordinates of a point on the hyperbola \(x^2 - y^2 = 1\).""",
            s("Tap it, then type the number."),
            ex(f("sinh", "0")), ex(f("sinh", f("ln", "2"))), ex(d(f("sinh", "x")))),
        "inverse hyperbolic sin" to g("""The inverse of \(\sinh\): \(\operatorname{asinh} x = \ln\left(x + \sqrt{x^2 + 1}\right)\), for every real \(x\).""",
            s("Tap it, then type the number."),
            ex(f("asinh", "0")), ex(f("asinh", fr("3", "4"))), ex(d(f("asinh", "x")))),
        "cos" to g("""In a right triangle, the adjacent side over the hypotenuse; on the unit circle, the \(x\) of the point at angle \(\theta\).""",
            s("Rad/Deg above the keys sets the angle unit.", "Tap cos, then type the angle."),
            ex(f("cos", fr("π", "3"))), ex(f("cos", "60"), note = "In degrees.", degrees = true), ex(int(f("cos", "x")))),
        "inverse cos" to g("""The angle whose cosine is \(x\), between \(0\) and \(\pi\). Real for \(-1 \le x \le 1\).""",
            s("Tap it, then type the cosine."),
            ex(f("acos", "0")), ex(f("acos", fr("−1", "2")), note = "In degrees.", degrees = true)),
        "hyperbolic cos" to g("""\(\cosh x = \frac{e^x + e^{-x}}{2}\): the shape of a hanging chain, \(y = \cosh x\).""",
            s("Tap it, then type the number."),
            ex(f("cosh", "0")), ex(f("cosh", "x"), p("2"), "−", f("sinh", "x"), p("2"), note = "Always 1.")),
        "inverse hyperbolic cos" to g("""The inverse of \(\cosh\) for \(x \ge 1\): \(\operatorname{acosh} x = \ln\left(x + \sqrt{x^2 - 1}\right)\).""",
            s("Tap it, then type the number."),
            ex(f("acosh", "1")), ex(f("acosh", fr("5", "4")))),
        "tan" to g("""\(\tan\theta = \frac{\sin\theta}{\cos\theta}\): the slope of a line at angle \(\theta\). Undefined at \(\frac{\pi}{2}\) and every half-turn from it.""",
            s("Rad/Deg above the keys sets the angle unit.", "Tap tan, then type the angle."),
            ex(f("tan", fr("π", "4"))), ex(f("tan", "60"), note = "In degrees.", degrees = true), ex(d(f("tan", "x")))),
        "inverse tan" to g("""The angle whose tangent is \(x\), between \(-\frac{\pi}{2}\) and \(\frac{\pi}{2}\); defined for every \(x\).""",
            s("Tap it, then type the tangent."),
            ex(f("atan", "1")), ex(int(fr("1", m("1+x", p("2"))))), ex(lim(f("atan", "x"), "x→∞"))),
        "hyperbolic tan" to g("""\(\tanh x = \frac{\sinh x}{\cosh x}\), an S-curve from \(-1\) to \(1\).""",
            s("Tap it, then type the number."),
            ex(f("tanh", "0")), ex(lim(f("tanh", "x"), "x→∞"))),
        "inverse hyperbolic tan" to g("""\(\operatorname{atanh} x = \frac{1}{2}\ln\frac{1 + x}{1 - x}\), for \(|x| < 1\).""",
            s("Tap it, then type the number."),
            ex(f("atanh", "0")), ex(f("atanh", fr("1", "2")))),
        // ---- Reciprocal trigonometry (the trigonometry tab's second page)
        "cosecant" to g("""One over the sine: \(\csc x = \frac{1}{\sin x}\). Undefined where \(\sin x = 0\).""",
            s(RECIPROCAL, "Tap csc, then type the angle."),
            ex(f("csc", fr("π", "6"))), ex(f("csc", "30"), note = "In degrees.", degrees = true), ex(d(f("csc", "x")))),
        "inverse cosecant" to g("""The angle whose cosecant is \(x\): \(\operatorname{acsc} x = \arcsin\frac{1}{x}\), for \(|x| \ge 1\).""",
            s(RECIPROCAL, "Tap acsc, then type the number."),
            ex(f("acsc", "2")), ex(f("acsc", "1"))),
        "hyperbolic cosecant" to g("""\(\operatorname{csch} x = \frac{1}{\sinh x}\), undefined at \(0\).""",
            s(RECIPROCAL, "Tap csch, then type the number."),
            ex(f("csch", f("ln", "2"))), ex(d(f("csch", "x")))),
        "inverse hyperbolic cosecant" to g("""The inverse of \(\operatorname{csch}\): \(\operatorname{acsch} x = \operatorname{asinh}\frac{1}{x}\).""",
            s(RECIPROCAL, "Tap acsch, then type the number."),
            ex(f("acsch", "1"))),
        "secant" to g("""One over the cosine: \(\sec x = \frac{1}{\cos x}\). Undefined where \(\cos x = 0\).""",
            s(RECIPROCAL, "Tap sec, then type the angle."),
            ex(f("sec", fr("π", "3"))), ex(f("sec", "60"), note = "In degrees.", degrees = true), ex(int(f("sec", "x")), note = "Long-press enter for the steps.")),
        "inverse secant" to g("""The angle whose secant is \(x\): \(\operatorname{asec} x = \arccos\frac{1}{x}\), for \(|x| \ge 1\).""",
            s(RECIPROCAL, "Tap asec, then type the number."),
            ex(f("asec", "2")), ex(f("asec", "−1"))),
        "hyperbolic secant" to g("""\(\operatorname{sech} x = \frac{1}{\cosh x}\): a bell-shaped curve, the shape of a soliton.""",
            s(RECIPROCAL, "Tap sech, then type the number."),
            ex(f("sech", "0")), ex(int(f("sech", "x"), lo = "−∞", hi = "∞"))),
        "inverse hyperbolic secant" to g("""The inverse of \(\operatorname{sech}\), for \(0 < x \le 1\).""",
            s(RECIPROCAL, "Tap asech, then type the number."),
            ex(f("asech", "1")), ex(f("asech", fr("4", "5")))),
        "cotangent" to g("""One over the tangent: \(\cot x = \frac{\cos x}{\sin x}\).""",
            s(RECIPROCAL, "Tap cot, then type the angle."),
            ex(f("cot", fr("π", "4"))), ex(d(f("cot", "x")))),
        "inverse cotangent" to g("""The angle whose cotangent is \(x\): \(\operatorname{acot} x = \arctan\frac{1}{x}\).""",
            s(RECIPROCAL, "Tap acot, then type the number."),
            ex(f("acot", "1"))),
        "hyperbolic cotangent" to g("""\(\operatorname{coth} x = \frac{\cosh x}{\sinh x}\), undefined at \(0\); it tends to \(\pm 1\).""",
            s(RECIPROCAL, "Tap coth, then type the number."),
            ex(f("coth", f("ln", "2"))), ex(lim(f("coth", "x"), "x→∞"))),
        "inverse hyperbolic cotangent" to g("""\(\operatorname{acoth} x = \frac{1}{2}\ln\frac{x + 1}{x - 1}\), for \(|x| > 1\).""",
            s(RECIPROCAL, "Tap acoth, then type the number."),
            ex(f("acoth", "2"))),
        // ---- Calculus
        "partial derivative" to g("""The derivative in one variable with the others held fixed: \(\frac{\partial}{\partial y}(x^2 y) = x^2\).""",
            s("Tap it and type the function.", """Tap the \(x\) in \(\partial x\) to change the variable."""),
            ex(d(m("x", p("2"), "y"), v = "y", partial = true)), ex(d(m(f("sin", "xy")), v = "x", partial = true))),
        "integral" to g("""The area under \(f\) from \(a\) to \(b\), \(\int_a^b f(x)\,dx = F(b) - F(a)\) with \(F' = f\). Left empty, the limits give an antiderivative \(F(x) + C\).""",
            s("Tap it and type the function.", "Fill the limits, or leave them empty.", """\(\infty\) works as a limit; long-press enter for the steps."""),
            ex(int(m("x", p("2")), lo = "0", hi = "1")), ex(int(m("x", "e", p("x")))), ex(int(m("e", p("−x", p("2"))), lo = "−∞", hi = "∞"))),
        "limit" to g("""What \(f(x)\) approaches as \(x\) approaches \(a\): \(\lim_{x \to 0} \frac{\sin x}{x} = 1\).""",
            s("Tap it and type the expression.", """Change \(x \to 0\) underneath; \(\infty\) is allowed."""),
            ex(lim(fr(f("sin", "x"), "x"), "x→0")), ex(lim(m("(1+", fr("1", "n"), ")", p("n")), "n→∞")), ex(lim(fr("1", "x"), m("x→0", p("+"))), note = "From the right.")),
        "sum" to g("""\(\sum_{k=a}^{b} f(k)\): the terms for \(k = a, a + 1, \ldots, b\) added up; \(b\) may be \(\infty\).""",
            s("Fill the variable and its start below, the end above.", "Type the term."),
            ex(sum("k", "1", "100", "k")), ex(sum("n", "1", "∞", fr("1", m("n", p("2"))))), ex(sum("k", "0", "n", m("2", p("k"))))),
        "product" to g("""\(\prod_{k=a}^{b} f(k)\): the terms multiplied together.""",
            s("Fill the variable and its start below, the end above.", "Type the factor."),
            ex(prod("k", "1", "5", "k")), ex(prod("k", "1", "4", m("1+", fr("1", "k"))), note = "It telescopes to 5.")),
        "Taylor series" to g("""The polynomial that matches \(f\) and its first \(N\) derivatives at \(a\): \(\sum_{n=0}^{N} \frac{f^{(n)}(a)}{n!}(x - a)^n\).""",
            s("Type the function.", "Set the point after the arrow and the order."),
            ex(f("taylor", m("e", p("x")), "x→0", "3")), ex(f("taylor", f("sin", "x"), "x→0", "5"))),
        "y prime" to g("""\(y'\), the derivative of \(y\), for writing differential equations.""",
            s("Use it inside the solve key for differential equations."),
            ex(f("dsolve", m("y", "′", "=y"))), ex(f("dsolve", m("y", "′", "=2x")))),
        "y double prime" to g("""\(y''\), the second derivative of \(y\).""",
            s("Use it inside the solve key."),
            ex(f("dsolve", m("y", "′", "′", "+y=0")))),
        "solve differential equation" to g("""Solves differential equations: first-order linear and separable ones, and second-order ones with constant coefficients. Without conditions the answer has constants \(C_1, C_2\).""",
            s("Type the equation in the box.", """Add conditions after commas, like \(y(0) = 1\)."""),
            ex(f("dsolve", m("y", "′", "=2y,y(0)=1"))), ex(f("dsolve", m("y", "′", "′", "+y=0")))),
        "infinity" to g("""\(\infty\), for limits, sums and integrals that go on without end.""",
            s("Tap it in a limit or bound."),
            ex(int(m("e", p("−x")), lo = "0", hi = "∞")), ex(lim(fr("1", "x"), "x→∞"))),
        "gradient" to g("""\(\nabla f\), the vector of partial derivatives: it points the way \(f\) grows fastest. With 2 in the small box it's the Laplacian \(\nabla^2 f\).""",
            s("Tap it and type the function.", "The switch above the keys picks Cartesian, cylindrical or spherical coordinates."),
            ex(f("grad", m("x", p("2"), "+y", p("2")), MathRow())), ex(f("grad", m("x", p("2"), "y"), m("2")))),
        "divergence" to g("""\(\nabla \cdot F = \frac{\partial P}{\partial x} + \frac{\partial Q}{\partial y} + \frac{\partial R}{\partial z}\): how much a field flows out of a point.""",
            s("Tap it and type the field as a vector."),
            ex(f("div", mat(3, 1, "x", "y", "z")))),
        "curl" to g("""\(\nabla \times F\): how much a field turns around a point.""",
            s("Tap it and type the field as a 3-vector."),
            ex(f("curl", mat(3, 1, "−y", "x", "0")))),
        "Jacobian matrix" to g("""The matrix of every first partial derivative of a vector function.""",
            s("Tap it and type the function as a vector."),
            ex(f("jacobian", mat(2, 1, "xy", "x+y")))),
        "Hessian matrix" to g("""The matrix of second partial derivatives of \(f\): its curvature in each direction.""",
            s("Tap it and type the function."),
            ex(f("hessian", m("x", p("2"), "y")))),
        // ---- Linear algebra
        "matrix" to g("""A grid of numbers. It grows as you fill its last row or column.""",
            s("Tap it: a matrix appears.", "Fill the boxes; type in the last row or column to add more."),
            ex(mat(2, 2, "1", "2", "3", "4"), "+", mat(2, 2, "1", "0", "0", "1"))),
        "inverse" to g("""\(A^{-1}\) with \(A A^{-1} = I\); it exists when \(\det A \ne 0\).""",
            s("Type the matrix.", "Tap the key after it.", "Long-press enter for the row steps."),
            ex(mat(2, 2, "2", "1", "1", "1"), p("−1")), ex(mat(2, 2, "a", "b", "c", "d"), p("−1"))),
        "transpose" to g("""\(A^{\top}\): rows become columns.""",
            s("Type the matrix, then tap the key."),
            ex(mat(2, 3, "1", "2", "3", "4", "5", "6"), p("T"))),
        "conjugate transpose" to g("""\(A^{\mathrm{H}}\): transposed and every entry conjugated. For real matrices, the same as the transpose.""",
            s("Type the matrix, then tap the key."),
            ex(mat(2, 2, "1", "i", "2", "3−i"), p("H"))),
        "determinant" to g("""\(\det A\): how much \(A\) scales area or volume; \(0\) when it has no inverse.""",
            s("Tap det, then type or tap a matrix."),
            ex(f("det", mat(2, 2, "1", "2", "3", "4"))), ex(f("det", mat(2, 2, "a", "b", "c", "d")))),
        "dot product" to g("""\(u \cdot v = \sum u_i v_i = |u||v|\cos\theta\); \(0\) when they're at right angles.""",
            s("Type the two vectors in the boxes."),
            ex(f("dot", mat(3, 1, "1", "2", "3"), mat(3, 1, "4", "5", "6")))),
        "cross product" to g("""\(u \times v\): a vector at right angles to both 3-vectors, of length the area of their parallelogram.""",
            s("Type the two 3-vectors in the boxes."),
            ex(f("cross", mat(3, 1, "1", "0", "0"), mat(3, 1, "0", "1", "0")))),
        "Hadamard product" to g("""\(A \circ B\): entry by entry, for matrices of the same size.""",
            s("Type the two matrices in the boxes."),
            ex(f("hadamard", mat(1, 2, "1", "2"), mat(1, 2, "3", "4")))),
        "Kronecker product" to g("""\(A \otimes B\): each entry of \(A\) times the whole of \(B\); a \(2 \times 2\) with a \(2 \times 2\) gives \(4 \times 4\).""",
            s("Type the two matrices in the boxes."),
            ex(f("kron", mat(2, 2, "1", "0", "0", "1"), mat(2, 2, "1", "2", "3", "4")))),
        "trace" to g("""\(\operatorname{tr} A\): the diagonal added up, also the sum of the eigenvalues.""",
            s("Tap tr, then type a matrix."),
            ex(f("trace", mat(2, 2, "1", "2", "3", "4")))),
        "eigenvalues" to g("""The numbers \(\lambda\) with \(A v = \lambda v\) for some \(v \ne 0\): the roots of \(\det(A - \lambda I) = 0\).""",
            s("Tap it, then type a square matrix.", "Long-press enter for the steps."),
            ex(f("eigvals", mat(2, 2, "2", "1", "1", "2"))), ex(f("eigvals", mat(2, 2, "0", "−1", "1", "0")))),
        "eigenvectors" to g("""Each eigenvalue \(\lambda\) with a vector \(v\) it scales: \(A v = \lambda v\).""",
            s("Tap it, then type a square matrix."),
            ex(f("eigvecs", mat(2, 2, "2", "1", "1", "2")))),
        "characteristic polynomial" to g("""\(p(\lambda) = \det(\lambda I - A)\); its roots are the eigenvalues.""",
            s("Tap it, then type a square matrix."),
            ex(f("charpoly", mat(2, 2, "1", "2", "3", "4")))),
        "reduced row echelon form" to g("""The matrix row-reduced: leading 1s with zeros above and below. On an augmented matrix the last column is the solution.""",
            s("Tap rref, then type the matrix.", "Long-press enter for each row operation."),
            ex(f("rref", mat(2, 3, "1", "1", "3", "1", "−1", "1")), note = """Solves \(x + y = 3,\ x - y = 1\).""")),
        "rank" to g("""The number of independent rows (or columns).""",
            s("Tap rk, then type the matrix."),
            ex(f("rank", mat(2, 2, "1", "2", "2", "4"))), ex(f("rank", mat(2, 2, "1", "2", "3", "4")))),
        // ---- Statistics
        "mean" to g("""The average: \(\bar{x} = \frac{1}{n}\sum x_i\).""",
            s("Tap it, then type the values with commas."),
            ex(f("mean", "2,4,4,5")), ex(f("mean", "1,2,3,4,100"), note = "One large value pulls the mean up.")),
        "median" to g("""The middle value when sorted, or the mean of the two middle ones.""",
            s("Tap it, then type the values with commas."),
            ex(f("median", "3,1,7,5")), ex(f("median", "1,2,3,4,100"), note = "Unmoved by the large value.")),
        "sample standard deviation" to g("""How spread out a sample is: \(s = \sqrt{\frac{1}{n - 1}\sum (x_i - \bar{x})^2}\).""",
            s("Tap s, then type the values with commas."),
            ex(f("sd", "2,4,4,4,5,5,7,9"))),
        "population standard deviation" to g("""The spread of a whole population: \(\sigma = \sqrt{\frac{1}{n}\sum (x_i - \bar{x})^2}\).""",
            s("""Tap \(\sigma\), then type the values with commas."""),
            ex(f("psd", "2,4,4,4,5,5,7,9"))),
        "sample variance" to g("""The square of the sample standard deviation, \(s^2\).""",
            s("""Tap \(s^2\), then type the values with commas."""),
            ex(f("var", "1,2,3,4"))),
        "n choose k" to g("""The ways to choose \(k\) things from \(n\) when order doesn't matter, \(\binom{n}{k} = \frac{n!}{k!\,(n - k)!}\); also the coefficients of \((a + b)^n\).""",
            s("""Type \(n\) in the top box.""", """Tap \(\rightarrow\) and type \(k\) in the bottom box."""),
            ex(bin("5", "2"), note = "Pairs from 5 people."), ex(bin("10", "3"), note = "Three toppings from ten."), ex(bin("52", "5"), note = "Poker hands.")),
        "permutations" to g("""Ordered choices of \(k\) from \(n\): \(P(n, k) = \frac{n!}{(n - k)!}\).""",
            s("""Fill \(n\), then \(k\)."""),
            ex(f("perm", "5", "2")), ex(f("perm", "10", "3"), note = "Gold, silver, bronze among 10.")),
        "normal density" to g("""The bell curve \(\varphi(x; \mu, \sigma) = \frac{1}{\sigma\sqrt{2\pi}} e^{-(x - \mu)^2 / 2\sigma^2}\). It's a formula, so it graphs.""",
            s("""Fill \(x\); \(\mu = 0\) and \(\sigma = 1\) are filled in, change them as needed."""),
            ex(f("normpdf", "0", "0", "1")), ex(f("normpdf", "x", "0", "1"))),
        "normal distribution function" to g("""The probability \(P(X \le x)\) for a normal \(X\): \(\Phi(x) = \frac{1}{2}\left(1 + \operatorname{erf}\frac{x - \mu}{\sigma\sqrt{2}}\right)\).""",
            s("""Fill \(x\), \(\mu\) and \(\sigma\)."""),
            ex(f("normcdf", "1.96", "0", "1")), ex(f("normcdf", "0", "0", "1"))),
        "inverse normal" to g("""The value with probability \(p\) below it: \(\Phi(z) = p\).""",
            s("""Tap it and type \(p\)."""),
            ex(f("invnorm", "0.975")), ex(f("invnorm", fr("1", "2")))),
        "binomial probability" to g("""Exactly \(k\) successes in \(n\) tries at chance \(p\): \(\binom{n}{k} p^k (1 - p)^{n - k}\).""",
            s("""Fill \(n\), \(p\) and \(k\)."""),
            ex(f("binompdf", "10", "0.5", "5")), ex(f("binompdf", "4", fr("1", "6"), "1"), note = "One six in four rolls.")),
        "cumulative binomial probability" to g("""At most \(k\) successes in \(n\) tries: \(P(X \le k)\).""",
            s("""Fill \(n\), \(p\) and \(k\)."""),
            ex(f("binomcdf", "10", "0.5", "5"))),
        "Poisson probability" to g("""Exactly \(k\) events at average rate \(\lambda\): \(\frac{\lambda^k e^{-\lambda}}{k!}\).""",
            s("""Fill \(\lambda\) and \(k\)."""),
            ex(f("poissonpdf", "2", "0")), ex(f("poissonpdf", "3", "2"))),
        "sum of a list" to g("""All the values added up.""",
            s("Tap it, then type the values with commas."),
            ex(f("total", "1,2,3,4"))),
        "comma for lists" to g("""Separates the values in a list.""",
            s("Tap it between values."),
            ex(f("mean", "1,2,3"))),
        // ---- Distributions (the statistics tab's second page)
        "exponential density" to g("""Waiting times at a constant rate \(\lambda\): \(f(x) = \lambda e^{-\lambda x}\) for \(x \ge 0\).""",
            s(DISTRIBUTIONS, """Fill \(x\) and the rate \(\lambda\)."""),
            ex(f("exppdf", "1", "2")), ex(int(f("exppdf", "x", "2"), lo = "0", hi = "∞"), note = "A density's total is 1.")),
        "exponential distribution function" to g("""The chance of waiting at most \(x\): \(F(x) = 1 - e^{-\lambda x}\).""",
            s(DISTRIBUTIONS, """Fill \(x\) and \(\lambda\)."""),
            ex(f("expcdf", "1", "2"))),
        "uniform density" to g("""Every value between \(a\) and \(b\) equally likely: \(f(x) = \frac{1}{b - a}\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("unifpdf", "3", "1", "5"))),
        "uniform distribution function" to g("""\(F(x) = \frac{x - a}{b - a}\) between \(a\) and \(b\): from \(0\) up to \(1\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("unifcdf", "3", "1", "5"))),
        "cumulative Poisson probability" to g("""At most \(k\) events at rate \(\lambda\): \(P(X \le k) = e^{-\lambda}\sum_{i=0}^{k} \frac{\lambda^i}{i!}\).""",
            s(DISTRIBUTIONS, """Fill \(\lambda\) and \(k\)."""),
            ex(f("poissoncdf", "2", "3"))),
        "geometric probability" to g("""The first success on try \(k\): \(P(X = k) = (1 - p)^{k - 1} p\).""",
            s(DISTRIBUTIONS, """Fill \(p\) and \(k\)."""),
            ex(f("geompdf", fr("1", "6"), "3"), note = "The first six on the third roll.")),
        "cumulative geometric probability" to g("""A success within \(k\) tries: \(P(X \le k) = 1 - (1 - p)^k\).""",
            s(DISTRIBUTIONS, """Fill \(p\) and \(k\)."""),
            ex(f("geomcdf", fr("1", "6"), "3"), note = "A six within three rolls.")),
        "chi-squared density" to g("""The sum of \(k\) squared standard normals: \(f(x) = \frac{x^{k/2 - 1} e^{-x/2}}{2^{k/2}\Gamma(k/2)}\).""",
            s(DISTRIBUTIONS, """Fill \(x\) and the degrees of freedom \(k\)."""),
            ex(f("chi2pdf", "1", "3"))),
        "chi-squared distribution function" to g("""\(P(X \le x)\) for \(\chi^2\) with \(k\) degrees of freedom, for tests of fit and of variance.""",
            s(DISTRIBUTIONS, """Fill \(x\) and \(k\)."""),
            ex(f("chi2cdf", "7.815", "3"), note = "The 5% critical value for 3 degrees of freedom.")),
        "log-normal density" to g("""A variable whose logarithm is normal (sizes, incomes): \(f(x) = \frac{1}{x\sigma\sqrt{2\pi}} e^{-(\ln x - \mu)^2 / 2\sigma^2}\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(\mu\) and \(\sigma\)."""),
            ex(f("lognpdf", "1", "0", "1"))),
        "log-normal distribution function" to g("""\(F(x) = \Phi\left(\frac{\ln x - \mu}{\sigma}\right)\): half the values lie below \(e^{\mu}\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(\mu\) and \(\sigma\)."""),
            ex(f("logncdf", "1", "0", "1"))),
        "Cauchy density" to g("""A bell with tails so heavy it has no mean: \(f(x) = \frac{1}{\pi\gamma(1 + ((x - x_0)/\gamma)^2)}\).""",
            s(DISTRIBUTIONS, """Fill \(x\), the centre \(x_0\) and the width \(\gamma\)."""),
            ex(f("cauchypdf", "0", "0", "1"))),
        "Cauchy distribution function" to g("""\(F(x) = \frac{1}{2} + \frac{1}{\pi}\arctan\frac{x - x_0}{\gamma}\); the median is \(x_0\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(x_0\) and \(\gamma\)."""),
            ex(f("cauchycdf", "1", "0", "1"))),
        "Weibull density" to g("""Lifetimes and failure rates, shape \(k\) and scale \(\lambda\); \(k = 1\) is the exponential.""",
            s(DISTRIBUTIONS, """Fill \(x\), \(k\) and \(\lambda\)."""),
            ex(f("weibpdf", "1", "2", "1"))),
        "Weibull distribution function" to g("""The chance of failing by time \(x\): \(F(x) = 1 - e^{-(x/\lambda)^k}\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(k\) and \(\lambda\)."""),
            ex(f("weibcdf", "1", "2", "1"))),
        // ---- Complex numbers
        "real part" to g("""\(\Re(a + bi) = a\).""",
            s("Tap it, then type the number."),
            ex(f("Re", "3+4i")), ex(f("Re", m("e", p("i", fr("π", "3")))))),
        "imaginary part" to g("""\(\Im(a + bi) = b\).""",
            s("Tap it, then type the number."),
            ex(f("Im", "3+4i"))),
        "conjugate" to g("""\((a + bi)^* = a - bi\): the reflection in the real axis; \(z z^* = |z|^2\).""",
            s("Tap it, then type the number."),
            ex(f("conj", "3+4i")), ex("(3+4i)", f("conj", "3+4i"))),
        "argument" to g("""The angle of \(z\) from the positive real axis, \(-\pi < \arg z \le \pi\).""",
            s("Tap it, then type the number; Rad/Deg sets the unit."),
            ex(f("arg", "1+i")), ex(f("arg", "−1"), degrees = true, note = "In degrees.")),
        "e to the i theta" to g("""Euler's formula: \(e^{i\theta} = \cos\theta + i\sin\theta\), the point on the unit circle at angle \(\theta\).""",
            s("""Type the angle after \(i\) in the power."""),
            ex("e", p("iπ")), ex("e", p("i", fr("π", "2")))),
        "gamma function" to g("""Extends factorials: \(\Gamma(n) = (n - 1)!\), and \(\Gamma(\frac{1}{2}) = \sqrt{\pi}\). Defined everywhere but \(0, -1, -2, \ldots\)""",
            s("Tap it, then type the number."),
            ex(f("gamma", "5")), ex(f("gamma", fr("1", "2")))),
        "Riemann zeta function" to g("""\(\zeta(s) = \sum \frac{1}{n^s}\) for \(s > 1\), and beyond by continuation; exact at even whole numbers.""",
            s("""Tap it, then type \(s\)."""),
            ex(f("zeta", "2")), ex(f("zeta", "−1"))),
        "Lambert W function" to g("""The solution of \(W e^W = z\): it solves equations like \(x e^x = 2\).""",
            s("""Tap it, then type \(z\)."""),
            ex(f("lambertw", "1")), ex(f("lambertw", "e"))),
        "Bessel function of the first kind" to g("""\(J_a(x)\): solutions of Bessel's equation that stay finite at 0, the vibrations of a drum.""",
            s("""Type the order \(a\) in the small box, then the number."""),
            ex(f("besselj", "0", "0")), ex(f("besselj", "1", "2"))),
        "Bessel function of the second kind" to g("""\(Y_a(x)\): the second solution of Bessel's equation, infinite at 0.""",
            s("""Type the order \(a\) in the small box, then the number."""),
            ex(f("bessely", "0", "1"))),
        "contour integral" to g("""\(\oint f(z)\,dz\) around a circle, counterclockwise: \(2\pi i\) times the residues inside.""",
            s("Type the function.", """Change the circle underneath, \(|z| = 1\) to start with."""),
            ex(f("contour", fr("1", "z"), m(f("abs", "z"), "=1"))), ex(f("contour", fr(m("e", p("z")), m("z", p("2"))), m(f("abs", "z"), "=2")))),
        "residue" to g("""\(\operatorname{Res}_{z = a} f\): the coefficient of \(\frac{1}{z - a}\) in \(f\)'s expansion at \(a\).""",
            s("Type the function, then the point underneath."),
            ex(f("residue", fr(m("e", p("z")), m("z", p("2"))), "z=0"))),
        "z" to g("""The variable of the complex plane: plot \(f(z) = z^2\) there. In the calculator it's a letter like any other.""",
            s("Tap it wherever the variable goes."),
            ex(f("solve", m("z", p("2"), "+1=0"), "z"))),
        "w" to g("""A second complex letter, for \(w = f(z)\) or a parameter.""",
            s("Tap it like any letter."),
            ex("2w+3w")),
        // ---- Special functions
        "error function" to g("""\(\operatorname{erf}(x) = \frac{2}{\sqrt{\pi}}\int_0^x e^{-t^2}\,dt\), the normal distribution's integral; from \(-1\) to \(1\).""",
            s("Tap it, then type the number."),
            ex(f("erf", "1")), ex(int(m("e", p("−x", p("2"))))), ex(d(f("erf", "x")))),
        "imaginary error function" to g("""\(\operatorname{erfi}(x) = -i\operatorname{erf}(ix)\): antiderivatives of \(e^{x^2}\) come out in it.""",
            s("Tap it, then type the number."),
            ex(f("erfi", "1")), ex(int(m("e", p("x", p("2")))))),
        "upper incomplete gamma function" to g("""\(\Gamma(s, x) = \int_x^{\infty} t^{s-1} e^{-t}\,dt\); \(\Gamma(s, 0) = \Gamma(s)\).""",
            s("""Fill \(s\), then \(x\)."""),
            ex(f("gammainc", "1", "2")), ex(f("gammainc", "3", "0"))),
        "digamma function" to g("""\(\psi(x) = \frac{\Gamma'(x)}{\Gamma(x)}\), the derivative of \(\ln\Gamma\); \(\psi(1) = -\gamma\).""",
            s("Tap it, then type the number."),
            ex(f("digamma", "1"))),
        "Hurwitz zeta function" to g("""\(\zeta(s, a) = \sum_{n=0}^{\infty} \frac{1}{(n + a)^s}\); \(\zeta(s, 1) = \zeta(s)\).""",
            s("""Fill \(s\), then \(a\)."""),
            ex(f("hurwitz", "2", "1"))),
        "sine integral" to g("""\(\operatorname{Si}(x) = \int_0^x \frac{\sin t}{t}\,dt\), tending to \(\frac{\pi}{2}\).""",
            s("Tap it, then type the number."),
            ex(f("si", "1")), ex(int(fr(f("sin", "x"), "x"))), ex(lim(f("si", "x"), "x→∞"))),
        "cosine integral" to g("""\(\operatorname{Ci}(x) = \gamma + \ln x + \int_0^x \frac{\cos t - 1}{t}\,dt\).""",
            s("Tap it, then type the number."),
            ex(f("ci", "1")), ex(int(fr(f("cos", "x"), "x")))),
        "exponential integral" to g("""\(\operatorname{Ei}(x)\): antiderivatives of \(\frac{e^x}{x}\) come out in it.""",
            s("Tap it, then type the number."),
            ex(f("ei", "1")), ex(int(fr(m("e", p("x")), "x")))),
        "logarithmic integral" to g("""\(\operatorname{li}(x) = \int_0^x \frac{dt}{\ln t}\): close to the number of primes up to \(x\).""",
            s("Tap it, then type the number."),
            ex(f("li", "10")), ex(int(fr("1", f("ln", "x"))))),
        "polylogarithm" to g("""\(\operatorname{Li}_s(z) = \sum_{k=1}^{\infty} \frac{z^k}{k^s}\); \(\operatorname{Li}_1(z) = -\ln(1 - z)\).""",
            s("""Type the order \(s\) in the small box, then \(z\)."""),
            ex(f("polylog", "2", "1")), ex(f("polylog", "2", fr("1", "2")))),
        "hyperbolic sine integral" to g("""\(\operatorname{Shi}(x) = \int_0^x \frac{\sinh t}{t}\,dt\).""",
            s("Tap it, then type the number."),
            ex(f("shi", "1")), ex(int(fr(f("sinh", "x"), "x")))),
        "hyperbolic cosine integral" to g("""\(\operatorname{Chi}(x) = \gamma + \ln x + \int_0^x \frac{\cosh t - 1}{t}\,dt\).""",
            s("Tap it, then type the number."),
            ex(f("chi", "1"))),
        "Fresnel sine integral" to g("""\(S(x) = \int_0^x \sin\frac{\pi t^2}{2}\,dt\), tending to \(\frac{1}{2}\); with \(C\), it draws the Euler spiral.""",
            s("Tap it, then type the number."),
            ex(f("fresnels", "1")), ex(lim(f("fresnels", "x"), "x→∞"))),
        "Fresnel cosine integral" to g("""\(C(x) = \int_0^x \cos\frac{\pi t^2}{2}\,dt\), tending to \(\frac{1}{2}\).""",
            s("Tap it, then type the number."),
            ex(f("fresnelc", "1"))),
        "incomplete elliptic integral of the first kind" to g("""\(F(\varphi \mid m) = \int_0^{\varphi} \frac{d\theta}{\sqrt{1 - m\sin^2\theta}}\); a pendulum's period needs it.""",
            s("""Fill the angle \(\varphi\), then the parameter \(m\)."""),
            ex(f("ellipticf", "1", "0")), ex(f("ellipticf", fr("π", "2"), fr("1", "2")))),
        // ---- Combinatorics
        "Stirling number of the first kind" to g("""\(s(n, k)\): arrangements of \(n\) things into \(k\) cycles, with sign; \(x(x - 1)\cdots(x - n + 1) = \sum_k s(n, k) x^k\).""",
            s("""Tap it: \(s(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("stirling1", "4", "2")), ex(f("stirling1", "7", "5"))),
        "Stirling number of the second kind" to g("""\(S(n, k)\): the ways to split \(n\) things into \(k\) non-empty groups.""",
            s("""Tap it: \(S(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("stirling2", "4", "2"))),
        "Bell number" to g("""\(B(n)\): every way to split \(n\) things into groups, \(B(n) = \sum_k S(n, k)\): 1, 1, 2, 5, 15, 52, …""",
            s("""Tap it: \(B(\square)\).""", """Fill \(n\)."""),
            ex(f("bell", "5")), ex(f("bell", "10"))),
        "derangements" to g("""\(!n\): orders of \(n\) things with nothing in its own place; about \(\frac{n!}{e}\).""",
            s("""Tap it: \(!\square\).""", """Fill \(n\)."""),
            ex(f("subfactorial", "4"), note = "Four hats handed back, none to its owner."), ex(fr(f("subfactorial", "10"), "10!"))),
        "Narayana number" to g("""\(N(n, k) = \frac{1}{n}\binom{n}{k}\binom{n}{k - 1}\); summed over \(k\), the Catalan numbers.""",
            s("""Tap it: \(N(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("narayana", "5", "3"))),
        "Lah number" to g("""\(L(n, k) = \binom{n - 1}{k - 1}\frac{n!}{k!}\): the ways to split \(n\) things into \(k\) ordered lists.""",
            s("""Tap it: \(L(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("lah", "4", "2"))),
        "Eulerian number" to g("""\(A(n, k)\): the orders of \(1, \ldots, n\) with exactly \(k\) rises.""",
            s("""Tap it: \(A(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("eulerian", "5", "2"))),
        "rising factorial" to g("""\(x^{(n)} = x(x + 1)\cdots(x + n - 1)\), \(n\) factors climbing from \(x\).""",
            s("""Tap it: \(\square^{(\square)}\).""", """Fill \(x\), then \(n\) in the raised box."""),
            ex(f("rising", "2", "3")), ex(f("rising", "x", "3"))),
        "falling factorial" to g("""\((x)_n = x(x - 1)\cdots(x - n + 1)\): ordered choices of \(n\) from \(x\).""",
            s("""Tap it: \((\square)_{\square}\).""", """Fill \(x\), then \(n\) below."""),
            ex(f("falling", "6", "3")), ex(f("falling", "x", "2"))),
        "superfactorial" to g("""\(\operatorname{sf}(n) = 1!\,2!\cdots n!\), the product of the first \(n\) factorials.""",
            s("""Tap it: \(\operatorname{sf}(\square)\).""", """Fill \(n\)."""),
            ex(f("superfactorial", "5"))),
        "harmonic number" to g("""\(H_n = 1 + \frac{1}{2} + \cdots + \frac{1}{n}\), exact; \(H_n \approx \ln n + \gamma\).""",
            s("""Tap it: \(H_{\square}\).""", """Fill \(n\)."""),
            ex(f("harmonic", "5")), ex(sum("n", "1", "4", f("harmonic", "n")))),
        "triangular number" to g("""\(T_n = \frac{n(n + 1)}{2}\): dots in a triangle, 1, 3, 6, 10, …""",
            s("""Tap it: \(T_{\square}\).""", """Fill \(n\)."""),
            ex(f("triangular", "10"))),
        "Motzkin number" to g("""\(M_n\): the ways to draw non-crossing chords between \(n\) points on a circle; 1, 1, 2, 4, 9, 21, 51, …""",
            s("""Tap it: \(M_{\square}\).""", """Fill \(n\)."""),
            ex(f("motzkin", "6"))),
        "Pell number" to g("""\(P_n = 2P_{n-1} + P_{n-2}\) from \(P_0 = 0\), \(P_1 = 1\); \(\frac{P_{n+1}}{P_n} \to 1 + \sqrt{2}\).""",
            s("""Tap it: \(P_{\square}\).""", """Fill \(n\)."""),
            ex(f("pell", "6"))),
        "primorial" to g("""\(n\#\): the product of the primes up to \(n\).""",
            s("""Tap it: \(\square\#\).""", """Fill \(n\)."""),
            ex(f("primorial", "10"))),
        // ---- Polynomials
        "Legendre polynomial" to g("""\(P_n(x)\): polynomials orthogonal on \([-1, 1]\), for gravity and charge around a sphere.""",
            s("""Tap it: \(P_{\square}(\square)\).""", """Type the degree \(n\) in the small box, then \(x\) in the brackets."""),
            ex(f("legendre", "2", "x")), ex(f("legendre", "3", fr("1", "2"))), ex(int(m(f("legendre", "2", "x"), p("2")), lo = "−1", hi = "1"), note = """Its norm, \(\frac{2}{2n + 1}\).""")),
        "Hermite polynomial" to g("""\(H_n(x)\), the physicists' Hermite polynomials, orthogonal with weight \(e^{-x^2}\): the quantum oscillator's states.""",
            s("""Tap it: \(H_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("hermite", "2", "x")), ex(f("hermite", "3", "x"))),
        "probabilists' Hermite polynomial" to g("""\(He_n(x)\), orthogonal with weight \(e^{-x^2/2}\), the normal density's shape.""",
            s("""Tap it: \(He_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("hermitehe", "3", "x"))),
        "Laguerre polynomial" to g("""\(L_n(x)\), orthogonal for \(x \ge 0\) with weight \(e^{-x}\).""",
            s("""Tap it: \(L_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("laguerre", "2", "x"))),
        "generalized Laguerre polynomial" to g("""\(L_n^{\alpha}(x)\), weight \(x^{\alpha} e^{-x}\): the hydrogen atom's radial functions.""",
            s("""Tap it: \(L_{\square}^{\square}(\square)\).""", """Fill the degree below, \(\alpha\) above, then \(x\)."""),
            ex(f("genlaguerre", "1", "α", "x")), ex(f("genlaguerre", "2", "1", "x"))),
        "Chebyshev polynomial of the first kind" to g("""\(T_n(x)\) with \(T_n(\cos\theta) = \cos n\theta\): the best polynomials for approximating on \([-1, 1]\).""",
            s("""Tap it: \(T_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("chebyshevt", "3", "x")), ex(f("chebyshevt", "3", f("cos", "θ")))),
        "Chebyshev polynomial of the second kind" to g("""\(U_n(x)\) with \(U_n(\cos\theta) = \frac{\sin(n + 1)\theta}{\sin\theta}\).""",
            s("""Tap it: \(U_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("chebyshevu", "2", "x"))),
        "Gegenbauer polynomial" to g("""\(C_n^{\alpha}(x)\), weight \((1 - x^2)^{\alpha - 1/2}\); \(\alpha = \frac{1}{2}\) gives Legendre.""",
            s("""Tap it: \(C_{\square}^{\square}(\square)\).""", """Fill the degree below, \(\alpha\) above, then \(x\)."""),
            ex(f("gegenbauer", "1", "α", "x")), ex(f("gegenbauer", "2", fr("1", "2"), "x"))),
        "associated Legendre function" to g("""\(P_n^m(x) = (-1)^m (1 - x^2)^{m/2} \frac{d^m}{dx^m} P_n(x)\), in the spherical harmonics.""",
            s("""Tap it: \(P_{\square}^{\square}(\square)\).""", """Fill \(n\) below, \(m\) above, then \(x\)."""),
            ex(f("assoclegendre", "1", "1", "x")), ex(f("assoclegendre", "2", "1", fr("1", "2")))),
        "Bernoulli polynomial" to g("""\(B_n(x) = \sum_k \binom{n}{k} B_k x^{n-k}\); \(B_n(0)\) is the Bernoulli number.""",
            s("""Tap it: \(B_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("bernoullipoly", "2", "x")), ex(f("bernoullipoly", "3", "0"))),
        "Fibonacci polynomial" to g("""\(F_{n+1}(x) = x F_n(x) + F_{n-1}(x)\) from \(F_0 = 0\), \(F_1 = 1\); at \(x = 1\), the Fibonacci numbers.""",
            s("""Tap it: \(F_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("fibpoly", "4", "x")), ex(f("fibpoly", "10", "1"))),
        "Lucas polynomial" to g("""\(L_{n+1}(x) = x L_n(x) + L_{n-1}(x)\) from \(L_0 = 2\), \(L_1 = x\); at \(x = 1\), the Lucas numbers.""",
            s("""Tap it: \(L_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("lucaspoly", "3", "x"))),
        "Bessel polynomial" to g("""\(y_n(x)\), from \(y_0 = 1\), \(y_1 = x + 1\): in Bessel filters.""",
            s("""Tap it: \(y_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("besselpoly", "2", "x"))),
        "Touchard polynomial" to g("""\(T_n(x) = \sum_k S(n, k) x^k\); \(T_n(1)\) is the Bell number.""",
            s("""Tap it: \(T_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("touchard", "3", "x")), ex(f("touchard", "5", "1"))),
        "cyclotomic polynomial" to g("""\(\Phi_n(x)\): the product of \((x - \omega)\) over the primitive \(n\)-th roots of unity; whole-number coefficients.""",
            s("""Tap it: \(\Phi_{\square}(\square)\).""", """Fill \(n\), then \(x\)."""),
            ex(f("cyclotomic", "6", "x")), ex(f("cyclotomic", "12", "x"))),
        // ---- Signals (graphs only)
        "Heaviside step" to g("""\(H(x)\): \(0\) for \(x < 0\), \(1\) for \(x > 0\), switching on at \(0\).""",
            s(SIGNALS, """Graph \(y = H(x - 2)\) to switch on at \(2\)."""),
            ex(f("heaviside", "3")), ex(f("heaviside", "−1"))),
        "rectangle function" to g("""\(\operatorname{rect}(x)\): \(1\) for \(|x| < \frac{1}{2}\), \(0\) outside, a box of width 1.""",
            s(SIGNALS, """\(\operatorname{rect}(\frac{x}{4})\) is a box of width 4."""),
            ex(f("rect", "0.2")), ex(int(f("rect", "x"), lo = "−1", hi = "1"))),
        "triangle function" to g("""\(\operatorname{tri}(x) = \max(1 - |x|, 0)\): a peak of height 1 at 0.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("tri", fr("1", "2")))),
        "ramp function" to g("""\(\operatorname{ramp}(x) = \max(x, 0)\), also called ReLU.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("ramp", "3")), ex(f("ramp", "−3"))),
        "pulse" to g("""\(\operatorname{pulse}(x, a, b)\): \(1\) between \(a\) and \(b\), \(0\) elsewhere.""",
            s(SIGNALS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("pulse", "2", "1", "3"))),
        "sawtooth wave" to g("""\(\operatorname{saw}(x) = x - \lfloor x \rfloor\): rises from 0 to 1, then drops back, every unit.""",
            s(SIGNALS, """\(\operatorname{saw}(\frac{x}{T})\) has period \(T\)."""),
            ex(f("sawtooth", fr("9", "4")))),
        "square wave" to g("""\(\operatorname{sq}(x)\): \(+1\) for the first half of each period of 1, \(-1\) for the second.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("squarewave", "0.25"))),
        "triangle wave" to g("""\(\operatorname{tw}(x)\): zig-zags between \(-1\) and \(1\) with period 1.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("trianglewave", "0.5"))),
        "logistic sigmoid" to g("""\(\sigma(x) = \frac{1}{1 + e^{-x}}\): an S-curve from 0 to 1, for growth and neural networks.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("sigmoid", "0")), ex(d(f("sigmoid", "x")))),
        "softplus" to g("""\(\ln(1 + e^x)\): a smooth ramp whose derivative is the sigmoid.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("softplus", "0"))),
        "clamp" to g("""\(\operatorname{clamp}(x, a, b) = \min(\max(x, a), b)\): \(x\) kept between \(a\) and \(b\).""",
            s(SIGNALS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("clamp", "5", "−1", "1"))),
        "linear interpolation" to g("""\(\operatorname{lerp}(a, b, t) = a + (b - a)t\): \(a\) at \(t = 0\), \(b\) at \(t = 1\).""",
            s(SIGNALS, """Fill \(a\), \(b\) and \(t\)."""),
            ex(f("lerp", "0", "10", fr("1", "2")))),
        "smoothstep" to g("""\(3x^2 - 2x^3\) between 0 and 1: eases from 0 to 1, flat at both ends.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("smoothstep", fr("1", "2")))),
        "Gaussian" to g("""\(e^{-x^2}\), the bell curve with peak 1; normpdf is the normalized one.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("gauss", "0")), ex(int(f("gauss", "x"), lo = "−∞", hi = "∞"))),
        "wrap" to g("""\(x\) brought into the range from \(a\) to \(b\) by whole periods, as angles wrap around.""",
            s(SIGNALS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("wrap", fr("7", "2"), "0", "1"))),
        // ---- Symbols
        "symbol builder" to g("""Builds a symbol such as \(\hat{x}_1\) or \(\dot{\theta}^2\): it acts as one letter, and one backspace deletes it whole.""",
            s("Tap it and pick a letter, then an accent and scripts.", "Saved symbols appear at the top of this tab."),
        ),
        "saved symbol" to g("""A symbol you built: it acts as one letter, and one backspace deletes it whole.""",
            s("Tap it wherever the symbol goes.", "Long-press it to undefine or remove it."),
        ),
        "list of constants with names" to g("""Opens the list of physical constants, each with its value, unit and source.""",
            s("Tap it, then search by name or symbol.", "Tap a constant to put it in the line."),
        ),
        "store in variable" to g("""Gives a letter a value, used from then on; \(f(x) := x^2\) defines a function.""",
            s("Type the letter.", "Tap :=, then type the value."),
            ex("a", w(":="), "5"), ex("f(x)", w(":="), "x", p("2"), "+1")),
        // ---- Number pad
        "all clear" to g("""Clears the line. Undo brings it back.""", s("Tap AC, or long-press backspace.")),
        "brackets" to g("""Groups what goes together; the next tap closes the bracket.""",
            s("Tap once to open, again to close."),
            ex("2(3+4)"), ex("(x+1)(x−1)")),
        "divide" to g("""Makes a fraction: what's before the cursor goes on top.""",
            s("Type the top, tap it, then type the bottom.", """Tap \(\rightarrow\) to leave the fraction."""),
            ex(fr("1", "3"), "+", fr("1", "6")), ex(fr(fr("1", "2"), fr("3", "4")))),
        "times" to g("""Multiplies; next to a letter or bracket you can leave it out: \(2x\).""",
            s("Tap it between factors."),
            ex("6×7"), ex(fr("2", "3"), "×", fr("9", "4"))),
        "minus" to g("""Subtracts, or makes a number negative.""",
            s("Tap it between terms, or before a number."),
            ex("5−8")),
        "plus" to g("""Adds; fractions and roots are added exactly.""",
            s("Tap it between terms."),
            ex(fr("1", "2"), "+", fr("1", "3")), ex(sq("12"), "+", sq("27"))),
        "point" to g("""The decimal point; decimals are kept exact: \(0.1 + 0.2 = \frac{3}{10}\).""",
            s("Tap it inside a number."),
            ex("0.1+0.2")),
        "backspace" to g("""Deletes what's before the cursor; a long-press clears the line.""", s("Tap to delete, long-press to clear.")),
        "enter" to g("""Works the line out and adds it to the history; long-press it for the steps, when there are some.""",
            s("Tap it when the line is done.", "Long-press it for the steps."),
            ex("2+3"), ex(d(m("x", p("3"))))),
        "x" to g("""The variable \(x\). Other letters are on the \(\text{A}\alpha\) tab.""",
            s("Tap it wherever the variable goes."),
            ex(f("solve", m("x", p("2"), "−1=0"), "x")), ex("2x+3x")),
    )

    /**
     * An example's answer as the calculator works it out, and whether it's a decimal (shown with ≈).
     * When the exact answer is just the example again (erf(1)), its decimal instead, or nothing.
     */
    fun answer(e: Example): Pair<MathRow, Boolean>? {
        val angle = if (e.degrees) com.example.cas.engine.AngleUnit.Degrees else com.example.cas.engine.AngleUnit.Radians
        val a = com.example.cas.engine.Formatter.answer(com.example.cas.engine.Evaluator(angle).evaluate(MathCodec.copy(e.row)))
        val same = com.example.cas.engine.Latex.of(a.exact) == com.example.cas.engine.Latex.of(e.row)
        return when {
            !same -> a.exact to a.isApproximate
            a.approx != null -> a.approx to true
            else -> null
        }
    }

    /** The digits share one guide. */
    val digit = g("""A digit. Next to a letter or bracket it multiplies: \(2x\), \(3(x + 1)\).""", s("Tap the digits in order."), ex("12×34"))

    /** Any Latin or Greek letter: a variable. */
    val letter = g("""A letter: a variable. Give it a value with \(:=\), as in \(a := 5\); in the graphs, a letter without one gets a slider.""",
        s("Tap it wherever the letter goes."), ex("2α+3α"))
}
