package com.example.cas.ui

import com.example.cas.editor.BigOp
import com.example.cas.editor.BigOpKind
import com.example.cas.editor.Binom
import com.example.cas.editor.Derivative
import com.example.cas.editor.Frac
import com.example.cas.editor.Func
import com.example.cas.editor.Integral
import com.example.cas.editor.MathRow
import com.example.cas.editor.MathCodec
import com.example.cas.editor.Matrix
import com.example.cas.editor.Node
import com.example.cas.editor.Pow
import com.example.cas.editor.Root
import com.example.cas.editor.Sqrt
import com.example.cas.editor.Sym

/**
 * What each key's long-press card says, beyond its title and formula: what it is, how to use it
 * step by step, and worked examples. An example is the row exactly as the keys would type it; the
 * card works out its answer with the calculator itself (so it's always what you'd get), and Try it
 * types it in. Math in the text is LaTeX between \( and \).
 */
object KeyGuides {
    /** [answer] false: a relation meant for the graphs, shown without a result. */
    class Example(val row: MathRow, val note: String = "", val degrees: Boolean = false, val answer: Boolean = true)
    class Guide(val about: String, val steps: List<String>, val examples: List<Example>)

    // ---------- building rows as the keys type them (as in [Docs]) ----------

    private fun m(vararg parts: Any): MathRow = MathRow(
        parts.flatMap { p ->
            when (p) {
                is String -> p.map { Sym(it.toString()) }
                is Node -> listOf(p)
                is MathRow -> p.items
                else -> error("not math: $p")
            }
        }.toMutableList(),
    )
    private fun f(name: String, vararg args: Any) = Func(name, args.map { if (it is MathRow) it else m(it) })
    private fun fr(num: Any, den: Any) = Frac(m(num), m(den))
    private fun p(vararg e: Any) = Pow(m(*e))
    private fun sq(x: Any) = Sqrt(m(x))
    private fun rt(n: Any, x: Any) = Root(m(n), m(x))
    private fun int(body: Any, v: String = "x", lo: Any? = null, hi: Any? = null) = Integral(lo?.let { m(it) } ?: MathRow(), hi?.let { m(it) } ?: MathRow(), m(body), m(v))
    private fun d(body: Any, v: String = "x", partial: Boolean = false) = Derivative(m(v), m(body), MathRow(), MathRow(), partial)
    private fun sum(v: String, lo: Any, hi: Any, body: Any) = BigOp(BigOpKind.Sum, m(v), m(lo), m(hi), m(body))
    private fun prod(v: String, lo: Any, hi: Any, body: Any) = BigOp(BigOpKind.Product, m(v), m(lo), m(hi), m(body))
    private fun lim(body: Any, to: Any) = Func("lim", listOf(m(body), m(to)))
    private fun mat(rows: Int, cols: Int, vararg cells: Any) = Matrix(rows, cols, cells.map { m(it) })
    private fun bin(n: Any, k: Any) = Binom(m(n), m(k))
    private fun w(word: String) = Sym(word)

    private fun ex(vararg parts: Any, note: String = "", degrees: Boolean = false) = Example(m(*parts), note, degrees)
    private fun graph(vararg parts: Any, note: String) = Example(m(*parts), note, answer = false)
    private fun g(about: String, steps: List<String>, vararg examples: Example) = Guide(about, steps, examples.toList())
    private fun s(vararg t: String) = t.toList()

    /** The trigonometry tab's second page, and the statistics tab's, as the first step for their keys. */
    private const val RECIPROCAL = "On the trigonometry tab, tap the 1/△ switch beside Rad/Deg."
    private const val DISTRIBUTIONS = "On the statistics tab, tap the pdf/cdf switch beside Rad/Deg."
    private const val SIGNALS = "In a graph, tap the signals button left of the letters above the keypad."

    val all: Map<String, Guide> = mapOf(
        // ---- Basic
        "pi" to g("""The ratio of a circle's circumference to its diameter, \(\pi \approx 3.14159\); a transcendental constant. It is kept exact throughout, so \(\sin\frac{\pi}{6} = \frac{1}{2}\).""",
            s("Tap it wherever the number goes.", """Tap \(\approx\) on an answer for its decimal."""),
            ex(f("sin", fr("π", "6")), note = """Exact at multiples of \(\frac{\pi}{6}\) and \(\frac{\pi}{4}\)."""), ex("2π", "×", "3"), ex(int(f("sin", "x"), lo = "0", hi = "π"))),
        "e" to g("""Euler's number, \(e = \lim_{n \to \infty}\left(1 + \frac{1}{n}\right)^n \approx 2.71828\), the base of the natural logarithm and the unique base with \(\frac{d}{dx}e^x = e^x\).""",
            s("""Tap e, then the power key for \(e^x\).""", """It stays exact: \(\ln e^3 = 3\)."""),
            ex(f("ln", m("e", p("3")))), ex(d(m("e", p("2x")))), ex(lim(m("(1+", fr("1", "n"), ")", p("n")), "n→∞"), note = """The limit that defines \(e\).""")),
        "power" to g("""Exponentiation \(x^n\): repeated multiplication for natural \(n\), extended by \(x^{-n} = \frac{1}{x^n}\) and \(x^{p/q} = \sqrt[q]{x^p}\). The exponent may be any expression.""",
            s("Type the base.", "Tap the power key and type the exponent.", """Tap \(\rightarrow\) to come back down."""),
            ex("2", p("10")), ex("8", p(fr("2", "3")), note = """\(8^{2/3} = (\sqrt[3]{8})^2\)."""), ex("(x+1)", p("2"), "−x", p("2"))),
        "nth root" to g("""The principal \(n\)-th root, \(\sqrt[n]{x} = x^{1/n}\), the number whose \(n\)-th power is \(x\). For odd \(n\) it is real on all of \(\mathbb{R}\): \(\sqrt[3]{-8} = -2\).""",
            s("""Type \(n\) in the small box.""", """Tap \(\rightarrow\), then type the number under the root."""),
            ex(rt("3", "27")), ex(rt("3", "−8")), ex(rt("4", "48"), note = "Simplified, kept exact.")),
        "factorial" to g("""For \(n \in \mathbb{N}\), \(n! = \prod_{k=1}^{n} k\) with \(0! = 1\): the number of permutations of \(n\) objects. It extends to non-integers by \(x! = \Gamma(x + 1)\).""",
            s("Type the number (or a bracket).", "Tap n! after it."),
            ex("5!"), ex("20!", note = "Exact, however long."), ex(fr("10!", "8!"))),
        "natural log" to g("""The logarithm to base \(e\), the inverse of \(e^x\): \(\ln x = y \iff e^y = x\). On the negative reals it takes the principal complex value, \(\ln(-1) = \pi i\).""",
            s("Tap ln, then type what's inside the brackets."),
            ex(f("ln", m("e", p("2")))), ex(f("ln", "8"), note = """Simplified to \(3 \ln 2\)."""), ex(d(f("ln", "x")))),
        "log base a" to g("""The logarithm to base \(a\), the inverse of \(a^x\): \(\log_a x = \frac{\ln x}{\ln a}\), defined for \(a > 0\), \(a \ne 1\).""",
            s("Type the base in the small box.", """Tap \(\rightarrow\) and type the number."""),
            ex(f("log", "2", "8")), ex(f("log", "10", "1000")), ex(f("log", "3", "5"), note = "Kept exact; tap ≈ for the decimal.")),
        "absolute value" to g("""The modulus \(|x|\): \(x\) for \(x \ge 0\) and \(-x\) for \(x < 0\). For \(z = a + bi\) it is the distance from the origin, \(|z| = \sqrt{a^2 + b^2}\).""",
            s("Tap it, then type inside the bars."),
            ex(f("abs", "−7")), ex(f("abs", "3+4i")), ex(int(f("abs", "x"), lo = "−1", hi = "1"))),
        "mod" to g("""The remainder on division, \(a \bmod b = a - b\left\lfloor \frac{a}{b} \right\rfloor\). The result has the sign of \(b\): \(-7 \bmod 3 = 2\).""",
            s("Type the first number.", "Tap mod, then type the second."),
            ex("17", w("mod"), "5"), ex("−7", w("mod"), "3"), ex("2", p("100"), w("mod"), "7")),
        "i, the imaginary unit" to g("""The imaginary unit, defined by \(i^2 = -1\). Every complex number has the form \(a + bi\) with \(a, b \in \mathbb{R}\), or the polar form \(r e^{i\theta}\).""",
            s("""Tap it like any number; next to a number it multiplies: \(2i\)."""),
            ex("i", p("2")), ex("(2+i)(3−i)"), ex(fr("1", "1+i"))),
        "equals sign" to g("""The equality relation \(A = B\). On Enter an equation is solved for its unknown; equations separated by commas, or an equation between matrices, are solved as a system. In the graphing modes, \(y = f(x)\) or \(F(x, y) = 0\) defines a curve.""",
            s("Type the left side, tap =, then type the right side.", "Tap Enter: it is solved for its unknown.", "With several letters, choose which to solve for.", "Separate several equations with commas to solve them together."),
            ex("x", p("3"), "+1=3"), ex("x", p("2"), "=9"), ex("x+y=3,x−y=1", note = "A system: one equation per unknown."),
            ex(mat(2, 2, "1", "1", "1", "−1"), "×", mat(2, 1, "x", "y"), "=", mat(2, 1, "3", "1"), note = "The same system as a matrix equation.")),
        "less than" to g("""The strict order relation \(a < b\); with = it gives \(a \le b\). In the graphing modes an inequality in \(x\) and \(y\) defines a shaded region.""",
            s("Type the left side, tap <, type the right side.", """Tap > then = for \(\ge\) (or < then = for \(\le\)).""", "Tap Enter: it is solved for its unknown."),
            ex("2x+1<7"), ex("x", p("2"), "<4"), graph("y<x", p("2"), note = "The region below the parabola, in the graphs.")),
        "greater than" to g("""The strict order relation \(a > b\); with = it gives \(a \ge b\). In the graphing modes an inequality in \(x\) and \(y\) defines a shaded region.""",
            s("Type the left side, tap >, type the right side.", "Tap Enter: it is solved for its unknown."),
            ex("x", p("2"), ">4"), ex("3x−5>1"), graph("x", p("2"), "+y", p("2"), ">1", note = "The outside of the unit circle, in the graphs.")),
        "comma" to g("""The separator between the elements of a list and between the arguments of a function of several variables, as in \(\gcd(12, 18)\).""",
            s("Tap it between values."),
            ex(f("mean", "2,4,9")), ex(f("max", "3", "8"))),
        "previous answer" to g("""The most recent result, \(\text{Ans}\). An operator entered on an empty line acts on it, so computations can be chained.""",
            s("Tap Ans where the last answer should go.", """Or tap \(+\), \(\times\)… right after = to carry on from it."""),
        ),
        // ---- Trigonometry
        "sin" to g("""The sine: on the unit circle, the \(y\)-coordinate of the point at angle \(\theta\); in a right triangle, opposite over hypotenuse. Periodic with period \(2\pi\) and range \([-1, 1]\).""",
            s("Rad/Deg above the keys sets the angle unit.", "Tap sin, then type the angle."),
            ex(f("sin", fr("π", "6"))), ex(f("sin", "30"), note = "In degrees.", degrees = true), ex(d(f("sin", "x")))),
        "inverse sin" to g("""The arcsine, the inverse of \(\sin\) on \(\left[-\frac{\pi}{2}, \frac{\pi}{2}\right]\). Real for \(|x| \le 1\); complex-valued outside.""",
            s("Tap it, then type the sine."),
            ex(f("asin", fr("1", "2"))), ex(f("asin", "1"), note = "In degrees.", degrees = true), ex(d(f("asin", "x")))),
        "hyperbolic sin" to g("""The hyperbolic sine, \(\sinh x = \frac{e^x - e^{-x}}{2}\), an odd function. The point \((\cosh t, \sinh t)\) traces the hyperbola \(x^2 - y^2 = 1\).""",
            s("Tap it, then type the number."),
            ex(f("sinh", "0")), ex(f("sinh", f("ln", "2"))), ex(d(f("sinh", "x")))),
        "inverse hyperbolic sin" to g("""The inverse of \(\sinh\), defined on all of \(\mathbb{R}\): \(\operatorname{asinh} x = \ln\left(x + \sqrt{x^2 + 1}\right)\).""",
            s("Tap it, then type the number."),
            ex(f("asinh", "0")), ex(f("asinh", fr("3", "4"))), ex(d(f("asinh", "x")))),
        "cos" to g("""The cosine: on the unit circle, the \(x\)-coordinate of the point at angle \(\theta\); in a right triangle, adjacent over hypotenuse. Periodic with period \(2\pi\) and range \([-1, 1]\).""",
            s("Rad/Deg above the keys sets the angle unit.", "Tap cos, then type the angle."),
            ex(f("cos", fr("π", "3"))), ex(f("cos", "60"), note = "In degrees.", degrees = true), ex(int(f("cos", "x")))),
        "inverse cos" to g("""The arccosine, the inverse of \(\cos\) on \([0, \pi]\). Real for \(|x| \le 1\).""",
            s("Tap it, then type the cosine."),
            ex(f("acos", "0")), ex(f("acos", fr("−1", "2")), note = "In degrees.", degrees = true)),
        "hyperbolic cos" to g("""The hyperbolic cosine, \(\cosh x = \frac{e^x + e^{-x}}{2}\), an even function with \(\cosh x \ge 1\). Its graph is the catenary.""",
            s("Tap it, then type the number."),
            ex(f("cosh", "0")), ex(f("cosh", "x"), p("2"), "−", f("sinh", "x"), p("2"), note = "Always 1.")),
        "inverse hyperbolic cos" to g("""The inverse of \(\cosh\) restricted to \(x \ge 0\), defined for \(x \ge 1\): \(\operatorname{acosh} x = \ln\left(x + \sqrt{x^2 - 1}\right)\).""",
            s("Tap it, then type the number."),
            ex(f("acosh", "1")), ex(f("acosh", fr("5", "4")))),
        "tan" to g("""The tangent, \(\tan\theta = \frac{\sin\theta}{\cos\theta}\): the slope of the line at angle \(\theta\). Periodic with period \(\pi\), with poles at \(\theta = \frac{\pi}{2} + k\pi\).""",
            s("Rad/Deg above the keys sets the angle unit.", "Tap tan, then type the angle."),
            ex(f("tan", fr("π", "4"))), ex(f("tan", "60"), note = "In degrees.", degrees = true), ex(d(f("tan", "x")))),
        "inverse tan" to g("""The arctangent, the inverse of \(\tan\) on \(\left(-\frac{\pi}{2}, \frac{\pi}{2}\right)\), defined on all of \(\mathbb{R}\).""",
            s("Tap it, then type the tangent."),
            ex(f("atan", "1")), ex(int(fr("1", m("1+x", p("2"))))), ex(lim(f("atan", "x"), "x→∞"))),
        "hyperbolic tan" to g("""The hyperbolic tangent, \(\tanh x = \frac{\sinh x}{\cosh x}\), an odd, increasing function with horizontal asymptotes \(y = \pm 1\).""",
            s("Tap it, then type the number."),
            ex(f("tanh", "0")), ex(lim(f("tanh", "x"), "x→∞"))),
        "inverse hyperbolic tan" to g("""The inverse of \(\tanh\), defined for \(|x| < 1\): \(\operatorname{atanh} x = \frac{1}{2}\ln\frac{1 + x}{1 - x}\).""",
            s("Tap it, then type the number."),
            ex(f("atanh", "0")), ex(f("atanh", fr("1", "2")))),
        // ---- Reciprocal trigonometry (the trigonometry tab's second page)
        "cosecant" to g("""The cosecant, \(\csc x = \frac{1}{\sin x}\), defined where \(\sin x \ne 0\).""",
            s(RECIPROCAL, "Tap csc, then type the angle."),
            ex(f("csc", fr("π", "6"))), ex(f("csc", "30"), note = "In degrees.", degrees = true), ex(d(f("csc", "x")))),
        "inverse cosecant" to g("""The inverse cosecant, \(\operatorname{acsc} x = \arcsin\frac{1}{x}\), defined for \(|x| \ge 1\).""",
            s(RECIPROCAL, "Tap acsc, then type the number."),
            ex(f("acsc", "2")), ex(f("acsc", "1"))),
        "hyperbolic cosecant" to g("""The hyperbolic cosecant, \(\operatorname{csch} x = \frac{1}{\sinh x}\), defined for \(x \ne 0\).""",
            s(RECIPROCAL, "Tap csch, then type the number."),
            ex(f("csch", f("ln", "2"))), ex(d(f("csch", "x")))),
        "inverse hyperbolic cosecant" to g("""The inverse hyperbolic cosecant, \(\operatorname{acsch} x = \operatorname{asinh}\frac{1}{x}\), defined for \(x \ne 0\).""",
            s(RECIPROCAL, "Tap acsch, then type the number."),
            ex(f("acsch", "1"))),
        "secant" to g("""The secant, \(\sec x = \frac{1}{\cos x}\), defined where \(\cos x \ne 0\).""",
            s(RECIPROCAL, "Tap sec, then type the angle."),
            ex(f("sec", fr("π", "3"))), ex(f("sec", "60"), note = "In degrees.", degrees = true), ex(int(f("sec", "x")), note = "Long-press enter for the steps.")),
        "inverse secant" to g("""The inverse secant, \(\operatorname{asec} x = \arccos\frac{1}{x}\), defined for \(|x| \ge 1\).""",
            s(RECIPROCAL, "Tap asec, then type the number."),
            ex(f("asec", "2")), ex(f("asec", "−1"))),
        "hyperbolic secant" to g("""The hyperbolic secant, \(\operatorname{sech} x = \frac{1}{\cosh x}\), an even function with \(0 < \operatorname{sech} x \le 1\).""",
            s(RECIPROCAL, "Tap sech, then type the number."),
            ex(f("sech", "0")), ex(int(f("sech", "x"), lo = "−∞", hi = "∞"))),
        "inverse hyperbolic secant" to g("""The inverse hyperbolic secant, \(\operatorname{asech} x = \operatorname{acosh}\frac{1}{x}\), defined for \(0 < x \le 1\).""",
            s(RECIPROCAL, "Tap asech, then type the number."),
            ex(f("asech", "1")), ex(f("asech", fr("4", "5")))),
        "cotangent" to g("""The cotangent, \(\cot x = \frac{\cos x}{\sin x}\), defined where \(\sin x \ne 0\); periodic with period \(\pi\).""",
            s(RECIPROCAL, "Tap cot, then type the angle."),
            ex(f("cot", fr("π", "4"))), ex(d(f("cot", "x")))),
        "inverse cotangent" to g("""The inverse cotangent, \(\operatorname{acot} x = \arctan\frac{1}{x}\).""",
            s(RECIPROCAL, "Tap acot, then type the number."),
            ex(f("acot", "1"))),
        "hyperbolic cotangent" to g("""The hyperbolic cotangent, \(\operatorname{coth} x = \frac{\cosh x}{\sinh x}\), defined for \(x \ne 0\), with horizontal asymptotes \(y = \pm 1\).""",
            s(RECIPROCAL, "Tap coth, then type the number."),
            ex(f("coth", f("ln", "2"))), ex(lim(f("coth", "x"), "x→∞"))),
        "inverse hyperbolic cotangent" to g("""The inverse hyperbolic cotangent, \(\operatorname{acoth} x = \frac{1}{2}\ln\frac{x + 1}{x - 1}\), defined for \(|x| > 1\).""",
            s(RECIPROCAL, "Tap acoth, then type the number."),
            ex(f("acoth", "2"))),
        // ---- Calculus
        "partial derivative" to g("""The rate of change of a function of several variables with respect to one of them, the others held constant: \(\frac{\partial}{\partial y}\left(x^2 y\right) = x^2\).""",
            s("Tap it and type the function.", """Tap the \(x\) in \(\partial x\) to change the variable."""),
            ex(d(m("x", p("2"), "y"), v = "y", partial = true)), ex(d(m(f("sin", "xy")), v = "x", partial = true))),
        "integral" to g("""The definite integral \(\int_a^b f(x)\,dx = F(b) - F(a)\), where \(F' = f\): the signed area under \(f\). Without limits it gives the antiderivative \(F(x) + C\).""",
            s("Tap it and type the function.", "Fill the limits, or leave them empty.", """\(\infty\) works as a limit; long-press enter for the steps."""),
            ex(int(m("x", p("2")), lo = "0", hi = "1")), ex(int(m("x", "e", p("x")))), ex(int(m("e", p("−x", p("2"))), lo = "−∞", hi = "∞"))),
        "limit" to g("""The value \(L = \lim_{x \to a} f(x)\) that \(f(x)\) approaches as \(x \to a\); \(a\) may be \(\pm\infty\).""",
            s("Tap it and type the expression.", """Change \(x \to 0\) underneath; \(\infty\) is allowed."""),
            ex(lim(fr(f("sin", "x"), "x"), "x→0")), ex(lim(m("(1+", fr("1", "n"), ")", p("n")), "n→∞")), ex(lim(fr("1", "x"), m("x→0", p("+"))), note = "From the right.")),
        "sum" to g("""The finite or infinite series \(\sum_{k=a}^{b} f(k) = f(a) + f(a + 1) + \cdots + f(b)\). Closed forms are found where they exist.""",
            s("Fill the variable and its start below, the end above.", "Type the term."),
            ex(sum("k", "1", "100", "k")), ex(sum("n", "1", "∞", fr("1", m("n", p("2"))))), ex(sum("k", "0", "n", m("2", p("k"))))),
        "product" to g("""The product \(\prod_{k=a}^{b} f(k) = f(a) \cdot f(a + 1) \cdots f(b)\).""",
            s("Fill the variable and its start below, the end above.", "Type the factor."),
            ex(prod("k", "1", "5", "k")), ex(prod("k", "1", "4", m("1+", fr("1", "k"))), note = "It telescopes to 5.")),
        "Taylor series" to g("""The Taylor polynomial of order \(N\) of \(f\) about \(a\): \(\sum_{n=0}^{N} \frac{f^{(n)}(a)}{n!}(x - a)^n\), which agrees with \(f\) and its first \(N\) derivatives at \(a\).""",
            s("Type the function.", "Set the point after the arrow and the order."),
            ex(f("taylor", m("e", p("x")), "x→0", "3")), ex(f("taylor", f("sin", "x"), "x→0", "5"))),
        "y prime" to g("""The first derivative \(y' = \frac{dy}{dx}\) of the unknown function \(y(x)\) in a differential equation.""",
            s("""Type the differential equation with it, such as \(y' = 2y\).""", """Add conditions after commas, like \(y(0) = 1\), then tap Enter: it is solved for \(y\)."""),
            ex("y", "′", "=y"), ex("y", "′", "=2y,y(0)=1")),
        "y double prime" to g("""The second derivative \(y'' = \frac{d^2 y}{dx^2}\) of the unknown function \(y(x)\) in a differential equation.""",
            s("""Type the differential equation with it, such as \(y'' + y = 0\), then tap Enter."""),
            ex("y", "′", "′", "+y=0"), ex("y", "′", "′", "−3y", "′", "+2y=0")),
        "solve differential equation" to g("""Finds the general or particular solution \(y(x)\) of an ordinary differential equation: first-order linear and separable equations, and second-order linear equations with constant coefficients. Arbitrary constants appear as \(C_1, C_2\).""",
            s("Type the equation in the box.", """Add conditions after commas, like \(y(0) = 1\).""", """The equation typed on its own, \(y' = 2y\), is solved the same way on Enter."""),
            ex(f("dsolve", m("y", "′", "=2y,y(0)=1"))), ex(f("dsolve", m("y", "′", "′", "+y=0")))),
        "infinity" to g("""The symbol \(\infty\), used as a limit point or as a bound of sums and integrals.""",
            s("Tap it in a limit or bound."),
            ex(int(m("e", p("−x")), lo = "0", hi = "∞")), ex(lim(fr("1", "x"), "x→∞"))),
        "gradient" to g("""The gradient \(\nabla f = \left(\frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \frac{\partial f}{\partial z}\right)\), which points in the direction of steepest ascent. With exponent 2 it is the Laplacian \(\nabla^2 f\).""",
            s("Tap it and type the function.", "The switch above the keys picks Cartesian, cylindrical or spherical coordinates."),
            ex(f("grad", m("x", p("2"), "+y", p("2")), MathRow())), ex(f("grad", m("x", p("2"), "y"), m("2")))),
        "divergence" to g("""The divergence of a vector field \(F = (P, Q, R)\), \(\nabla \cdot F = \frac{\partial P}{\partial x} + \frac{\partial Q}{\partial y} + \frac{\partial R}{\partial z}\): the net outward flux per unit volume.""",
            s("Tap it and type the field as a vector."),
            ex(f("div", mat(3, 1, "x", "y", "z")))),
        "curl" to g("""The curl of a vector field in \(\mathbb{R}^3\), \(\nabla \times F\): a vector measuring the local rotation of the field.""",
            s("Tap it and type the field as a 3-vector."),
            ex(f("curl", mat(3, 1, "−y", "x", "0")))),
        "Jacobian matrix" to g("""For \(F: \mathbb{R}^n \to \mathbb{R}^m\), the \(m \times n\) matrix \(J_{ij} = \frac{\partial F_i}{\partial x_j}\), the best linear approximation of \(F\) at a point.""",
            s("Tap it and type the function as a vector."),
            ex(f("jacobian", mat(2, 1, "xy", "x+y")))),
        "Hessian matrix" to g("""The symmetric matrix of second partial derivatives, \(H_{ij} = \frac{\partial^2 f}{\partial x_i \partial x_j}\), which describes the local curvature of \(f\).""",
            s("Tap it and type the function."),
            ex(f("hessian", m("x", p("2"), "y")))),
        // ---- Linear algebra
        "matrix" to g("""A rectangular array of entries with \(m\) rows and \(n\) columns. It grows as its last row or column is filled.""",
            s("Tap it: a matrix appears.", "Fill the boxes; type in the last row or column to add more."),
            ex(mat(2, 2, "1", "2", "3", "4"), "+", mat(2, 2, "1", "0", "0", "1"))),
        "inverse" to g("""The matrix \(A^{-1}\) with \(A A^{-1} = A^{-1} A = I\). It exists if and only if \(\det A \ne 0\).""",
            s("Type the matrix.", "Tap the key after it.", "Long-press enter for the row steps."),
            ex(mat(2, 2, "2", "1", "1", "1"), p("−1")), ex(mat(2, 2, "a", "b", "c", "d"), p("−1"))),
        "transpose" to g("""The transpose \(A^{\top}\), with \(\left(A^{\top}\right)_{ij} = A_{ji}\): rows and columns interchanged.""",
            s("Type the matrix, then tap the key."),
            ex(mat(2, 3, "1", "2", "3", "4", "5", "6"), p("T"))),
        "conjugate transpose" to g("""The conjugate transpose \(A^{\mathrm{H}}\), with \(\left(A^{\mathrm{H}}\right)_{ij} = \overline{A_{ji}}\). For a real matrix it equals \(A^{\top}\).""",
            s("Type the matrix, then tap the key."),
            ex(mat(2, 2, "1", "i", "2", "3−i"), p("H"))),
        "determinant" to g("""The determinant \(\det A\) of a square matrix: the factor by which \(A\) scales volume. It is zero if and only if \(A\) is singular.""",
            s("Tap det, then type or tap a matrix."),
            ex(f("det", mat(2, 2, "1", "2", "3", "4"))), ex(f("det", mat(2, 2, "a", "b", "c", "d")))),
        "dot product" to g("""The scalar product \(u \cdot v = \sum_i u_i v_i = |u|\,|v|\cos\theta\); it vanishes exactly when \(u\) and \(v\) are orthogonal.""",
            s("Type the two vectors in the boxes."),
            ex(f("dot", mat(3, 1, "1", "2", "3"), mat(3, 1, "4", "5", "6")))),
        "cross product" to g("""For \(u, v \in \mathbb{R}^3\), the vector \(u \times v\) orthogonal to both, with length \(|u|\,|v|\sin\theta\), the area of the parallelogram they span.""",
            s("Type the two 3-vectors in the boxes."),
            ex(f("cross", mat(3, 1, "1", "0", "0"), mat(3, 1, "0", "1", "0")))),
        "Hadamard product" to g("""The entrywise product \((A \circ B)_{ij} = A_{ij} B_{ij}\) of two matrices of equal size.""",
            s("Type the two matrices in the boxes."),
            ex(f("hadamard", mat(1, 2, "1", "2"), mat(1, 2, "3", "4")))),
        "Kronecker product" to g("""The block matrix \(A \otimes B = \left(a_{ij} B\right)\); an \(m \times n\) and a \(p \times q\) matrix give an \(mp \times nq\) matrix.""",
            s("Type the two matrices in the boxes."),
            ex(f("kron", mat(2, 2, "1", "0", "0", "1"), mat(2, 2, "1", "2", "3", "4")))),
        "trace" to g("""The trace \(\operatorname{tr} A = \sum_i a_{ii}\), the sum of the diagonal entries, which equals the sum of the eigenvalues.""",
            s("Tap tr, then type a matrix."),
            ex(f("trace", mat(2, 2, "1", "2", "3", "4")))),
        "eigenvalues" to g("""The scalars \(\lambda\) for which \(A v = \lambda v\) has a solution \(v \ne 0\); equivalently, the roots of \(\det(A - \lambda I) = 0\).""",
            s("Tap it, then type a square matrix.", "Long-press enter for the steps."),
            ex(f("eigvals", mat(2, 2, "2", "1", "1", "2"))), ex(f("eigvals", mat(2, 2, "0", "−1", "1", "0")))),
        "eigenvectors" to g("""The nonzero vectors \(v\) with \(A v = \lambda v\), listed with their eigenvalues \(\lambda\).""",
            s("Tap it, then type a square matrix."),
            ex(f("eigvecs", mat(2, 2, "2", "1", "1", "2")))),
        "characteristic polynomial" to g("""The polynomial \(p(\lambda) = \det(\lambda I - A)\), whose roots are the eigenvalues of \(A\).""",
            s("Tap it, then type a square matrix."),
            ex(f("charpoly", mat(2, 2, "1", "2", "3", "4")))),
        "reduced row echelon form" to g("""The unique matrix row-equivalent to \(A\) in which each leading entry is 1 and is the only nonzero entry in its column. For an augmented matrix it exhibits the solution of the linear system.""",
            s("Tap rref, then type the matrix.", "Long-press enter for each row operation."),
            ex(f("rref", mat(2, 3, "1", "1", "3", "1", "−1", "1")), note = """The augmented matrix of \(x + y = 3,\ x - y = 1\).""")),
        "rank" to g("""The rank of \(A\): the dimension of its column space, equal to the number of linearly independent rows.""",
            s("Tap rk, then type the matrix."),
            ex(f("rank", mat(2, 2, "1", "2", "2", "4"))), ex(f("rank", mat(2, 2, "1", "2", "3", "4")))),
        // ---- Statistics
        "mean" to g("""The arithmetic mean \(\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i\).""",
            s("Tap it, then type the values with commas."),
            ex(f("mean", "2,4,4,5")), ex(f("mean", "1,2,3,4,100"), note = "One large value pulls the mean up.")),
        "median" to g("""The middle value of the sorted data; for an even number of values, the mean of the two middle values.""",
            s("Tap it, then type the values with commas."),
            ex(f("median", "3,1,7,5")), ex(f("median", "1,2,3,4,100"), note = "Unmoved by the large value.")),
        "sample standard deviation" to g("""The sample standard deviation \(s = \sqrt{\frac{1}{n - 1}\sum_{i=1}^{n} (x_i - \bar{x})^2}\), with Bessel's correction \(n - 1\).""",
            s("Tap s, then type the values with commas."),
            ex(f("sd", "2,4,4,4,5,5,7,9"))),
        "population standard deviation" to g("""The population standard deviation \(\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n} (x_i - \mu)^2}\).""",
            s("""Tap \(\sigma\), then type the values with commas."""),
            ex(f("psd", "2,4,4,4,5,5,7,9"))),
        "sample variance" to g("""The sample variance \(s^2 = \frac{1}{n - 1}\sum_{i=1}^{n} (x_i - \bar{x})^2\).""",
            s("""Tap \(s^2\), then type the values with commas."""),
            ex(f("var", "1,2,3,4"))),
        "n choose k" to g("""The binomial coefficient \(\binom{n}{k} = \frac{n!}{k!\,(n - k)!}\): the number of \(k\)-element subsets of an \(n\)-element set, and the coefficient of \(a^k b^{n-k}\) in \((a + b)^n\).""",
            s("""Type \(n\) in the top box.""", """Tap \(\rightarrow\) and type \(k\) in the bottom box."""),
            ex(bin("5", "2"), note = "Pairs from 5 people."), ex(bin("10", "3"), note = "Three toppings from ten."), ex(bin("52", "5"), note = "Poker hands.")),
        "permutations" to g("""The number of ordered selections of \(k\) objects from \(n\), \(P(n, k) = \frac{n!}{(n - k)!}\).""",
            s("""Fill \(n\), then \(k\)."""),
            ex(f("perm", "5", "2")), ex(f("perm", "10", "3"), note = "Gold, silver, bronze among 10.")),
        "normal density" to g("""The probability density of \(\mathcal{N}(\mu, \sigma^2)\), \(\varphi(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{(x - \mu)^2}{2\sigma^2}}\).""",
            s("""Fill \(x\); \(\mu = 0\) and \(\sigma = 1\) are filled in, change them as needed."""),
            ex(f("normpdf", "0", "0", "1")), ex(f("normpdf", "x", "0", "1"))),
        "normal distribution function" to g("""The cumulative distribution function \(P(X \le x)\) of \(\mathcal{N}(\mu, \sigma^2)\), \(\Phi(x) = \frac{1}{2}\left(1 + \operatorname{erf}\frac{x - \mu}{\sigma\sqrt{2}}\right)\).""",
            s("""Fill \(x\), \(\mu\) and \(\sigma\)."""),
            ex(f("normcdf", "1.96", "0", "1")), ex(f("normcdf", "0", "0", "1"))),
        "inverse normal" to g("""The quantile function of the normal distribution: the value \(x\) with \(\Phi(x) = p\).""",
            s("""Tap it and type \(p\)."""),
            ex(f("invnorm", "0.975")), ex(f("invnorm", fr("1", "2")))),
        "binomial probability" to g("""The probability mass function of \(\operatorname{Bin}(n, p)\), \(P(X = k) = \binom{n}{k} p^k (1 - p)^{n - k}\).""",
            s("""Fill \(n\), \(p\) and \(k\)."""),
            ex(f("binompdf", "10", "0.5", "5")), ex(f("binompdf", "4", fr("1", "6"), "1"), note = "One six in four rolls.")),
        "cumulative binomial probability" to g("""The cumulative distribution function of \(\operatorname{Bin}(n, p)\), \(P(X \le k) = \sum_{i=0}^{k} \binom{n}{i} p^i (1 - p)^{n - i}\).""",
            s("""Fill \(n\), \(p\) and \(k\)."""),
            ex(f("binomcdf", "10", "0.5", "5"))),
        "Poisson probability" to g("""The probability mass function of the Poisson distribution with rate \(\lambda\), \(P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}\).""",
            s("""Fill \(\lambda\) and \(k\)."""),
            ex(f("poissonpdf", "2", "0")), ex(f("poissonpdf", "3", "2"))),
        "sum of a list" to g("""The sum \(\sum_i x_i\) of the elements of a list.""",
            s("Tap it, then type the values with commas."),
            ex(f("total", "1,2,3,4"))),
        "comma for lists" to g("""The separator between the elements of a list.""",
            s("Tap it between values."),
            ex(f("mean", "1,2,3"))),
        // ---- Distributions (the statistics tab's second page)
        "exponential density" to g("""The density of the exponential distribution with rate \(\lambda\), \(f(x) = \lambda e^{-\lambda x}\) for \(x \ge 0\): the waiting time of a Poisson process.""",
            s(DISTRIBUTIONS, """Fill \(x\) and the rate \(\lambda\)."""),
            ex(f("exppdf", "1", "2")), ex(int(f("exppdf", "x", "2"), lo = "0", hi = "∞"), note = "A density's total is 1.")),
        "exponential distribution function" to g("""The cumulative distribution function of the exponential distribution, \(F(x) = 1 - e^{-\lambda x}\) for \(x \ge 0\).""",
            s(DISTRIBUTIONS, """Fill \(x\) and \(\lambda\)."""),
            ex(f("expcdf", "1", "2"))),
        "uniform density" to g("""The density of the continuous uniform distribution on \([a, b]\), \(f(x) = \frac{1}{b - a}\) for \(a \le x \le b\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("unifpdf", "3", "1", "5"))),
        "uniform distribution function" to g("""The cumulative distribution function of the uniform distribution on \([a, b]\), \(F(x) = \frac{x - a}{b - a}\) for \(a \le x \le b\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("unifcdf", "3", "1", "5"))),
        "cumulative Poisson probability" to g("""The cumulative distribution function of the Poisson distribution, \(P(X \le k) = e^{-\lambda}\sum_{i=0}^{k} \frac{\lambda^i}{i!}\).""",
            s(DISTRIBUTIONS, """Fill \(\lambda\) and \(k\)."""),
            ex(f("poissoncdf", "2", "3"))),
        "geometric probability" to g("""The probability that the first success occurs on trial \(k\), \(P(X = k) = (1 - p)^{k - 1} p\).""",
            s(DISTRIBUTIONS, """Fill \(p\) and \(k\)."""),
            ex(f("geompdf", fr("1", "6"), "3"), note = "The first six on the third roll.")),
        "cumulative geometric probability" to g("""The probability of a first success within \(k\) trials, \(P(X \le k) = 1 - (1 - p)^k\).""",
            s(DISTRIBUTIONS, """Fill \(p\) and \(k\)."""),
            ex(f("geomcdf", fr("1", "6"), "3"), note = "A six within three rolls.")),
        "chi-squared density" to g("""The density of \(\chi^2_k\), the sum of \(k\) squared independent standard normal variables: \(f(x) = \frac{x^{k/2 - 1} e^{-x/2}}{2^{k/2}\Gamma(k/2)}\).""",
            s(DISTRIBUTIONS, """Fill \(x\) and the degrees of freedom \(k\)."""),
            ex(f("chi2pdf", "1", "3"))),
        "chi-squared distribution function" to g("""The cumulative distribution function of \(\chi^2_k\), used in goodness-of-fit tests and tests of variance.""",
            s(DISTRIBUTIONS, """Fill \(x\) and \(k\)."""),
            ex(f("chi2cdf", "7.815", "3"), note = "The 5% critical value for 3 degrees of freedom.")),
        "log-normal density" to g("""The density of a variable whose logarithm is \(\mathcal{N}(\mu, \sigma^2)\): \(f(x) = \frac{1}{x\sigma\sqrt{2\pi}} e^{-\frac{(\ln x - \mu)^2}{2\sigma^2}}\) for \(x > 0\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(\mu\) and \(\sigma\)."""),
            ex(f("lognpdf", "1", "0", "1"))),
        "log-normal distribution function" to g("""The cumulative distribution function of the log-normal distribution, \(F(x) = \Phi\left(\frac{\ln x - \mu}{\sigma}\right)\); its median is \(e^{\mu}\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(\mu\) and \(\sigma\)."""),
            ex(f("logncdf", "1", "0", "1"))),
        "Cauchy density" to g("""The density of the Cauchy distribution with location \(x_0\) and scale \(\gamma\), \(f(x) = \frac{1}{\pi\gamma\left(1 + \left(\frac{x - x_0}{\gamma}\right)^2\right)}\); it has no mean or variance.""",
            s(DISTRIBUTIONS, """Fill \(x\), the centre \(x_0\) and the width \(\gamma\)."""),
            ex(f("cauchypdf", "0", "0", "1"))),
        "Cauchy distribution function" to g("""The cumulative distribution function of the Cauchy distribution, \(F(x) = \frac{1}{2} + \frac{1}{\pi}\arctan\frac{x - x_0}{\gamma}\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(x_0\) and \(\gamma\)."""),
            ex(f("cauchycdf", "1", "0", "1"))),
        "Weibull density" to g("""The density of the Weibull distribution with shape \(k\) and scale \(\lambda\), \(f(x) = \frac{k}{\lambda}\left(\frac{x}{\lambda}\right)^{k - 1} e^{-(x/\lambda)^k}\); for \(k = 1\) it is exponential.""",
            s(DISTRIBUTIONS, """Fill \(x\), \(k\) and \(\lambda\)."""),
            ex(f("weibpdf", "1", "2", "1"))),
        "Weibull distribution function" to g("""The cumulative distribution function of the Weibull distribution, \(F(x) = 1 - e^{-(x/\lambda)^k}\) for \(x \ge 0\).""",
            s(DISTRIBUTIONS, """Fill \(x\), \(k\) and \(\lambda\)."""),
            ex(f("weibcdf", "1", "2", "1"))),
        // ---- Complex numbers
        "real part" to g("""The real part of \(z = a + bi\), \(\operatorname{Re} z = a\).""",
            s("Tap it, then type the number."),
            ex(f("Re", "3+4i")), ex(f("Re", m("e", p("i", fr("π", "3")))))),
        "imaginary part" to g("""The imaginary part of \(z = a + bi\), \(\operatorname{Im} z = b\).""",
            s("Tap it, then type the number."),
            ex(f("Im", "3+4i"))),
        "conjugate" to g("""The complex conjugate \(\bar{z} = a - bi\) of \(z = a + bi\): its reflection in the real axis, with \(z\bar{z} = |z|^2\).""",
            s("Tap it, then type the number."),
            ex(f("conj", "3+4i")), ex("(3+4i)", f("conj", "3+4i"))),
        "argument" to g("""The principal argument \(\arg z\), with \(-\pi < \arg z \le \pi\): the angle from the positive real axis to \(z\).""",
            s("Tap it, then type the number; Rad/Deg sets the unit."),
            ex(f("arg", "1+i")), ex(f("arg", "−1"), degrees = true, note = "In degrees.")),
        "e to the i theta" to g("""Euler's formula, \(e^{i\theta} = \cos\theta + i\sin\theta\): the point at angle \(\theta\) on the unit circle.""",
            s("""Type the angle after \(i\) in the power."""),
            ex("e", p("iπ")), ex("e", p("i", fr("π", "2")))),
        "gamma function" to g("""The analytic continuation of the factorial, \(\Gamma(z) = \int_0^{\infty} t^{z - 1} e^{-t}\,dt\), with \(\Gamma(n) = (n - 1)!\); it has poles at \(0, -1, -2, \ldots\)""",
            s("Tap it, then type the number."),
            ex(f("gamma", "5")), ex(f("gamma", fr("1", "2")))),
        "Riemann zeta function" to g("""The Riemann zeta function, \(\zeta(s) = \sum_{n=1}^{\infty} \frac{1}{n^s}\) for \(\operatorname{Re} s > 1\), extended to all \(s \ne 1\) by analytic continuation.""",
            s("""Tap it, then type \(s\)."""),
            ex(f("zeta", "2")), ex(f("zeta", "−1"))),
        "Lambert W function" to g("""The inverse of \(w \mapsto w e^w\): \(W(z) e^{W(z)} = z\). It expresses the roots of equations such as \(x e^x = a\).""",
            s("""Tap it, then type \(z\)."""),
            ex(f("lambertw", "1")), ex(f("lambertw", "e"))),
        "Bessel function of the first kind" to g("""\(J_a(x)\), the solution of Bessel's equation \(x^2 y'' + x y' + (x^2 - a^2) y = 0\) that is finite at the origin.""",
            s("""Type the order \(a\) in the small box, then the number."""),
            ex(f("besselj", "0", "0")), ex(f("besselj", "1", "2"))),
        "Bessel function of the second kind" to g("""\(Y_a(x)\), the second linearly independent solution of Bessel's equation, singular at the origin.""",
            s("""Type the order \(a\) in the small box, then the number."""),
            ex(f("bessely", "0", "1"))),
        "contour integral" to g("""The integral \(\oint_C f(z)\,dz\) along a closed curve, taken counterclockwise. By the residue theorem it equals \(2\pi i\) times the sum of the residues enclosed.""",
            s("Type the function.", """Change the circle underneath, \(|z| = 1\) to start with."""),
            ex(f("contour", fr("1", "z"), m(f("abs", "z"), "=1"))), ex(f("contour", fr(m("e", p("z")), m("z", p("2"))), m(f("abs", "z"), "=2")))),
        "residue" to g("""The residue \(\operatorname{Res}_{z = a} f\), the coefficient of \((z - a)^{-1}\) in the Laurent expansion of \(f\) about \(a\).""",
            s("Type the function, then the point underneath."),
            ex(f("residue", fr(m("e", p("z")), m("z", p("2"))), "z=0"))),
        "z" to g("""The complex variable \(z = x + iy\), the default variable of the complex-plane mode.""",
            s("Tap it wherever the variable goes."),
            ex("z", p("2"), "+1=0", note = "Solved on Enter, complex roots included."), ex(d(m("z", p("3")), "z"))),
        "w" to g("""A second complex variable, used for an image \(w = f(z)\) or as a parameter.""",
            s("Tap it like any letter."),
            ex("2w+3w")),
        // ---- Special functions
        "error function" to g("""The error function \(\operatorname{erf} x = \frac{2}{\sqrt{\pi}}\int_0^x e^{-t^2}\,dt\), an odd function with limits \(\pm 1\).""",
            s("Tap it, then type the number."),
            ex(f("erf", "1")), ex(int(m("e", p("−x", p("2"))))), ex(d(f("erf", "x")))),
        "imaginary error function" to g("""The imaginary error function \(\operatorname{erfi} x = -i\operatorname{erf}(ix) = \frac{2}{\sqrt{\pi}}\int_0^x e^{t^2}\,dt\).""",
            s("Tap it, then type the number."),
            ex(f("erfi", "1")), ex(int(m("e", p("x", p("2")))))),
        "upper incomplete gamma function" to g("""The upper incomplete gamma function \(\Gamma(s, x) = \int_x^{\infty} t^{s-1} e^{-t}\,dt\), with \(\Gamma(s, 0) = \Gamma(s)\).""",
            s("""Fill \(s\), then \(x\)."""),
            ex(f("gammainc", "1", "2")), ex(f("gammainc", "3", "0"))),
        "digamma function" to g("""The logarithmic derivative of the gamma function, \(\psi(x) = \frac{\Gamma'(x)}{\Gamma(x)}\), with \(\psi(1) = -\gamma\).""",
            s("Tap it, then type the number."),
            ex(f("digamma", "1"))),
        "Hurwitz zeta function" to g("""The Hurwitz zeta function \(\zeta(s, a) = \sum_{n=0}^{\infty} \frac{1}{(n + a)^s}\), with \(\zeta(s, 1) = \zeta(s)\).""",
            s("""Fill \(s\), then \(a\)."""),
            ex(f("hurwitz", "2", "1"))),
        "sine integral" to g("""The sine integral \(\operatorname{Si}(x) = \int_0^x \frac{\sin t}{t}\,dt\), with \(\lim_{x \to \infty} \operatorname{Si}(x) = \frac{\pi}{2}\).""",
            s("Tap it, then type the number."),
            ex(f("si", "1")), ex(int(fr(f("sin", "x"), "x"))), ex(lim(f("si", "x"), "x→∞"))),
        "cosine integral" to g("""The cosine integral \(\operatorname{Ci}(x) = \gamma + \ln x + \int_0^x \frac{\cos t - 1}{t}\,dt\), for \(x > 0\).""",
            s("Tap it, then type the number."),
            ex(f("ci", "1")), ex(int(fr(f("cos", "x"), "x")))),
        "exponential integral" to g("""The exponential integral \(\operatorname{Ei}(x) = \int_{-\infty}^{x} \frac{e^t}{t}\,dt\), taken as a principal value.""",
            s("Tap it, then type the number."),
            ex(f("ei", "1")), ex(int(fr(m("e", p("x")), "x")))),
        "logarithmic integral" to g("""The logarithmic integral \(\operatorname{li}(x) = \int_0^x \frac{dt}{\ln t}\); by the prime number theorem, \(\pi(x) \sim \operatorname{li}(x)\).""",
            s("Tap it, then type the number."),
            ex(f("li", "10")), ex(int(fr("1", f("ln", "x"))))),
        "polylogarithm" to g("""The polylogarithm \(\operatorname{Li}_s(z) = \sum_{k=1}^{\infty} \frac{z^k}{k^s}\) for \(|z| < 1\), with \(\operatorname{Li}_1(z) = -\ln(1 - z)\).""",
            s("""Type the order \(s\) in the small box, then \(z\)."""),
            ex(f("polylog", "2", "1")), ex(f("polylog", "2", fr("1", "2")))),
        "hyperbolic sine integral" to g("""The hyperbolic sine integral \(\operatorname{Shi}(x) = \int_0^x \frac{\sinh t}{t}\,dt\).""",
            s("Tap it, then type the number."),
            ex(f("shi", "1")), ex(int(fr(f("sinh", "x"), "x")))),
        "hyperbolic cosine integral" to g("""The hyperbolic cosine integral \(\operatorname{Chi}(x) = \gamma + \ln x + \int_0^x \frac{\cosh t - 1}{t}\,dt\).""",
            s("Tap it, then type the number."),
            ex(f("chi", "1"))),
        "Fresnel sine integral" to g("""The Fresnel integral \(S(x) = \int_0^x \sin\frac{\pi t^2}{2}\,dt\), tending to \(\frac{1}{2}\). The curve \((C(t), S(t))\) is the Euler spiral.""",
            s("Tap it, then type the number."),
            ex(f("fresnels", "1")), ex(lim(f("fresnels", "x"), "x→∞"))),
        "Fresnel cosine integral" to g("""The Fresnel integral \(C(x) = \int_0^x \cos\frac{\pi t^2}{2}\,dt\), tending to \(\frac{1}{2}\).""",
            s("Tap it, then type the number."),
            ex(f("fresnelc", "1"))),
        "incomplete elliptic integral of the first kind" to g("""The incomplete elliptic integral of the first kind, \(F(\varphi \mid m) = \int_0^{\varphi} \frac{d\theta}{\sqrt{1 - m\sin^2\theta}}\); at \(\varphi = \frac{\pi}{2}\) it is the complete integral \(K(m)\).""",
            s("""Fill the angle \(\varphi\), then the parameter \(m\)."""),
            ex(f("ellipticf", "1", "0")), ex(f("ellipticf", fr("π", "2"), fr("1", "2")))),
        // ---- Combinatorics
        "Stirling number of the first kind" to g("""The signed Stirling numbers \(s(n, k)\), defined by \(x(x - 1)\cdots(x - n + 1) = \sum_k s(n, k)\,x^k\); \(|s(n, k)|\) counts permutations of \(n\) elements with \(k\) cycles.""",
            s("""Tap it: \(s(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("stirling1", "4", "2")), ex(f("stirling1", "7", "5"))),
        "Stirling number of the second kind" to g("""The Stirling numbers \(S(n, k)\): the number of partitions of an \(n\)-element set into \(k\) nonempty blocks.""",
            s("""Tap it: \(S(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("stirling2", "4", "2"))),
        "Bell number" to g("""The Bell number \(B_n = \sum_{k=0}^{n} S(n, k)\), the number of partitions of an \(n\)-element set: \(1, 1, 2, 5, 15, 52, \ldots\)""",
            s("""Tap it: \(B(\square)\).""", """Fill \(n\)."""),
            ex(f("bell", "5")), ex(f("bell", "10"))),
        "derangements" to g("""The subfactorial \(!n = n!\sum_{k=0}^{n} \frac{(-1)^k}{k!}\), the number of permutations of \(n\) elements with no fixed point; the nearest integer to \(\frac{n!}{e}\).""",
            s("""Tap it: \(!\square\).""", """Fill \(n\)."""),
            ex(f("subfactorial", "4"), note = "Four hats handed back, none to its owner."), ex(fr(f("subfactorial", "10"), "10!"))),
        "Narayana number" to g("""The Narayana number \(N(n, k) = \frac{1}{n}\binom{n}{k}\binom{n}{k - 1}\); summing over \(k\) gives the Catalan number \(C_n\).""",
            s("""Tap it: \(N(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("narayana", "5", "3"))),
        "Lah number" to g("""The unsigned Lah number \(L(n, k) = \binom{n - 1}{k - 1}\frac{n!}{k!}\): the number of partitions of an \(n\)-element set into \(k\) nonempty linearly ordered blocks.""",
            s("""Tap it: \(L(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("lah", "4", "2"))),
        "Eulerian number" to g("""The Eulerian number \(A(n, k)\): the number of permutations of \(1, \ldots, n\) with exactly \(k\) ascents.""",
            s("""Tap it: \(A(\square, \square)\).""", """Fill \(n\) and \(k\)."""),
            ex(f("eulerian", "5", "2"))),
        "rising factorial" to g("""The rising factorial (Pochhammer symbol) \(x^{(n)} = x(x + 1)\cdots(x + n - 1) = \frac{\Gamma(x + n)}{\Gamma(x)}\).""",
            s("""Tap it: \(\square^{(\square)}\).""", """Fill \(x\), then \(n\) in the raised box."""),
            ex(f("rising", "2", "3")), ex(f("rising", "x", "3"))),
        "falling factorial" to g("""The falling factorial \((x)_n = x(x - 1)\cdots(x - n + 1) = \frac{\Gamma(x + 1)}{\Gamma(x - n + 1)}\).""",
            s("""Tap it: \((\square)_{\square}\).""", """Fill \(x\), then \(n\) below."""),
            ex(f("falling", "6", "3")), ex(f("falling", "x", "2"))),
        "superfactorial" to g("""The superfactorial \(\operatorname{sf}(n) = \prod_{k=1}^{n} k!\).""",
            s("""Tap it: \(\operatorname{sf}(\square)\).""", """Fill \(n\)."""),
            ex(f("superfactorial", "5"))),
        "harmonic number" to g("""The harmonic number \(H_n = \sum_{k=1}^{n} \frac{1}{k}\), computed exactly; \(H_n = \ln n + \gamma + O\left(\frac{1}{n}\right)\).""",
            s("""Tap it: \(H_{\square}\).""", """Fill \(n\)."""),
            ex(f("harmonic", "5")), ex(sum("n", "1", "4", f("harmonic", "n")))),
        "triangular number" to g("""The triangular number \(T_n = \sum_{k=1}^{n} k = \frac{n(n + 1)}{2} = \binom{n + 1}{2}\).""",
            s("""Tap it: \(T_{\square}\).""", """Fill \(n\)."""),
            ex(f("triangular", "10"))),
        "Motzkin number" to g("""The Motzkin number \(M_n\): the number of ways to draw non-intersecting chords among \(n\) points on a circle: \(1, 1, 2, 4, 9, 21, \ldots\)""",
            s("""Tap it: \(M_{\square}\).""", """Fill \(n\)."""),
            ex(f("motzkin", "6"))),
        "Pell number" to g("""The Pell numbers, \(P_0 = 0\), \(P_1 = 1\), \(P_n = 2P_{n-1} + P_{n-2}\); the ratios \(\frac{P_{n+1}}{P_n}\) converge to \(1 + \sqrt{2}\).""",
            s("""Tap it: \(P_{\square}\).""", """Fill \(n\)."""),
            ex(f("pell", "6"))),
        "primorial" to g("""The primorial \(n\# = \prod_{p \le n} p\), the product of all primes not exceeding \(n\).""",
            s("""Tap it: \(\square\#\).""", """Fill \(n\)."""),
            ex(f("primorial", "10"))),
        // ---- Polynomials
        "Legendre polynomial" to g("""The Legendre polynomials \(P_n(x)\), orthogonal on \([-1, 1]\) with weight 1 and normalized by \(P_n(1) = 1\).""",
            s("""Tap it: \(P_{\square}(\square)\).""", """Type the degree \(n\) in the small box, then \(x\) in the brackets."""),
            ex(f("legendre", "2", "x")), ex(f("legendre", "3", fr("1", "2"))), ex(int(m(f("legendre", "2", "x"), p("2")), lo = "−1", hi = "1"), note = """Its norm, \(\frac{2}{2n + 1}\).""")),
        "Hermite polynomial" to g("""The physicists' Hermite polynomials \(H_n(x)\), orthogonal on \(\mathbb{R}\) with weight \(e^{-x^2}\); they give the eigenstates of the quantum harmonic oscillator.""",
            s("""Tap it: \(H_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("hermite", "2", "x")), ex(f("hermite", "3", "x"))),
        "probabilists' Hermite polynomial" to g("""The probabilists' Hermite polynomials \(He_n(x)\), orthogonal on \(\mathbb{R}\) with weight \(e^{-x^2/2}\).""",
            s("""Tap it: \(He_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("hermitehe", "3", "x"))),
        "Laguerre polynomial" to g("""The Laguerre polynomials \(L_n(x)\), orthogonal on \(x \ge 0\) with weight \(e^{-x}\).""",
            s("""Tap it: \(L_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("laguerre", "2", "x"))),
        "generalized Laguerre polynomial" to g("""The generalized Laguerre polynomials \(L_n^{\alpha}(x)\), orthogonal on \(x \ge 0\) with weight \(x^{\alpha} e^{-x}\).""",
            s("""Tap it: \(L_{\square}^{\square}(\square)\).""", """Fill the degree below, \(\alpha\) above, then \(x\)."""),
            ex(f("genlaguerre", "1", "α", "x")), ex(f("genlaguerre", "2", "1", "x"))),
        "Chebyshev polynomial of the first kind" to g("""The Chebyshev polynomials \(T_n(x)\), defined by \(T_n(\cos\theta) = \cos n\theta\); orthogonal on \([-1, 1]\) with weight \(\frac{1}{\sqrt{1 - x^2}}\).""",
            s("""Tap it: \(T_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("chebyshevt", "3", "x")), ex(f("chebyshevt", "3", f("cos", "θ")))),
        "Chebyshev polynomial of the second kind" to g("""The Chebyshev polynomials \(U_n(x)\), defined by \(U_n(\cos\theta) = \frac{\sin(n + 1)\theta}{\sin\theta}\); orthogonal on \([-1, 1]\) with weight \(\sqrt{1 - x^2}\).""",
            s("""Tap it: \(U_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("chebyshevu", "2", "x"))),
        "Gegenbauer polynomial" to g("""The Gegenbauer polynomials \(C_n^{\alpha}(x)\), orthogonal on \([-1, 1]\) with weight \((1 - x^2)^{\alpha - 1/2}\); \(C_n^{1/2} = P_n\).""",
            s("""Tap it: \(C_{\square}^{\square}(\square)\).""", """Fill the degree below, \(\alpha\) above, then \(x\)."""),
            ex(f("gegenbauer", "1", "α", "x")), ex(f("gegenbauer", "2", fr("1", "2"), "x"))),
        "associated Legendre function" to g("""The associated Legendre functions \(P_n^m(x) = (-1)^m (1 - x^2)^{m/2} \frac{d^m}{dx^m} P_n(x)\), the angular part of the spherical harmonics.""",
            s("""Tap it: \(P_{\square}^{\square}(\square)\).""", """Fill \(n\) below, \(m\) above, then \(x\)."""),
            ex(f("assoclegendre", "1", "1", "x")), ex(f("assoclegendre", "2", "1", fr("1", "2")))),
        "Bernoulli polynomial" to g("""The Bernoulli polynomials \(B_n(x) = \sum_{k=0}^{n} \binom{n}{k} B_k\,x^{n-k}\), where \(B_n(0) = B_n\) are the Bernoulli numbers.""",
            s("""Tap it: \(B_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("bernoullipoly", "2", "x")), ex(f("bernoullipoly", "3", "0"))),
        "Fibonacci polynomial" to g("""The Fibonacci polynomials, \(F_0 = 0\), \(F_1 = 1\), \(F_{n+1}(x) = x F_n(x) + F_{n-1}(x)\); \(F_n(1)\) is the \(n\)-th Fibonacci number.""",
            s("""Tap it: \(F_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("fibpoly", "4", "x")), ex(f("fibpoly", "10", "1"))),
        "Lucas polynomial" to g("""The Lucas polynomials, \(L_0 = 2\), \(L_1 = x\), \(L_{n+1}(x) = x L_n(x) + L_{n-1}(x)\); \(L_n(1)\) is the \(n\)-th Lucas number.""",
            s("""Tap it: \(L_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("lucaspoly", "3", "x"))),
        "Bessel polynomial" to g("""The Bessel polynomials \(y_n(x) = \sum_{k=0}^{n} \frac{(n + k)!}{(n - k)!\,k!}\left(\frac{x}{2}\right)^k\).""",
            s("""Tap it: \(y_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("besselpoly", "2", "x"))),
        "Touchard polynomial" to g("""The Touchard polynomials \(T_n(x) = \sum_{k=0}^{n} S(n, k)\,x^k\), the moments of the Poisson distribution; \(T_n(1) = B_n\).""",
            s("""Tap it: \(T_{\square}(\square)\).""", """Fill the degree, then \(x\)."""),
            ex(f("touchard", "3", "x")), ex(f("touchard", "5", "1"))),
        "cyclotomic polynomial" to g("""The cyclotomic polynomial \(\Phi_n(x) = \prod (x - \omega)\) over the primitive \(n\)-th roots of unity \(\omega\); it is irreducible over \(\mathbb{Q}\) with integer coefficients.""",
            s("""Tap it: \(\Phi_{\square}(\square)\).""", """Fill \(n\), then \(x\)."""),
            ex(f("cyclotomic", "6", "x")), ex(f("cyclotomic", "12", "x"))),
        // ---- Signals (graphs only)
        "Heaviside step" to g("""The Heaviside step function \(H(x)\): \(0\) for \(x < 0\) and \(1\) for \(x > 0\).""",
            s(SIGNALS, """Graph \(y = H(x - 2)\) to switch on at \(2\)."""),
            ex(f("heaviside", "3")), ex(f("heaviside", "−1"))),
        "rectangle function" to g("""The rectangular function \(\operatorname{rect}(x)\): \(1\) for \(|x| < \frac{1}{2}\) and \(0\) for \(|x| > \frac{1}{2}\).""",
            s(SIGNALS, """\(\operatorname{rect}(\frac{x}{4})\) is a box of width 4."""),
            ex(f("rect", "0.2")), ex(int(f("rect", "x"), lo = "−1", hi = "1"))),
        "triangle function" to g("""The triangular function \(\operatorname{tri}(x) = \max(1 - |x|, 0)\), the convolution of \(\operatorname{rect}\) with itself.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("tri", fr("1", "2")))),
        "ramp function" to g("""The ramp function \(\operatorname{ramp}(x) = \max(x, 0)\), the antiderivative of \(H(x)\).""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("ramp", "3")), ex(f("ramp", "−3"))),
        "pulse" to g("""The indicator function of an interval: \(\operatorname{pulse}(x, a, b) = 1\) for \(a \le x < b\) and \(0\) otherwise.""",
            s(SIGNALS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("pulse", "2", "1", "3"))),
        "sawtooth wave" to g("""The sawtooth wave \(\operatorname{saw}(x) = x - \lfloor x \rfloor\), periodic with period 1, with \(0 \le \operatorname{saw}(x) < 1\).""",
            s(SIGNALS, """\(\operatorname{saw}(\frac{x}{T})\) has period \(T\)."""),
            ex(f("sawtooth", fr("9", "4")))),
        "square wave" to g("""The square wave of period 1, equal to \(+1\) on the first half of each period and \(-1\) on the second.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("squarewave", "0.25"))),
        "triangle wave" to g("""The triangle wave of period 1, piecewise linear between \(-1\) and \(1\).""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("trianglewave", "0.5"))),
        "logistic sigmoid" to g("""The logistic function \(\sigma(x) = \frac{1}{1 + e^{-x}}\), increasing from 0 to 1, with \(\sigma' = \sigma(1 - \sigma)\).""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("sigmoid", "0")), ex(d(f("sigmoid", "x")))),
        "softplus" to g("""The softplus function \(\ln\left(1 + e^x\right)\), a smooth approximation of \(\max(x, 0)\) whose derivative is \(\sigma(x)\).""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("softplus", "0"))),
        "clamp" to g("""The clamp function \(\operatorname{clamp}(x, a, b) = \min(\max(x, a), b)\), the projection of \(x\) onto \([a, b]\).""",
            s(SIGNALS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("clamp", "5", "−1", "1"))),
        "linear interpolation" to g("""Linear interpolation \(\operatorname{lerp}(a, b, t) = (1 - t)\,a + t\,b\), with value \(a\) at \(t = 0\) and \(b\) at \(t = 1\).""",
            s(SIGNALS, """Fill \(a\), \(b\) and \(t\)."""),
            ex(f("lerp", "0", "10", fr("1", "2")))),
        "smoothstep" to g("""The cubic Hermite step \(3x^2 - 2x^3\) on \([0, 1]\), clamped to 0 and 1 outside, with zero derivative at both ends.""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("smoothstep", fr("1", "2")))),
        "Gaussian" to g("""The Gaussian function \(e^{-x^2}\), with \(\int_{-\infty}^{\infty} e^{-x^2}\,dx = \sqrt{\pi}\).""",
            s(SIGNALS, "Tap it and type the variable."),
            ex(f("gauss", "0")), ex(int(f("gauss", "x"), lo = "−∞", hi = "∞"))),
        "wrap" to g("""Periodic reduction: the value \(x - k(b - a)\), \(k \in \mathbb{Z}\), that lies in \(a \le x < b\).""",
            s(SIGNALS, """Fill \(x\), \(a\) and \(b\)."""),
            ex(f("wrap", fr("7", "2"), "0", "1"))),
        // ---- Symbols
        "symbol builder" to g("""Constructs a compound symbol such as \(\hat{x}_1\) or \(\dot{\theta}^2\) from a base letter, accents and indices. The result is a single atomic variable.""",
            s("Tap it and pick a letter, then an accent and scripts.", "Saved symbols appear at the top of this tab."),
        ),
        "saved symbol" to g("""A user-defined compound symbol, treated as a single atomic variable.""",
            s("Tap it wherever the symbol goes.", "Long-press it to undefine or remove it."),
        ),
        "list of constants with names" to g("""The catalogue of physical constants, each with its CODATA value, unit and reference.""",
            s("Tap it, then search by name or symbol.", "Tap a constant to put it in the line."),
        ),
        "store in variable" to g("""The assignment operator \(:=\). It binds a variable to a value, \(a := 5\), or defines a function, \(f(x) := x^2\).""",
            s("Type the letter.", "Tap :=, then type the value."),
            ex("a", w(":="), "5"), ex("f(x)", w(":="), "x", p("2"), "+1")),
        // ---- Number pad
        "all clear" to g("""Clears the input line; the action can be undone.""", s("Tap AC, or long-press backspace.")),
        "brackets" to g("""Parentheses, which group a subexpression and override the order of operations.""",
            s("Tap once to open, again to close."),
            ex("2(3+4)"), ex("(x+1)(x−1)")),
        "divide" to g("""Division as a built-up fraction \(\frac{a}{b}\); the expression before the cursor becomes the numerator.""",
            s("Type the top, tap it, then type the bottom.", """Tap \(\rightarrow\) to leave the fraction."""),
            ex(fr("1", "3"), "+", fr("1", "6")), ex(fr(fr("1", "2"), fr("3", "4")))),
        "times" to g("""Multiplication. Juxtaposition also denotes a product: \(2x\), \(3(x + 1)\).""",
            s("Tap it between factors."),
            ex("6×7"), ex(fr("2", "3"), "×", fr("9", "4"))),
        "minus" to g("""Subtraction, or the additive inverse \(-a\).""",
            s("Tap it between terms, or before a number."),
            ex("5−8")),
        "plus" to g("""Addition; rational and radical terms are combined exactly.""",
            s("Tap it between terms."),
            ex(fr("1", "2"), "+", fr("1", "3")), ex(sq("12"), "+", sq("27"))),
        "point" to g("""The decimal separator. Terminating decimals are converted to exact rationals: \(0.1 + 0.2 = \frac{3}{10}\).""",
            s("Tap it inside a number."),
            ex("0.1+0.2")),
        "backspace" to g("""Deletes the element before the cursor; a long press clears the line.""", s("Tap to delete, long-press to clear.")),
        "enter" to g("""Evaluates the input and appends the result to the history; an equation is solved for its unknown. A long press shows the worked steps, where available.""",
            s("Tap it when the line is done.", "Long-press it for the steps."),
            ex("2+3"), ex(d(m("x", p("3")))), ex("2x+3=11")),
        "x" to g("""The real variable \(x\), the default independent variable.""",
            s("Tap it wherever the variable goes."),
            ex("2x+3x"), ex("x", p("2"), "−5x+6=0")),
    )

    /**
     * An example's answer as the calculator works it out, and whether it's a decimal (shown with ≈).
     * When the exact answer is just the example again (erf(1)), its decimal instead, or nothing.
     */
    fun answer(e: Example): Pair<MathRow, Boolean>? {
        if (!e.answer) return null
        val angle = if (e.degrees) com.example.cas.engine.AngleUnit.Degrees else com.example.cas.engine.AngleUnit.Radians
        val a = com.example.cas.engine.Formatter.answer(com.example.cas.engine.Evaluator(angle, solveEquations = true).evaluate(MathCodec.copy(e.row)))
        val same = com.example.cas.engine.Latex.of(a.exact) == com.example.cas.engine.Latex.of(e.row)
        return when {
            !same -> a.exact to a.isApproximate
            a.approx != null -> a.approx to true
            else -> null
        }
    }

    /** One curve of a card's graph: what's plotted (a function of x) and its legend, in LaTeX. */
    class Curve(val row: MathRow, val label: String)

    /** A small graph on a key's card: its curves over [x], and over [y] (or fitted to them). */
    class Plot(val curves: List<Curve>, val x: ClosedFloatingPointRange<Double>, val y: ClosedFloatingPointRange<Double>? = null)

    private fun c(label: String, vararg parts: Any) = Curve(m(*parts), label)
    private fun one(name: String, label: String, lo: Double, hi: Double, y: ClosedFloatingPointRange<Double>? = null) = Plot(listOf(c(label, f(name, "x"))), lo..hi, y)
    /** A family f(n, x) at several n. */
    private fun family(name: String, sym: String, ns: List<String>, lo: Double, hi: Double, y: ClosedFloatingPointRange<Double>? = null, extra: List<String> = emptyList()) =
        Plot(ns.map { n -> c("${sym}_{$n}" + (if (extra.isEmpty()) "" else "^{${extra[0]}}"), f(name, n, *extra.toTypedArray(), "x")) }, lo..hi, y)

    /** Graphs for the keys whose function is worth seeing: the function itself, or a family of them. */
    val plots: Map<String, Plot> by lazy {
        val trig = -6.5..6.5
        mapOf(
            "natural log" to Plot(listOf(c("""\ln x""", f("ln", "x"))), 0.0..8.0, -3.0..3.0),
            "log base a" to Plot(listOf(c("""\log_2 x""", f("log", "2", "x")), c("""\log_{10} x""", f("log", "10", "x"))), 0.0..10.0, -3.0..4.0),
            "absolute value" to one("abs", """|x|""", -4.0, 4.0, -1.0..4.0),
            "nth root" to Plot(listOf(c("""\sqrt{x}""", sq("x")), c("""\sqrt[3]{x}""", rt("3", "x"))), -8.0..8.0, -2.5..3.0),
            "power" to Plot(listOf(c("x^2", "x", p("2")), c("x^3", "x", p("3")), c("2^x", "2", p("x"))), -2.5..2.5, -4.0..6.0),
            "e" to Plot(listOf(c("e^x", "e", p("x")), c("e^{-x}", "e", p("−x"))), -3.0..3.0, -0.5..6.0),
            "factorial" to Plot(listOf(c("""\Gamma(x + 1)""", f("gamma", "x+1"))), -3.5..4.0, -6.0..10.0),
            "sin" to one("sin", """\sin x""", trig.start, trig.endInclusive, -1.6..1.6),
            "cos" to one("cos", """\cos x""", trig.start, trig.endInclusive, -1.6..1.6),
            "tan" to one("tan", """\tan x""", trig.start, trig.endInclusive, -4.0..4.0),
            "inverse sin" to one("asin", """\arcsin x""", -1.2, 1.2, -2.0..2.0),
            "inverse cos" to one("acos", """\arccos x""", -1.2, 1.2, -0.5..3.5),
            "inverse tan" to one("atan", """\arctan x""", -8.0, 8.0, -2.0..2.0),
            "hyperbolic sin" to one("sinh", """\sinh x""", -3.0, 3.0, -6.0..6.0),
            "hyperbolic cos" to one("cosh", """\cosh x""", -3.0, 3.0, -1.0..6.0),
            "hyperbolic tan" to one("tanh", """\tanh x""", -4.0, 4.0, -1.5..1.5),
            "inverse hyperbolic sin" to one("asinh", """\operatorname{asinh} x""", -8.0, 8.0, -3.0..3.0),
            "inverse hyperbolic cos" to one("acosh", """\operatorname{acosh} x""", 0.0, 8.0, -0.5..3.0),
            "inverse hyperbolic tan" to one("atanh", """\operatorname{atanh} x""", -1.2, 1.2, -3.0..3.0),
            "cosecant" to one("csc", """\csc x""", trig.start, trig.endInclusive, -4.0..4.0),
            "secant" to one("sec", """\sec x""", trig.start, trig.endInclusive, -4.0..4.0),
            "cotangent" to one("cot", """\cot x""", trig.start, trig.endInclusive, -4.0..4.0),
            "inverse cosecant" to one("acsc", """\operatorname{acsc} x""", -5.0, 5.0, -2.0..2.0),
            "inverse secant" to one("asec", """\operatorname{asec} x""", -5.0, 5.0, -0.5..3.5),
            "inverse cotangent" to one("acot", """\operatorname{acot} x""", -6.0, 6.0, -2.0..2.0),
            "hyperbolic cosecant" to one("csch", """\operatorname{csch} x""", -4.0, 4.0, -4.0..4.0),
            "hyperbolic secant" to one("sech", """\operatorname{sech} x""", -5.0, 5.0, -0.3..1.3),
            "hyperbolic cotangent" to one("coth", """\operatorname{coth} x""", -4.0, 4.0, -4.0..4.0),
            "inverse hyperbolic cosecant" to one("acsch", """\operatorname{acsch} x""", -4.0, 4.0, -3.0..3.0),
            "inverse hyperbolic secant" to one("asech", """\operatorname{asech} x""", 0.0, 1.2, -0.5..3.5),
            "inverse hyperbolic cotangent" to one("acoth", """\operatorname{acoth} x""", -4.0, 4.0, -3.0..3.0),
            "e to the i theta" to Plot(listOf(c("""\operatorname{Re} e^{ix}""", f("cos", "x")), c("""\operatorname{Im} e^{ix}""", f("sin", "x"))), trig, -1.6..1.6),
            // Distributions.
            "normal density" to Plot(listOf("0.5", "1", "2").map { s -> c("""\sigma = $s""", f("normpdf", "x", "0", s)) }, -5.0..5.0, -0.05..0.85),
            "normal distribution function" to Plot(listOf("0.5", "1", "2").map { s -> c("""\sigma = $s""", f("normcdf", "x", "0", s)) }, -5.0..5.0, -0.1..1.1),
            "exponential density" to Plot(listOf("0.5", "1", "2").map { l -> c("""\lambda = $l""", f("exppdf", "x", l)) }, 0.0..4.0, -0.1..2.1),
            "exponential distribution function" to Plot(listOf("0.5", "1", "2").map { l -> c("""\lambda = $l""", f("expcdf", "x", l)) }, 0.0..5.0, -0.1..1.1),
            "uniform density" to Plot(listOf(c("""a = 1,\ b = 3""", f("unifpdf", "x", "1", "3"))), 0.0..4.0, -0.1..0.8),
            "uniform distribution function" to Plot(listOf(c("""a = 1,\ b = 3""", f("unifcdf", "x", "1", "3"))), 0.0..4.0, -0.1..1.1),
            "chi-squared density" to Plot(listOf("1", "2", "4").map { k -> c("""k = $k""", f("chi2pdf", "x", k)) }, 0.0..8.0, -0.05..0.6),
            "chi-squared distribution function" to Plot(listOf("1", "2", "4").map { k -> c("""k = $k""", f("chi2cdf", "x", k)) }, 0.0..10.0, -0.1..1.1),
            "log-normal density" to Plot(listOf("0.5", "1").map { s -> c("""\sigma = $s""", f("lognpdf", "x", "0", s)) }, 0.0..4.0, -0.05..0.9),
            "log-normal distribution function" to Plot(listOf("0.5", "1").map { s -> c("""\sigma = $s""", f("logncdf", "x", "0", s)) }, 0.0..4.0, -0.1..1.1),
            "Cauchy density" to Plot(listOf(c("""\text{Cauchy}""", f("cauchypdf", "x", "0", "1")), c("""\mathcal{N}(0, 1)""", f("normpdf", "x", "0", "1"))), -5.0..5.0, -0.03..0.45),
            "Cauchy distribution function" to Plot(listOf(c("""\gamma = 1""", f("cauchycdf", "x", "0", "1"))), -6.0..6.0, -0.1..1.1),
            "Weibull density" to Plot(listOf("0.5", "1", "2").map { k -> c("""k = $k""", f("weibpdf", "x", k, "1")) }, 0.0..3.0, -0.1..2.1),
            "Weibull distribution function" to Plot(listOf("0.5", "1", "2").map { k -> c("""k = $k""", f("weibcdf", "x", k, "1")) }, 0.0..3.0, -0.1..1.1),
            "inverse normal" to Plot(listOf(c("""\Phi^{-1}(x)""", f("invnorm", "x"))), 0.0..1.0, -3.0..3.0),
            // Special functions.
            "gamma function" to Plot(listOf(c("""\Gamma(x)""", f("gamma", "x"))), -4.0..5.0, -6.0..8.0),
            "Riemann zeta function" to Plot(listOf(c("""\zeta(x)""", f("zeta", "x"))), -6.0..6.0, -3.0..4.0),
            "Lambert W function" to Plot(listOf(c("""W(x)""", f("lambertw", "x"))), -0.5..6.0, -1.5..2.0),
            "Bessel function of the first kind" to Plot(listOf("0", "1", "2").map { n -> c("""J_{$n}""", f("besselj", n, "x")) }, 0.0..15.0, -0.6..1.1),
            "Bessel function of the second kind" to Plot(listOf("0", "1", "2").map { n -> c("""Y_{$n}""", f("bessely", n, "x")) }, 0.0..15.0, -1.5..0.7),
            "error function" to Plot(listOf(c("""\operatorname{erf} x""", f("erf", "x"))), -3.0..3.0, -1.3..1.3),
            "imaginary error function" to Plot(listOf(c("""\operatorname{erfi} x""", f("erfi", "x"))), -2.0..2.0, -6.0..6.0),
            "upper incomplete gamma function" to Plot(listOf("1", "2", "3").map { s -> c("""\Gamma($s, x)""", f("gammainc", s, "x")) }, 0.0..6.0, -0.2..2.2),
            "digamma function" to Plot(listOf(c("""\psi(x)""", f("digamma", "x"))), -3.0..5.0, -6.0..4.0),
            "Hurwitz zeta function" to Plot(listOf("0.5", "1", "2").map { a -> c("""\zeta(x, $a)""", f("hurwitz", "x", a)) }, 1.0..6.0, -0.5..6.0),
            "sine integral" to Plot(listOf(c("""\operatorname{Si} x""", f("si", "x"))), -15.0..15.0, -2.2..2.2),
            "cosine integral" to Plot(listOf(c("""\operatorname{Ci} x""", f("ci", "x"))), 0.0..15.0, -2.0..1.0),
            "exponential integral" to Plot(listOf(c("""\operatorname{Ei} x""", f("ei", "x"))), -4.0..3.0, -4.0..8.0),
            "logarithmic integral" to Plot(listOf(c("""\operatorname{li} x""", f("li", "x"))), 0.0..10.0, -4.0..7.0),
            "polylogarithm" to Plot(listOf("1", "2", "3").map { s -> c("""\operatorname{Li}_{$s}""", f("polylog", s, "x")) }, -3.0..0.95, -2.0..3.0),
            "hyperbolic sine integral" to Plot(listOf(c("""\operatorname{Shi} x""", f("shi", "x"))), -4.0..4.0, -8.0..8.0),
            "hyperbolic cosine integral" to Plot(listOf(c("""\operatorname{Chi} x""", f("chi", "x"))), 0.0..4.0, -4.0..8.0),
            "Fresnel sine integral" to Plot(listOf(c("""S(x)""", f("fresnels", "x")), c("""C(x)""", f("fresnelc", "x"))), -5.0..5.0, -1.0..1.0),
            "Fresnel cosine integral" to Plot(listOf(c("""C(x)""", f("fresnelc", "x")), c("""S(x)""", f("fresnels", "x"))), -5.0..5.0, -1.0..1.0),
            "incomplete elliptic integral of the first kind" to Plot(listOf("0", "0.5", "0.9").map { k -> c("""m = $k""", f("ellipticf", "x", k)) }, 0.0..3.0, -0.2..5.0),
            // Polynomials.
            "Legendre polynomial" to family("legendre", "P", listOf("2", "3", "4"), -1.0, 1.0, -1.1..1.1),
            "Hermite polynomial" to family("hermite", "H", listOf("2", "3", "4"), -2.2, 2.2, -25.0..25.0),
            "probabilists' Hermite polynomial" to family("hermitehe", "He", listOf("2", "3", "4"), -3.2, 3.2, -8.0..10.0),
            "Laguerre polynomial" to family("laguerre", "L", listOf("2", "3", "4"), -1.0, 10.0, -8.0..8.0),
            "generalized Laguerre polynomial" to Plot(listOf("2", "3").map { n -> c("""L_{$n}^{1}""", f("genlaguerre", n, "1", "x")) }, -1.0..10.0, -6.0..8.0),
            "Chebyshev polynomial of the first kind" to family("chebyshevt", "T", listOf("2", "3", "4"), -1.0, 1.0, -1.2..1.2),
            "Chebyshev polynomial of the second kind" to family("chebyshevu", "U", listOf("2", "3", "4"), -1.0, 1.0, -5.0..5.0),
            "Gegenbauer polynomial" to Plot(listOf("2", "3", "4").map { n -> c("""C_{$n}^{1}""", f("gegenbauer", n, "1", "x")) }, -1.0..1.0, -5.0..5.0),
            "associated Legendre function" to Plot(listOf(c("""P_2^{1}""", f("assoclegendre", "2", "1", "x")), c("""P_3^{1}""", f("assoclegendre", "3", "1", "x")), c("""P_3^{2}""", f("assoclegendre", "3", "2", "x"))), -1.0..1.0, -8.0..8.0),
            "Bernoulli polynomial" to family("bernoullipoly", "B", listOf("2", "3", "4"), -0.5, 1.5, -0.3..0.4),
            "Fibonacci polynomial" to family("fibpoly", "F", listOf("2", "3", "4"), -2.0, 2.0, -6.0..6.0),
            "Lucas polynomial" to family("lucaspoly", "L", listOf("2", "3", "4"), -2.5, 2.5, -8.0..12.0),
            "Bessel polynomial" to family("besselpoly", "y", listOf("1", "2", "3"), -3.0, 1.0, -4.0..6.0),
            "Touchard polynomial" to family("touchard", "T", listOf("2", "3", "4"), -3.0, 1.5, -2.0..6.0),
            "cyclotomic polynomial" to family("cyclotomic", """\Phi""", listOf("3", "4", "6"), -2.0, 2.0, -1.0..7.0),
            // Signals.
            "Heaviside step" to one("heaviside", """H(x)""", -3.0, 3.0, -0.3..1.3),
            "rectangle function" to one("rect", """\operatorname{rect} x""", -2.0, 2.0, -0.3..1.3),
            "triangle function" to one("tri", """\operatorname{tri} x""", -2.0, 2.0, -0.3..1.3),
            "ramp function" to one("ramp", """\operatorname{ramp} x""", -3.0, 3.0, -0.5..3.0),
            "pulse" to Plot(listOf(c("""\operatorname{pulse}(x, 1, 3)""", f("pulse", "x", "1", "3"))), -1.0..5.0, -0.3..1.3),
            "sawtooth wave" to one("sawtooth", """\operatorname{saw} x""", -2.5, 2.5, -0.3..1.3),
            "square wave" to one("squarewave", """\operatorname{sq} x""", -2.0, 2.0, -1.4..1.4),
            "triangle wave" to one("trianglewave", """\operatorname{tw} x""", -2.0, 2.0, -1.4..1.4),
            "logistic sigmoid" to one("sigmoid", """\sigma(x)""", -6.0, 6.0, -0.2..1.2),
            "softplus" to Plot(listOf(c("""\operatorname{softplus} x""", f("softplus", "x")), c("""\operatorname{ramp} x""", f("ramp", "x"))), -4.0..4.0, -0.5..4.0),
            "clamp" to Plot(listOf(c("""\operatorname{clamp}(x, -1, 1)""", f("clamp", "x", "−1", "1"))), -3.0..3.0, -1.6..1.6),
            "linear interpolation" to Plot(listOf(c("""\operatorname{lerp}(1, 3, x)""", f("lerp", "1", "3", "x"))), -0.5..1.5, 0.0..4.0),
            "smoothstep" to Plot(listOf(c("""\operatorname{smoothstep} x""", f("smoothstep", "x")), c("x", "x")), -0.5..1.5, -0.3..1.3),
            "Gaussian" to Plot(listOf(c("""e^{-x^2}""", f("gauss", "x"))), -3.0..3.0, -0.1..1.2),
            "wrap" to Plot(listOf(c("""\operatorname{wrap}(x, 0, 1)""", f("wrap", "x", "0", "1"))), -2.0..2.0, -0.3..1.3),
            // Calculus: a function and what the key makes of it.
            "integral" to Plot(listOf(c("""\cos x""", f("cos", "x")), c("""\int_0^x \cos t\,dt""", f("sin", "x"))), trig, -1.6..1.6),
            "Taylor series" to Plot(listOf(c("""\sin x""", f("sin", "x")), c("""x - \frac{x^3}{6}""", "x−", fr(m("x", p("3")), "6")), c("""x - \frac{x^3}{6} + \frac{x^5}{120}""", "x−", fr(m("x", p("3")), "6"), "+", fr(m("x", p("5")), "120"))), -5.0..5.0, -2.0..2.0),
        )
    }

    /**
     * The graph's curves sampled at [n] points across its x range (NaN where a curve is undefined),
     * worked out with the graphs' own compiler, so they match what the graphing modes draw.
     */
    fun sample(plot: Plot, n: Int = 240): List<DoubleArray> = plot.curves.map { curve ->
        val e = com.example.cas.engine.Evaluator().evaluate(MathCodec.copy(curve.row))
        val fn = com.example.cas.graph.Compiler.compile(e, listOf("x"))
        val arg = DoubleArray(1)
        DoubleArray(n) { i ->
            arg[0] = plot.x.start + (plot.x.endInclusive - plot.x.start) * i / (n - 1)
            runCatching { fn(arg) }.getOrDefault(Double.NaN)
        }
    }

    /** The digits share one guide. */
    val digit = g("""A decimal digit. A number written next to a variable or bracket denotes a product: \(2x\), \(3(x + 1)\).""", s("Tap the digits in order."), ex("12×34"))

    /** Any Latin or Greek letter: a variable. */
    val letter = g("""A variable. It is bound to a value with \(:=\), as in \(a := 5\); in the graphing modes an unbound variable becomes a slider.""",
        s("Tap it wherever the letter goes."), ex("2α+3α"))
}
