package com.example.cas.ui

/**
 * The "How to use" part of each key's explanation: where the key's boxes go and a worked
 * example. It replaces the usage written with the key's help, so every key has one.
 */
internal object KeyHowTo {
    val usage: Map<String, String> = mapOf(
        // ---- Basic
        "pi" to """Kept exact: \(\sin\frac{\pi}{6} = \frac{1}{2}\). Tap ≈ on an answer for the decimal, \(\pi \approx 3.14159\).""",
        "e" to """Kept exact: \(\ln e^3 = 3\). Type e, then the power key, for \(e^x\).""",
        "power" to """Raises what's before the cursor; type the exponent, then → to leave it. \(2^{10} = 1024\), \((x + 1)^2\) expands with Expand.""",
        "nth root" to """Fill the small box with \(n\), then the number under the root: \(\sqrt[3]{27} = 3\).""",
        "factorial" to """Put it after a number or bracket: \(5! = 120\). Non-whole numbers use \(\Gamma\): \(0.5! = \frac{\sqrt{\pi}}{2}\).""",
        "natural log" to """\(\ln e^2 = 2\), \(\ln 8 = 3 \ln 2\). Logs of negatives are complex: \(\ln(-1) = \pi i\).""",
        "log base a" to """Fill the base in the small box: \(\log_2 8 = 3\), \(\log_{10} 1000 = 3\).""",
        "absolute value" to """Type the number inside the bars: \(|-7| = 7\), \(|3 + 4i| = 5\). In a graph, \(y = |x|\) is a V.""",
        "mod" to """Between two numbers: \(17 \bmod 5 = 2\). The answer has the sign of the divisor: \(-7 \bmod 3 = 2\).""",
        "i, the imaginary unit" to """\(i^2 = -1\): \((2 + i)(3 - i) = 7 + i\). Answers can be shown as \(r e^{i\theta}\) (Settings).""",
        "equals sign" to """Makes an equation to solve: \(x^2 = 9\) gives \(x = -3, x = 3\). In the graphs, \(y = \ldots\) or an equation in \(x\) and \(y\).""",
        "less than" to """Makes an inequality: \(2x + 1 < 7\) gives \(x < 3\). In the graphs it shades the region.""",
        "greater than" to """\(x^2 > 4\) gives \(x < -2\) or \(x > 2\). Type > then = for \(\ge\).""",
        "comma" to """Separates values in lists and functions with several inputs: \(\gcd(12, 18)\), mean(1, 2, 3).""",
        "previous answer" to """Ans is the last answer: after \(3 \cdot 4 = 12\), Ans + 1 = 13. An operator pressed straight after = also starts from it.""",
        // ---- Trigonometry
        "sin" to """\(\sin\frac{\pi}{6} = \frac{1}{2}\); in Deg, \(\sin 30 = \frac{1}{2}\). Rad/Deg above the keys sets the angle unit; exact at multiples of 30° and 45°.""",
        "inverse sin" to """\(\arcsin\frac{1}{2} = \frac{\pi}{6}\) (30 in Deg). For \(|x| > 1\) the answer is complex.""",
        "hyperbolic sin" to """\(\sinh 0 = 0\), \(\sinh x = \frac{e^x - e^{-x}}{2}\); try \(\frac{d}{dx}\sinh x = \cosh x\).""",
        "inverse hyperbolic sin" to """\(\operatorname{asinh} x = \ln\left(x + \sqrt{x^2 + 1}\right)\): \(\operatorname{asinh} 0 = 0\).""",
        "cos" to """\(\cos\frac{\pi}{3} = \frac{1}{2}\); in Deg, \(\cos 60 = \frac{1}{2}\).""",
        "inverse cos" to """\(\arccos 0 = \frac{\pi}{2}\) (90 in Deg). Defined for \(-1 \le x \le 1\).""",
        "hyperbolic cos" to """\(\cosh 0 = 1\); a hanging chain has the shape \(y = \cosh x\).""",
        "inverse hyperbolic cos" to """\(\operatorname{acosh} 1 = 0\); for \(x \ge 1\) it's \(\ln\left(x + \sqrt{x^2 - 1}\right)\).""",
        "tan" to """\(\tan\frac{\pi}{4} = 1\); in Deg, \(\tan 45 = 1\). Undefined at \(\frac{\pi}{2}\).""",
        "inverse tan" to """\(\arctan 1 = \frac{\pi}{4}\); \(\int \frac{1}{1 + x^2}\,dx = \arctan x + C\).""",
        "hyperbolic tan" to """\(\tanh 0 = 0\); it tends to \(\pm 1\): \(\lim_{x \to \infty} \tanh x = 1\).""",
        "inverse hyperbolic tan" to """\(\operatorname{atanh} x = \frac{1}{2}\ln\frac{1 + x}{1 - x}\), for \(|x| < 1\).""",
        // ---- Reciprocal trigonometry (the trigonometry tab's second page)
        "cosecant" to """On the trigonometry tab, the 1/△ switch beside Rad/Deg shows it. \(\csc\frac{\pi}{6} = 2\); in Deg, \(\csc 30 = 2\).""",
        "inverse cosecant" to """1/△ switch on the trigonometry tab. \(\operatorname{acsc} 2 = \frac{\pi}{6}\), for \(|x| \ge 1\).""",
        "hyperbolic cosecant" to """1/△ switch on the trigonometry tab. \(\operatorname{csch} x = \frac{1}{\sinh x}\); \(\operatorname{csch} 1 \approx 0.8509\).""",
        "inverse hyperbolic cosecant" to """1/△ switch on the trigonometry tab. \(\operatorname{acsch} 1 = \ln\left(1 + \sqrt{2}\right)\).""",
        "secant" to """1/△ switch on the trigonometry tab. \(\sec\frac{\pi}{3} = 2\); in Deg, \(\sec 60 = 2\). \(\int \sec x\,dx\) has steps.""",
        "inverse secant" to """1/△ switch on the trigonometry tab. \(\operatorname{asec} 2 = \frac{\pi}{3}\), for \(|x| \ge 1\).""",
        "hyperbolic secant" to """1/△ switch on the trigonometry tab. \(\operatorname{sech} 0 = 1\); graph \(y = \operatorname{sech} x\) for a soliton's bell.""",
        "inverse hyperbolic secant" to """1/△ switch on the trigonometry tab. \(\operatorname{asech} 1 = 0\), for \(0 < x \le 1\).""",
        "cotangent" to """1/△ switch on the trigonometry tab. \(\cot\frac{\pi}{4} = 1\); \(\frac{d}{dx}\cot x = -\csc^2 x\).""",
        "inverse cotangent" to """1/△ switch on the trigonometry tab. \(\operatorname{acot} 1 = \frac{\pi}{4}\).""",
        "hyperbolic cotangent" to """1/△ switch on the trigonometry tab. \(\operatorname{coth} x = \frac{\cosh x}{\sinh x}\), undefined at 0.""",
        "inverse hyperbolic cotangent" to """1/△ switch on the trigonometry tab. \(\operatorname{acoth} 2 = \frac{1}{2}\ln 3\), for \(|x| > 1\).""",
        // ---- Calculus
        "partial derivative" to """Fill the function, then tap the \(x\) in \(\partial x\) to change the variable: \(\frac{\partial}{\partial y}\left(x^2 y\right) = x^2\). Long-press = for steps.""",
        "integral" to """Fill the body; the limits are optional: \(\int_0^1 x^2\,dx = \frac{1}{3}\), \(\int x e^x\,dx = (x - 1)e^x + C\). \(\infty\) works as a limit.""",
        "limit" to """Type the expression, then change \(a\) under lim: \(\lim_{x \to 0} \frac{\sin x}{x} = 1\). \(\infty\) is allowed.""",
        "sum" to """Fill the variable, its start and end, then the body: \(\sum_{k=1}^{100} k = 5050\), \(\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}\).""",
        "product" to """Like Σ: \(\prod_{k=1}^{5} k = 120\).""",
        "Taylor series" to """Fill the function, the point and the order: taylor(\(e^x\), \(x \to 0\), 3) gives \(1 + x + \frac{x^2}{2} + \frac{x^3}{6}\).""",
        "y prime" to """For differential equations: \(y' = y\) with the solve key gives \(y = C e^x\).""",
        "y double prime" to """\(y'' + y = 0\) solves to \(y = C_1 \cos x + C_2 \sin x\).""",
        "solve differential equation" to """Type the equation in the box, with conditions after commas: \(y' = 2y, y(0) = 1\) gives \(y = e^{2x}\).""",
        "infinity" to """As a limit: \(\int_0^{\infty} e^{-x}\,dx = 1\), \(\lim_{x \to \infty} \frac{1}{x} = 0\).""",
        "gradient" to """\(\nabla\left(x^2 + y^2\right) = (2x, 2y)\). Put 2 in the small box for the Laplacian. The switch above the keys picks the coordinates.""",
        "divergence" to """Give \(F\) as a vector: \(\nabla \cdot (x, y, z) = 3\).""",
        "curl" to """\(\nabla \times (-y, x, 0) = (0, 0, 2)\).""",
        "Jacobian matrix" to """Of a vector function: J\((x y, x + y)\) is the matrix of its partial derivatives.""",
        "Hessian matrix" to """Of a scalar function: H\((x^2 y)\) gives the matrix of second derivatives.""",
        // ---- Linear algebra
        "matrix" to """Pick the size, then fill the boxes; it grows as you type in the last row or column.""",
        "inverse" to """After a matrix: \(\begin{bmatrix} 2 & 0 \\ 0 & 4 \end{bmatrix}^{-1} = \begin{bmatrix} \frac{1}{2} & 0 \\ 0 & \frac{1}{4} \end{bmatrix}\). Long-press = for the steps.""",
        "transpose" to """After a matrix: rows become columns, \(\begin{bmatrix} 1 & 2 \end{bmatrix}^{\top}\) is a column.""",
        "conjugate transpose" to """After a matrix: transpose and conjugate. Real matrices: the same as the transpose.""",
        "determinant" to """det of a square matrix: \(\det \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} = -2\).""",
        "dot product" to """Two vectors of the same length: \((1, 2, 3) \cdot (4, 5, 6) = 32\).""",
        "cross product" to """Two 3-vectors: \((1, 0, 0) \times (0, 1, 0) = (0, 0, 1)\).""",
        "Hadamard product" to """Entry by entry, same sizes: \(\begin{bmatrix} 1 & 2 \end{bmatrix} \circ \begin{bmatrix} 3 & 4 \end{bmatrix} = \begin{bmatrix} 3 & 8 \end{bmatrix}\).""",
        "Kronecker product" to """Every entry of the first times the whole second: a 2×2 ⊗ 2×2 is 4×4.""",
        "trace" to """The diagonal added: \(\operatorname{tr}\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} = 5\).""",
        "eigenvalues" to """λ of a square matrix: \(\begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}\) gives \(\lambda = 2, \lambda = 3\). Long-press = for the steps.""",
        "eigenvectors" to """Each eigenvalue with its vector: \(\begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}\) has \(\lambda = 3\) with \((1, 1)\).""",
        "characteristic polynomial" to """\(\det(A - \lambda I)\): for \(\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}\) it's \(\lambda^2 - 5\lambda - 2\).""",
        "reduced row echelon form" to """Solve a system from its augmented matrix: rref shows the solution in the last column. Long-press = for the row steps.""",
        "rank" to """How many independent rows: \(\operatorname{rk}\begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix} = 1\).""",
        // ---- Statistics
        "mean" to """Type the values with commas: mean(2, 4, 4, 5) = \(\frac{15}{4}\).""",
        "median" to """median(3, 1, 7, 5) = 4: the middle value, or the average of the two middle ones.""",
        "sample standard deviation" to """s(2, 4, 4, 4, 5, 5, 7, 9) \(\approx 2.138\), dividing by \(n - 1\).""",
        "population standard deviation" to """σ(2, 4, 4, 4, 5, 5, 7, 9) = 2, dividing by \(n\).""",
        "sample variance" to """\(s^2\)(1, 2, 3, 4) = \(\frac{5}{3}\).""",
        "n choose k" to """Fill \(n\) on top, \(k\) below: \(\binom{5}{2} = 10\). Also with letters: \(\binom{n}{2} = \frac{n(n - 1)}{2}\).""",
        "permutations" to """Ordered choices: P(5, 2) = 20.""",
        "normal density" to """normpdf(x, μ, σ), μ = 0 and σ = 1 filled in: normpdf(0, 0, 1) \(= \frac{1}{\sqrt{2\pi}}\). It's a formula, so it graphs.""",
        "normal distribution function" to """normcdf(1.96, 0, 1) \(\approx 0.975\): the chance of a value at most 1.96.""",
        "inverse normal" to """The value with that probability below it: \(\Phi^{-1}(0.975) \approx 1.96\).""",
        "binomial probability" to """Bin(n, p, k): exactly \(k\) successes in \(n\) trials. Bin(10, 0.5, 5) \(= \frac{63}{256}\).""",
        "cumulative binomial probability" to """At most \(k\) successes: binomcdf(10, 0.5, 5) \(= \frac{319}{512}\).""",
        "Poisson probability" to """poissonpdf(λ, k): exactly \(k\) events at rate λ. poissonpdf(2, 0) \(= e^{-2}\).""",
        "sum of a list" to """Values separated by commas: total(1, 2, 3, 4) = 10.""",
        "comma for lists" to """Separates the values: mean(1, 2, 3).""",
        // ---- Distributions (the statistics tab's second page)
        "exponential density" to """The pdf/cdf switch on the statistics tab shows it. Fill \(x\) and the rate λ: \(f(1, 2) = 2e^{-2}\). Graph \(y = f(x, 1)\) to see it.""",
        "exponential distribution function" to """pdf/cdf switch on the statistics tab. The chance of waiting at most 1 at rate 2: \(1 - e^{-2} \approx 0.865\).""",
        "uniform density" to """pdf/cdf switch on the statistics tab. Fill \(x, a, b\): \(f(3, 1, 5) = \frac{1}{4}\).""",
        "uniform distribution function" to """pdf/cdf switch on the statistics tab. \(F(3, 1, 5) = \frac{1}{2}\).""",
        "cumulative Poisson probability" to """pdf/cdf switch on the statistics tab. Fill λ and \(k\): at most 3 events at rate 2 is \(\approx 0.857\).""",
        "geometric probability" to """pdf/cdf switch on the statistics tab. Fill \(p\) and \(k\): the first six on the third roll, \(p = \frac{1}{6}\), \(k = 3\), is \(\frac{25}{216}\).""",
        "cumulative geometric probability" to """pdf/cdf switch on the statistics tab. A six within 3 rolls: \(1 - \left(\frac{5}{6}\right)^3 = \frac{91}{216}\).""",
        "chi-squared density" to """pdf/cdf switch on the statistics tab. Fill \(x\) and the degrees of freedom \(k\): \(f(1, 3) \approx 0.242\).""",
        "chi-squared distribution function" to """pdf/cdf switch on the statistics tab. \(F(7.815, 3) \approx 0.95\), the 5% critical value for 3 degrees of freedom.""",
        "log-normal density" to """pdf/cdf switch on the statistics tab. Fill \(x, \mu, \sigma\): \(f(1, 0, 1) = \frac{1}{\sqrt{2\pi}}\).""",
        "log-normal distribution function" to """pdf/cdf switch on the statistics tab. \(F(1, 0, 1) = \frac{1}{2}\): half the values are below \(e^{\mu}\).""",
        "Cauchy density" to """pdf/cdf switch on the statistics tab. Fill \(x, x_0, \gamma\): \(f(0, 0, 1) = \frac{1}{\pi}\).""",
        "Cauchy distribution function" to """pdf/cdf switch on the statistics tab. \(F(1, 0, 1) = \frac{3}{4}\).""",
        "Weibull density" to """pdf/cdf switch on the statistics tab. Fill \(x\), the shape \(k\) and the scale λ: \(f(1, 2, 1) = 2e^{-1}\).""",
        "Weibull distribution function" to """pdf/cdf switch on the statistics tab. \(F(1, 2, 1) = 1 - e^{-1} \approx 0.632\).""",
        // ---- Complex numbers
        "real part" to """\(\Re(3 + 4i) = 3\); \(\Re\, e^{i\theta} = \cos\theta\).""",
        "imaginary part" to """\(\Im(3 + 4i) = 4\).""",
        "conjugate" to """\((3 + 4i)^* = 3 - 4i\); \(z z^* = |z|^2\).""",
        "argument" to """The angle of \(z\): \(\angle(1 + i) = \frac{\pi}{4}\) (45 in Deg).""",
        "e to the i theta" to """Fill the angle: \(e^{i\pi} = -1\), \(e^{i\pi/2} = i\).""",
        "gamma function" to """\(\Gamma(5) = 24\), \(\Gamma\left(\frac{1}{2}\right) = \sqrt{\pi}\). Graph it in the complex plane to see its poles.""",
        "Riemann zeta function" to """Exact at even whole numbers: \(\zeta(2) = \frac{\pi^2}{6}\); \(\zeta(-1) = -\frac{1}{12}\).""",
        "Lambert W function" to """Solves \(x e^x = a\): \(W(1) \approx 0.5671\), and \(x e^x = 2\) gives \(x = W(2)\).""",
        "Bessel function of the first kind" to """The order \(a\) goes in the small box: \(J_0(0) = 1\); graph \(y = J_0(x)\) for a damped wave.""",
        "Bessel function of the second kind" to """The order \(a\) goes in the small box: \(Y_0(1) \approx 0.0883\); it's infinite at 0.""",
        "contour integral" to """Fill the function; the circle \(|z| = 1\) is filled in, change it to any circle: \(\oint_{|z| = 1} \frac{1}{z}\,dz = 2\pi i\).""",
        "residue" to """Fill the function, then set the point underneath: \(\operatorname{Res}_{z = 0} \frac{e^z}{z^2} = 1\).""",
        "z" to """The variable of the complex plane: plot \(f(z) = z^2\) there. In the calculator it's a letter like any other.""",
        "w" to """A second complex letter, for \(w = f(z)\) or a parameter.""",
        // ---- Special functions
        "error function" to """\(\operatorname{erf}(0) = 0\), \(\operatorname{erf}(1) \approx 0.8427\); \(\int_0^x e^{-t^2}\,dt = \frac{\sqrt{\pi}}{2}\operatorname{erf}(x)\).""",
        "imaginary error function" to """\(\operatorname{erfi}(1) \approx 1.6505\); \(\int e^{x^2}\,dx = \frac{\sqrt{\pi}}{2}\operatorname{erfi}(x) + C\).""",
        "upper incomplete gamma function" to """Fill \(s\) and \(x\): \(\Gamma(1, x) = e^{-x}\); \(\Gamma(s, 0) = \Gamma(s)\).""",
        "digamma function" to """\(\psi(1) = -\gamma \approx -0.5772\); \(\frac{d}{dx}\ln\Gamma(x) = \psi(x)\).""",
        "Hurwitz zeta function" to """Fill \(s\) and \(a\): \(\zeta(2, 1) = \frac{\pi^2}{6}\), for \(s > 1\).""",
        "sine integral" to """\(\int \frac{\sin x}{x}\,dx = \operatorname{Si}(x) + C\); \(\operatorname{Si}(\infty) = \frac{\pi}{2}\).""",
        "cosine integral" to """\(\int \frac{\cos x}{x}\,dx = \operatorname{Ci}(x) + C\); \(\operatorname{Ci}(1) \approx 0.3374\).""",
        "exponential integral" to """\(\int \frac{e^x}{x}\,dx = \operatorname{Ei}(x) + C\); \(\operatorname{Ei}(1) \approx 1.8951\).""",
        "logarithmic integral" to """\(\int \frac{1}{\ln x}\,dx = \operatorname{li}(x) + C\); \(\operatorname{li}(x)\) is close to the count of primes up to \(x\).""",
        "polylogarithm" to """The order \(s\) in the small box: \(\operatorname{Li}_2(1) = \frac{\pi^2}{6}\), \(\operatorname{Li}_1(x) = -\ln(1 - x)\).""",
        "hyperbolic sine integral" to """\(\int \frac{\sinh x}{x}\,dx = \operatorname{Shi}(x) + C\).""",
        "hyperbolic cosine integral" to """\(\int \frac{\cosh x}{x}\,dx = \operatorname{Chi}(x) + C\).""",
        "Fresnel sine integral" to """\(S(1) \approx 0.4383\); integrals of \(\sin x^2\) come out in it. Graph \(S(x)\) against \(C(x)\) for the Euler spiral.""",
        "Fresnel cosine integral" to """\(C(1) \approx 0.7799\); both tend to \(\frac{1}{2}\).""",
        "incomplete elliptic integral of the first kind" to """Fill the angle φ and the parameter \(m\): \(F(\varphi \mid 0) = \varphi\); a pendulum's period uses \(F\left(\frac{\pi}{2} \mid m\right)\).""",
        // ---- Combinatorics
        "Stirling number of the first kind" to """Shown as \(s(\square, \square)\): fill \(n\) and \(k\). \(s(4, 2) = 11\). Long-press = for the definition.""",
        "Stirling number of the second kind" to """Shown as \(S(\square, \square)\): \(S(4, 2) = 7\), splitting 4 things into 2 groups.""",
        "Bell number" to """Shown as \(B(\square)\): \(B(5) = 52\). Graph \(y = B(x)\) to see it grow (as steps).""",
        "derangements" to """Shown as \(!\square\): \(!4 = 9\) ways to hand back 4 hats with nobody getting their own.""",
        "Narayana number" to """Shown as \(N(\square, \square)\): \(N(5, 3) = 20\); summed over \(k\) they give the Catalan number.""",
        "Lah number" to """Shown as \(L(\square, \square)\): \(L(4, 2) = 36\).""",
        "Eulerian number" to """Shown as \(A(\square, \square)\): \(A(5, 2) = 66\); \(A(n, k) = \sum_{j=0}^{k} (-1)^j \binom{n+1}{j}(k + 1 - j)^n\).""",
        "rising factorial" to """Shown as \(x^{(n)}\): fill \(x\), then \(n\) in the raised box. \(2^{(3)} = 24\); with a letter, \(x^{(3)} = x^3 + 3x^2 + 2x\).""",
        "falling factorial" to """Shown as \((x)_n\): \((6)_3 = 120\), ordered choices of 3 from 6.""",
        "superfactorial" to """Shown as \(\operatorname{sf}(\square)\): \(\operatorname{sf}(5) = 34560\).""",
        "harmonic number" to """Shown as \(H_{\square}\): \(H_5 = \frac{137}{60}\). \(\sum_{n=1}^{4} H_n = \frac{77}{12}\). Graphs as a smooth curve.""",
        "triangular number" to """Shown as \(T_{\square}\): \(T_{10} = 55\).""",
        "Motzkin number" to """Shown as \(M_{\square}\): \(M_6 = 51\).""",
        "Pell number" to """Shown as \(P_{\square}\): \(P_6 = 70\); \(\frac{P_{n+1}}{P_n} \to 1 + \sqrt{2}\).""",
        "primorial" to """Shown as \(\square\#\): \(10\# = 2 \cdot 3 \cdot 5 \cdot 7 = 210\).""",
        // ---- Polynomials
        "Legendre polynomial" to """Shown as \(P_{\square}(\square)\): the degree in the small box, then the variable. \(P_2(x) = \frac{3x^2 - 1}{2}\); \(P_3\left(\frac{1}{2}\right) = -\frac{7}{16}\).""",
        "Hermite polynomial" to """Shown as \(H_{\square}(\square)\): \(H_2(x) = 4x^2 - 2\).""",
        "probabilists' Hermite polynomial" to """Shown as \(He_{\square}(\square)\): \(He_2(x) = x^2 - 1\).""",
        "Laguerre polynomial" to """Shown as \(L_{\square}(\square)\): \(L_1(x) = 1 - x\), \(L_2(x) = \frac{x^2 - 4x + 2}{2}\).""",
        "generalized Laguerre polynomial" to """Shown as \(L_{\square}^{\square}(\square)\): the degree below, α above. \(L_1^{\alpha}(x) = 1 + \alpha - x\).""",
        "Chebyshev polynomial of the first kind" to """Shown as \(T_{\square}(\square)\): \(T_3(x) = 4x^3 - 3x\), and \(T_3(\cos\theta) = \cos 3\theta\).""",
        "Chebyshev polynomial of the second kind" to """Shown as \(U_{\square}(\square)\): \(U_2(x) = 4x^2 - 1\).""",
        "Gegenbauer polynomial" to """Shown as \(C_{\square}^{\square}(\square)\): degree below, α above. \(C_1^{\alpha}(x) = 2\alpha x\); \(\alpha = \frac{1}{2}\) gives Legendre.""",
        "associated Legendre function" to """Shown as \(P_{\square}^{\square}(\square)\): \(n\) below, \(m\) above. \(P_1^1(x) = -\sqrt{1 - x^2}\); graph it on \([-1, 1]\).""",
        "Bernoulli polynomial" to """Shown as \(B_{\square}(\square)\): \(B_2(x) = x^2 - x + \frac{1}{6}\).""",
        "Fibonacci polynomial" to """Shown as \(F_{\square}(\square)\): \(F_3(x) = x^2 + 1\); \(F_n(1)\) is the Fibonacci number.""",
        "Lucas polynomial" to """Shown as \(L_{\square}(\square)\): \(L_2(x) = x^2 + 2\).""",
        "Bessel polynomial" to """Shown as \(y_{\square}(\square)\): \(y_2(x) = 3x^2 + 3x + 1\).""",
        "Touchard polynomial" to """Shown as \(T_{\square}(\square)\): \(T_3(x) = x^3 + 3x^2 + x\); \(T_3(1) = 5\), the Bell number.""",
        "cyclotomic polynomial" to """Shown as \(\Phi_{\square}(\square)\): \(\Phi_6(x) = x^2 - x + 1\), \(\Phi_5(x) = x^4 + x^3 + x^2 + x + 1\).""",
        // ---- Signals (graphs only: the button left of the letters above the keypad)
        "Heaviside step" to """In the graphs, the button left of the letters above the keypad. \(y = H(x - 2)\) switches on at 2.""",
        "rectangle function" to """Graphs only. \(y = \operatorname{rect}\left(\frac{x}{4}\right)\) is a box of width 4.""",
        "triangle function" to """Graphs only. \(y = 3\operatorname{tri}(x)\): a peak of height 3.""",
        "ramp function" to """Graphs only. \(y = \operatorname{ramp}(x - 1)\) starts rising at 1.""",
        "pulse" to """Graphs only. Fill \(x\), \(a\), \(b\): \(y = \operatorname{pulse}(x, 1, 3)\) is 1 from 1 to 3.""",
        "sawtooth wave" to """Graphs only. \(y = \operatorname{saw}\left(\frac{x}{T}\right)\) has period \(T\).""",
        "square wave" to """Graphs only. \(y = \operatorname{sq}(2x)\) switches every quarter.""",
        "triangle wave" to """Graphs only. \(y = 2\operatorname{tw}(x)\) zig-zags between \(-2\) and 2.""",
        "logistic sigmoid" to """Graphs only. \(y = \sigma(x - 3)\) is \(\frac{1}{2}\) at 3; \(\sigma'(x) = \sigma(x)(1 - \sigma(x))\).""",
        "softplus" to """Graphs only. Compare \(y = \operatorname{softplus}(x)\) with \(y = \operatorname{ramp}(x)\).""",
        "clamp" to """Graphs only. \(y = \operatorname{clamp}(x, -1, 1)\) is cut off at \(\pm 1\).""",
        "linear interpolation" to """Graphs only. Fill \(a\), \(b\), \(t\): \(\operatorname{lerp}(0, 10, \frac{1}{2}) = 5\).""",
        "smoothstep" to """Graphs only. \(y = S\left(\frac{x}{2}\right)\) eases from 0 to 1 over \([0, 2]\).""",
        "Gaussian" to """Graphs only. \(y = g\left(\frac{x}{2}\right)\) is twice as wide; normpdf is the normalized one.""",
        "wrap" to """Graphs only. \(y = \operatorname{wrap}(x, -1, 1)\) repeats the line between \(-1\) and 1.""",
        // ---- Number pad and symbols
        "all clear" to """Clears the line. Long-press backspace does the same.""",
        "brackets" to """Opens a bracket; the next one closes it. \(2(3 + 4) = 14\).""",
        "divide" to """Makes a fraction: what's before the cursor goes on top. \(\frac{1}{3} + \frac{1}{6} = \frac{1}{2}\).""",
        "times" to """\(6 \cdot 7 = 42\). Next to a letter or bracket you can leave it out: \(2x\).""",
        "minus" to """\(5 - 8 = -3\); also a negative sign.""",
        "plus" to """\(\frac{1}{2} + \frac{1}{3} = \frac{5}{6}\).""",
        "point" to """Decimals: \(0.1 + 0.2 = \frac{3}{10}\), kept exact.""",
        "backspace" to """Deletes before the cursor; a long-press clears everything.""",
        "enter" to """Works the line out. Long-press it for the steps when there are some.""",
        "x" to """The variable: \(x^2 - 1 = 0\) gives \(x = \pm 1\). Other letters are on the Aα tab.""",
        "list of constants with names" to """Opens every constant with its name, value and units; search by name (\(c\), Planck…) and tap one to type it. \(m_e c^2\) gives the electron's rest energy.""",
        "symbol builder" to """Build a symbol like \(\hat{x}_1\): it acts as one letter (one backspace deletes it). Saved symbols appear at the top of this tab.""",
    )
}
